### ISSUE TITLE
Use of single-sided bandwidth for RadioSetRxConfig in examples

### ISSUE THREAD

**Issue by cirnod** [Lora-net/LoRaMac-node#1005]
In issue #928, it was stated that the bandwidth provided to `RadioSetRxConfig()` should be the single-sided bandwidth (SSB) not the double-sided bandwidth (DSB) for the SX126x platform. In the examples, for example [here](https://github.com/Lora-net/LoRaMac-node/blob/master/src/apps/ping-pong/NucleoL476/main.c#L227), it seems that still the double-sided bandwidth is provided to `RadioSetRxConfig()` for the sx126x and LR1110 chips.

**Comment by mluis1** [comment]
Thanks for the finding.

We forgot to update the ping-pong and rx-sensi examples.
We will provide a fix as soon as possible.
