### ISSUE TITLE
sx126x Calibration Image  need timeout?

### ISSUE THREAD

**Issue by alexrayne** [Lora-net/LoRaMac-node#1008]
Hallow!
i tests sample modem application for SX1261 transiver chip.

And found that when after command RADIO_CALIBRATEIMAGE goes TX Freq setup - it fails somehow. When i make pause more then 0.7ms it work well.

Can anybody explain behaviour of calibration commands? It not produces BUSY signal, but need timeout?

**Comment by mluis1** [comment]
The description you provide is not very clear and it is hard to understand what you are the steps being executed.

Could you tell us the steps to reproduce the issue?
Even better can you provide an example code which reproduces the issue?

In the future it would be nice if you could post this kind of questions on the project [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab. It is a better place to engage discussions and then we can agree if it is an issue or not.
If you don't mind I move this issue to the [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab.
