### ISSUE TITLE
how to debug this project "LoMac-node-periodic-uplink-lpp"?

### ISSUE THREAD

**Issue by enddls** [Lora-net/LoRaMac-node#1011]
I want to debug LoMac-node-periodic-uplink-lpp.

but this project does not include keil project.

how to debug this project "LoMac-node-periodic-uplink-lpp"?

**Comment by mluis1** [comment]
You have already asked a similar question on this project.

Please refer to the answers provided on issue #971 


In the future it would be nice if you could post this kind of questions on the project [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab. It is a better place to engage discussions and then we can agree if it is an issue or not.
If you don't mind I move this issue to the [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab.
