### ISSUE TITLE
Redundant semicolon in lr1110/radio.c

### ISSUE THREAD

**Issue by C47D** [Lora-net/LoRaMac-node#1012]
https://github.com/Lora-net/LoRaMac-node/blob/bb606c8416c8428d6704eb635b57ccd1ff42eeb0/src/radio/lr1110/radio.c#L657

Introduced with bb606c8416c8428d6704eb635b57ccd1ff42eeb0

**Comment by mluis1** [comment]
Thanks for the finding. It is fixed.
