### ISSUE TITLE
TimerStart(), TimerStop() functions unconditionally enable interrupts on return

### ISSUE THREAD

**Issue by catsup** [Lora-net/LoRaMac-node#103]
The TimerStart() and TimerStop() functions (in src/system/timer.c) disable interrupts upon entry, and re-enable interrupts when returning, regardless of whether interrupts were disabled or not before entry.

This can cause problems if the calling flow disabled interrupts and relies on them to remain disabled.

Interrupts should only be re-enabled if they were previously disabled (ie by reference counting or checking interrupt status upon function entry).

**Comment by pdemil** [comment]
> Interrupts should only be re-enabled if they were previously disabled

Interrupts should only be re-enabled if they were previously enabled

**Comment by catsup** [comment]
Yes, obviously. Thanks for the correction.

**Comment by mluis1** [comment]
We will try to provide a fix for this as soon as possible.
