### ISSUE TITLE
Support for STM32WL55xx

### ISSUE THREAD

**Issue by MarekNovakACRIOS** [Lora-net/LoRaMac-node#1035]
Dear community,

Is the support fo STM32WL55xx planned?
I checked the license and it should be possible to include it in /src/radio folder of the repo side by SX126x, SX127x support etc.

It will need some dependency cleanup from ST trace headers maybe, but otherwise it is integrablable I think.

I also modified portions in radio.c for this platform (RadioIrqProcess() and RadioOnDioIrq() - a lot of processing was done directly in ISR, although there is the IrqProcess entry in struct Radio_s, which should be polled from non-ISR context).

I attach my modified version in an archive and I am able to integrate it / create pull request if this is wanted.

Regards! 

[stm32WL55.zip](https://github.com/Lora-net/LoRaMac-node/files/5892823/stm32WL55.zip)

**Comment by mluis1** [comment]
At the moment we have no plans to add support for the STM32WL55xx platform.

We will consider this addition once we get access to a development platform.

In the meantime you can use the libraries provided by ST as the provided LoRaWAN stack is based on this project.
In discussions tab of this project there are already 2 topics talking about the same subject. (#1003 and #1023)

In the future it would be nice if you could post this kind of questions on the project Discussions tab. It is a better place to engage discussions and then we can agree if it is an issue or not.
If you don't mind I move this issue to the Discussions tab.
