### ISSUE TITLE
sx126x radio.c

### ISSUE THREAD

**Issue by RomanJasmann** [Lora-net/LoRaMac-node#1059]
1. The critical section in RadioIrqProcess is not applied properly:

![grafik](https://user-images.githubusercontent.com/80332798/110952271-4eec7200-8346-11eb-9c0b-abb624fdbb0b.png)

Fix:

```
void RadioIrqProcess(void) {
    uint8_t fired;

    CRITICAL_SECTION_BEGIN( );
    fired = IrqFired;
    IrqFired = 0;
    CRITICAL_SECTION_END( );

    if (fired == true) {

```

2. There is a missing TimerStop for the RxTimeoutTimer:

![grafik](https://user-images.githubusercontent.com/80332798/110953046-36c92280-8347-11eb-8d00-fb81d9635d5f.png)

Fix: 

```
        if( ( irqRegs & IRQ_RX_DONE ) == IRQ_RX_DONE )
        {
            TimerStop( &RxTimeoutTimer );
```

3. In case of a header error, the RxError callback should be called:

![grafik](https://user-images.githubusercontent.com/80332798/110953784-07ff7c00-8348-11eb-98b8-2c5c67d3b77d.png)

Fix:

```
        if( ( irqRegs & IRQ_HEADER_ERROR ) == IRQ_HEADER_ERROR )
        {
            TimerStop( &RxTimeoutTimer );
            if( RxContinuous == false )
            {
                //!< Update operating mode state to a value lower than \ref MODE_STDBY_XOSC
                SX126xSetOperatingMode( MODE_STDBY_RC );
            }
            if( ( RadioEvents != NULL ) && ( RadioEvents->RxTimeout != NULL ) )
            {
                RadioEvents->RxError( );
            }
        }
```

**Comment by mluis1** [comment]
Thanks for the findings.

We agree with first two findings.

Concerning third finding we think that the implementation is correct as it is.

The `IRQ_HEADER_ERROR` can be seen as an RxTimemout.
This interrupt may happen at the beginning of the reception and as such it is similar to the RxTimeout.  
The RxTimeout corresponds to the amount of time required to receive the LoRa header.  
When the `IRQ_HEADER_ERROR` is generated the radio cannot anyway continue the reception process.

The RxError callback is more to notify the upper layer that there was a CRC error on the received frame.

**Comment by mluis1** [comment]
@RomanJasmann Could you please review the proposition?

**Comment by RomanJasmann** [comment]
@mluis1 you have fixed it.
