### ISSUE TITLE
SK-IM880 - inconsistent reading of vdd / battery level

### ISSUE THREAD

**Issue by Regimbal** [Lora-net/LoRaMac-node#106]
Hello all,
While upgrade from LoRaMac 4.0 to 4.3, I observed the BoardMeasureVdd does not returns the same value.
Last release returns an inconsistent value.
Anyone could eventually confirm this? or give me a solution?

Thanks a lot,
Nicolas

EDIT:
on an other board, the application is blocked during the ADC conversion.
I managed to solve my problem with the little patch below.
The other commented parameters hadc->Init could also be of some use although I did not qualified them.

`
uint16_t AdcMcuRead( Adc_t *obj, uint8_t channel )
{
        ADC_HandleTypeDef *hadc;
        ADC_ChannelConfTypeDef adcConf;
        uint16_t adcData = 0;

```
    hadc = &obj->Adc;

        /* Enable HSI */
    __HAL_RCC_HSI_ENABLE();

    /* Wait till HSI is ready */
    while(__HAL_RCC_GET_FLAG(RCC_FLAG_HSIRDY) == RESET)
    {
    }

    __HAL_RCC_ADC1_CLK_ENABLE( );

    hadc->Instance = ADC1;
    /*hadc->Init.ClockPrescaler = ADC_CLOCK_ASYNC_DIV1;
    hadc->Init.Resolution = ADC_RESOLUTION12b;
    hadc->Init.DataAlign = ADC_DATAALIGN_RIGHT;
    hadc->Init.ScanConvMode = DISABLE;*/
    hadc->Init.EOCSelection = EOC_SINGLE_CONV;
    /*hadc->Init.LowPowerAutoWait = ADC_AUTOWAIT_DISABLE;
    hadc->Init.LowPowerAutoPowerOff = ADC_AUTOPOWEROFF_IDLE_PHASE;
    hadc->Init.ChannelsBank = ADC_CHANNELS_BANK_A;
    hadc->Init.ContinuousConvMode = DISABLE;
    hadc->Init.NbrOfConversion = 1;
    hadc->Init.DiscontinuousConvMode = DISABLE;
    hadc->Init.ExternalTrigConv = ADC_SOFTWARE_START;
    hadc->Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
    hadc->Init.DMAContinuousRequests = DISABLE;*/
    HAL_ADC_Init(hadc);

    adcConf.Channel = channel;
    adcConf.Rank = ADC_REGULAR_RANK_1;
    adcConf.SamplingTime = ADC_SAMPLETIME_192CYCLES;

    HAL_ADC_ConfigChannel( hadc, &adcConf);

    /* Enable ADC1 */
    __HAL_ADC_ENABLE( hadc) ;
```

`

**Comment by ChrisEAlfred** [comment]
Why do all implementations of adc-board.c AdcMcuReadChannel()  contain:
    // Disable HSI
    __HAL_RCC_HSI_DISABLE( );
at the end?

This is called via PrepareTxFrame(). Isn't the processor running the HSI at this point? In which case, the HSI is prematurely turned off by the read of the battery calling AdcMcuReadChannel().

It seems quite bizarre (wrong?) to be managing the CPU clock from an ADC read!
