### ISSUE TITLE
Type to store milliseconds usage in LoRaMac.

### ISSUE THREAD

**Issue by me9atherion** [Lora-net/LoRaMac-node#1061]
Hello.
Everywhere in LoRaMac stack code I see that millisecond timestamps stored in variables with type TimerTime_t. Some of these variables are initialized from SysTimeToMs() or from TimerGetCurrentTime().
However here such variable is stored as **uint32_t** (which is equivalent type to TimerTime_t now, but potentially may be changed in future):
![image](https://user-images.githubusercontent.com/74147534/111164733-0253a180-85a7-11eb-89ef-ac40fcc6b0f0.png)

Also may be "milliseconds-related" functions in systime.c/h should also be updated with decent milliseconds type?

**Comment by mluis1** [comment]
Thanks for reporting this. We will try to implement this enhancement as soon as possible.
