### ISSUE TITLE
LmhpCompliance.c error in array size

### ISSUE THREAD

**Issue by x893** [Lora-net/LoRaMac-node#1064]
Hi,
LmhpCompliance.c

**if( index < ( sizeof( periodicity ) / sizeof( uint16_t ) ) )**
but **periodicity** define as **uint32_t periodicity[]** so must change to
**if( index < ( sizeof( periodicity ) / sizeof( uint32_t ) ) )**

Best wishes

**Comment by mluis1** [comment]
Thanks for the finding. Will be corrected for next release.
