### ISSUE TITLE
Tried to run LoRaMac-node firmware on NAMote-72 hardware

### ISSUE THREAD

**Issue by vipul-embedded** [Lora-net/LoRaMac-node#107]
I have tried to run LoRaMac-Node firmware on NAMote-72 hardware compiled in Keil. I have done essential modification of SPI and DIO pins. But there was no any communication on LoRa.

Does anybody has tried to do same? If yes, kindly let me know is it working ?
What should i take care extra?

Regards,

**Comment by mluis1** [comment]
NAMote72 hardware isn't a supported platform yet. In the mean time you may refer to the following mbed project which is synchronized with this repository.
https://developer.mbed.org/teams/Semtech/code/LoRaWAN-NAMote72-Application-Demo/
