### ISSUE TITLE
Broken link to the porting guide

### ISSUE THREAD

**Issue by Willybood** [Lora-net/LoRaMac-node#1085]
The link to the porting guide in the readme is broken. Is it still available?

Thanks, this could be really useful for an upcoming project.

**Comment by mluis1** [comment]
We forgot to update the link when we changed the documentation site to provide pages for each individual release.

The right link is: http://stackforce.github.io/LoRaMac-doc/LoRaMac-doc-v4.5.1/_p_o_r_t_i_n_g__g_u_i_d_e.html

We will fix the link as soon as possible.

**Comment by Willybood** [comment]
Thanks, and thanks for taking a look at this so quickly!
