### ISSUE TITLE
LoraWan Connection issue with ABP

### ISSUE THREAD

**Issue by Ahsan-Averos** [Lora-net/LoRaMac-node#1092]
Dear Sir
Please correct me what I am doing wrong, I done it number of serval trial to connect with gateway but unable to do this.
Although my Lora communication is working fine.

Reference code:
[(https://github.com/insightsip/ISP4520-examples)]

**Hardware:**

nrf52832
E22900M22S(Sx1262)

**Please see the response in log file.**

_> app: LoRaWan end-device started.
<info> app: Initializing fds...
<info> app: Reading flash usage statistics...
<info> app: Found 7 valid records.
<info> app: Found 75 dirty records (ready to be garbage collected).
<debug> app: Record 3 at 7D06C
<debug> app: Record 4 at 7D1D0
<debug> app: Record 6 at 7D41C
<debug> app: Record 7 at 7D4F0
<debug> app: Record 80 at 7ED9C
<debug> app: Record 81 at 7EDDC
<debug> app: Record 82 at 7EE00
<info> app: Data restored from NVM: 1208 bytes
<info> app: MLME-Request: MLME_JOIN, OK
<debug> app: Uplink counter   : 26
<debug> app: Uplink Data rate : DR_0
<debug> app: Uplink TX power  : 0
<debug> app: Uplink frequency: 868500000
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x1
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x2
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x5
<info> app: Data stored on NVM: 224 bytes
<info> app: MCPS-Request: MCPS_UNCONFIRMED,  OK
<debug> app: Uplink counter   : 27
<debug> app: Uplink Data rate : DR_0
<debug> app: Uplink TX power  : 0
<debug> app: Uplink frequency: 868300000
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x1
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x2
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x5
<info> app: Data stored on NVM: 224 bytes
<info> app: MCPS-Request: MCPS_UNCONFIRMED,  OK
<debug> app: Uplink counter   : 28
<debug> app: Uplink Data rate : DR_0
<debug> app: Uplink TX power  : 0
<debug> app: Uplink frequency: 868300000
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x1
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x2
<debug> app: FDS update success! FileId: 0x3E8 RecKey:0x5
<info> app: Data stored on NVM: 224 bytes
<info> app: MCPS-Request: MCPS_UNCONFIRMED,  OK_

**And also see what I changed in code** 

 
![image](https://user-images.githubusercontent.com/81947656/117609652-d3f2dc80-b179-11eb-9ac4-286bcb7b7387.png)
![image](https://user-images.githubusercontent.com/81947656/117610487-46b08780-b17b-11eb-97f0-8f3b482f3b94.png)
![image](https://user-images.githubusercontent.com/81947656/117609736-f4229b80-b179-11eb-9314-d8a909052667.png)

**Server data**
Device address:

![image](https://user-images.githubusercontent.com/81947656/117610056-89be2b00-b17a-11eb-8d8c-b4f5bd765f0c.png)

Network + App  session keys:

![image](https://user-images.githubusercontent.com/81947656/117610110-a195af00-b17a-11eb-8452-a47f0d9228f6.png)

Graph:

![image](https://user-images.githubusercontent.com/81947656/117610165-b7a36f80-b17a-11eb-976e-246dc5035686.png)

I hope that someone helping me out in this.
Thanks in advance.....

**Comment by mluis1** [comment]
First I would like to clarify something. An end-device does not connect to a gateway. An end-device connects to a network server.
A gateway is just a dumb device that translates what is received on the RF to the IP world and vice versa.

Which Network Server are you using?

Most of the network servers that I'm aware of use big endian encoding for the `DevAddr`. The LoRaMac-node project also encodes the `DevAddr` as big endian (see comment above `LORAWAN_DEVICE_ADDRESS` definition).

On your screen shot you have entered the `DevAddr` encoded as little endian.

`DevAddr` should be: `60595857`

In the future it would be nice if you could post this kind of questions on the project [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab. It is a better place to engage discussions and then we can agree if it is an issue or not.
If you don't mind I move this issue to the [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab.
