### ISSUE TITLE
Datarate retransmission management

### ISSUE THREAD

**Issue by mpt8153** [Lora-net/LoRaMac-node#112]
I've a question about the management of datarate when ack is not received for a confirmed message type:
    /*!
     * Number of trials to transmit the frame, if the LoRaMAC layer did not
     * receive an acknowledgment. The MAC performs a datarate adaptation,
     * according to the LoRaWAN Specification V1.0.1, chapter 19.4, according
     * to the following table:
     *
     * Transmission nb | Data Rate
     * ----------------|-----------
     * 1 (first)       | DR
     * 2               | DR
     * 3               | max(DR-1,0)
     * 4               | max(DR-1,0)
     * 5               | max(DR-2,0)
     * 6               | max(DR-2,0)
     * 7               | max(DR-3,0)
     * 8               | max(DR-3,0)
     *

I don't understand how stack manage DR if payload has a valid payload for DR but this length is not valid for DR-1.

For example in EU 863-870MHz ISM Band if I want to transmit a payload of 60 bytes at DR = 3 and I don't receive an ack what happen when datarate is decreased at DR = 2 where a payload of 60 byte is not allowed?

BR

**Comment by djaeckle** [comment]
Hi mpt8153,

thanks for the report. Your statement is correct. Currently, the MAC does not verify if the payload length is valid in case it decreases the DR. We will provide a fix for it soon.
