### ISSUE TITLE
Classes A to B or C

### ISSUE THREAD

**Issue by JulienArmenti** [Lora-net/LoRaMac-node#113]
Hi,

The master branch and the feature/class_b have a different loramac.c source code.

Which one I need to use if I want to switch beetween classe A and B or C in my firmware?
I want my board always in class A but, if an action is done, it's go to class B or C.

 Is class B and C have past LoRa-Alliance compliance tests ? Is there a software available to test class B or C ?

Thanks,
Have a good week end.
Julien

**Comment by djaeckle** [comment]
Hi JulienArmenti,

in general, you will find a description of the repository branches in the wiki. The master branch contains always the latest stable version. At the moment, it contains the sources according to the LoRaWAN Specification v1.0.1. This version passes all compliance tests for Class A. The version contains also an implementation for Class C, but currently, there is no compliance test available to test against.

On the develop branch, we implement the next version of the LoRaWAN Specification, which is v1.0.2. However, please note, that the develop branch is not tested with the compliance tests.

The feature branch for Class B implements the Class B device according to LoRaWAN Specification 1.1. However, please note, that this Specification is still experimental will most likely change in the future. Also, there is no compliance test available yet.
