### ISSUE TITLE
DevNonce and DR are not refresh on join request attempts

### ISSUE THREAD

**Issue by ettmyfox** [Lora-net/LoRaMac-node#114]
In my mind, I think there is a little software regression on release 4.3.0.

in this commit : https://github.com/Lora-net/LoRaMac-node/commit/b3d0141470ee66fa0869b68f40dd3e1f5fc278b7

in older release : 
ChannelsNbRepCounter = ChannelsNbRep; so Join messages aren't repeated automatically
in new release :
ChannelsNbRepCounter = 0; so join messages are repeated automatically and DevNonce and DR are not refreshed, which is not compliant with LoRa specification

**Comment by djaeckle** [comment]
Hi ettmyfox,

thanks for the report. We will provide an update soon.

**Comment by mluis1** [comment]
Leave a comment
