### ISSUE TITLE
Printf for LoRaMAC 4.5.2

### ISSUE THREAD

**Issue by meakash** [Lora-net/LoRaMac-node#1143]
Respected all,

 I have trying to use the STM32 L073 based Firmware for Periodic Lpp Uplink and although i am getting Join Requests and Join Accepts I am not getting any uplink data. So I tried to insert printf commands and include stdio.h file in the headers, but i am not getting any output on the console. 

Can please somebody help me with the Baud rate and the communication. I am currently using a Nucleo F303RE to program the .bin file to my Hardware.

**Comment by mluis1** [comment]
By default this project sets up the UART parameters with 921600 bits/s 8N1.
The choice for this bit rate is to avoid as much as possible to disturb the LoRaWAN protocol handling.
In addition one must be careful where in the code `printf` commands are added. A `printf` takes time to be executed which may disturb some tight LoRaWAN protocol timings.

In the future it would be nice if you could post this kind of questions on the project [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab. It is a better place to engage discussions and then we can agree if it is an issue or not.
If you don't mind I move this issue to the [Discussions](https://github.com/Lora-net/LoRaMac-node/discussions) tab.
