### ISSUE TITLE
Wrong variable types

### ISSUE THREAD

**Issue by sborshch** [Lora-net/LoRaMac-node#1213]
1) LoRaMacNvmDataGroup2_t variable Rejoin0UplinksLimit is uint16_t, while in SRV_MAC_REJOIN_PARAM_REQ value 0x01 << ( maxCountN + 4 ) assigned, where maxCountN can hold value up to 15, so Rejoin0UplinksLimit must be uint32_t. LoRaMacNvmDataGroup1_t variable Rejoin0UplinksCounter must have uint32_t type also.

2) LmHandlerParams_t variable PingSlotPeriodicity has type bool, while in COMPLIANCE_PING_SLOT_INFO_REQ value of type uint8_t assigned.

3) LoRaMacNvmDataGroup2_t variable IsRejoinRequestPending actually means pending of Rejoin-accept message. Would it be better to change its name to IsRejoinAcceptPending?

**Comment by mluis1** [comment]
Thanks for the feedback.

Point 2 has been fixed by 9eed0e911cde6b298107b67bc2b5cf6ebf601151 commit.

Other points will be fixed in the coming days
