### ISSUE TITLE
RestoreNvmData doesn't restore RegionGroup2 in LoRaMac 4.6.0

### ISSUE THREAD

**Issue by Dreambound131** [Lora-net/LoRaMac-node#1254]
Hello,
In our application we need to completely shut down the LoRa chipset, so we frequently restore the Ctxs in the Loramac stack. 
Working with 915MHz band regions, we noticed that the whole RegionGroup2 is not restored when issuing a MIB_NVM_CTXS set request. Going in deep we found that "RestoreNvmData" function in LoRaMac.c actually restore all the other Context exept for RegionGroup2. We added the context restore also for Region2 and everything looks fine by now.
Below you can see the change we made, do you think there can be hidden issue in our solution? Thank you

RestoreNvmData Edited section:
>     // Region1
>     crc = Crc32( ( uint8_t* ) &nvm->RegionGroup1, sizeof( nvm->RegionGroup1 ) -
>                                             sizeof( nvm->RegionGroup1.Crc32 ) );
>     if( crc == nvm->RegionGroup1.Crc32 )
>     {
>         memcpy1( ( uint8_t* ) &Nvm.RegionGroup1,( uint8_t* ) &nvm->RegionGroup1,
>                  sizeof( Nvm.RegionGroup1 ) );
>     }
> 
>     // Region2
>     crc = Crc32( ( uint8_t* ) &nvm->RegionGroup2, sizeof( nvm->RegionGroup2 ) -
>                                             sizeof( nvm->RegionGroup2.Crc32 ) );
>     if( crc == nvm->RegionGroup2.Crc32 )
>     {
>         memcpy1( ( uint8_t* ) &Nvm.RegionGroup2,( uint8_t* ) &nvm->RegionGroup2,
>                  sizeof( Nvm.RegionGroup2 ) );
>     }

**Comment by MedadRufus** [comment]
interesting find
