### ISSUE TITLE
SX1276 don't go in TX mode

### ISSUE THREAD

**Issue by davide01frasson** [Lora-net/LoRaMac-node#1262]
i'm coding a LoRa SX1276 transceiver from a Texas Instrument TMS320F28379D. Basically i copy-pasted the Arduino libraries changing the SPI protocol methods and everthing seemed fine, i was able to switch between SLEEP and STAND-BY mode, reading register and loading data into the Reg-Fifo and updating the Reg_Payload_Length, but when it comes to switch Reg_Op_Mode to TX mode it don't works. I've tried to put delays, changing power supply but i am not able to switch mode and to start transmission.

**Comment by MedadRufus** [comment]
This repo does not deal with the Arduino libraries so you will not likely get any support here.

**Comment by mluis1** [comment]
Please consider asking your question on a forum such https://forum.lora-developers.semtech.com/ you may get better support on the issues you are observing.

Another possibility is to use the radio drivers provided by this project which are known to be fully functional.
