### ISSUE TITLE
Duplicated marco CHANNEL_PLAN_GROUP_AS923_X in src/mac/region/RegionAS923.h

### ISSUE THREAD

**Issue by Apaisal** [Lora-net/LoRaMac-node#1279]
Dear Maintainer

I found duplicated marco in src/mac/region/RegionAS923.h

master branch https://github.com/Lora-net/LoRaMac-node/commit/243864e0fb44b6f255b69d8fe29d77aa0a67f0fd https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/region/RegionAS923.h
v5.0.0-branch https://github.com/Lora-net/LoRaMac-node/commit/c12af2a9357c536edd49793181707b359b310be7 https://github.com/Lora-net/LoRaMac-node/blob/1ded7077ee7c0e7f6474bba8e18e357dc291aae1/src/mac/region/RegionAS923.h

CHANNEL_PLAN_GROUP_AS923_1 line [52](https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/region/RegionAS923.h#L52) and [70](https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/region/RegionAS923.h#L70)
CHANNEL_PLAN_GROUP_AS923_2 line [58](https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/region/RegionAS923.h#L58) and [76](https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/region/RegionAS923.h#L76)
CHANNEL_PLAN_GROUP_AS923_3 line [64](https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/region/RegionAS923.h#L64) and [82](https://github.com/Lora-net/LoRaMac-node/blob/bc9a93e1cbbea9e27b6af35dd542a96fc67f5699/src/mac/region/RegionAS923.h#L82)

Could you confirm them, please?

**Comment by mluis1** [comment]
Yes, you are right.
We will try to fix if for next release.
