### ISSUE TITLE
SRV_MAC_DEVICE_TIME_ANS processing 

### ISSUE THREAD

**Issue by yasserattar** [Lora-net/LoRaMac-node#1286]
there is a bug in this section of the code in file LoraMac.c in function ProcessMacCommands in case SRV_MAC_DEVICE_TIME_ANS 
when it want to calculate the time difference between Tx Done time and now instead of subtracting the MacCtx.LastTxSysTime from sysTimeCurrent and adding that to sysTime (what we received from network ) it takes it away from what we received from network and added it to actual cpu time that is wromg .
so this line should be corrected as follows: 
//sysTime = SysTimeAdd( sysTimeCurrent, YSysTimeSub( sysTime, MacCtx.LastTxSysTime ) );
sysTime = SysTimeAdd( sysTime , SysTimeSub(sysTimeCurrent , MacCtx.LastTxSysTime ) );

**Comment by mluis1** [comment]
Can we close this issue?
