### ISSUE TITLE
CoIDE

### ISSUE THREAD

**Issue by justinma4** [Lora-net/LoRaMac-node#13]
Hello,

I am trying to open this project in CoIDE only i get the error:
"The chil:STM32L141CBT6 information of current project has something worng."
Does anyone know this error? And how can i fix this?

Greet Justin

**Comment by mluis1** [comment]
The STM32L1**4**1CBT6 microcontroller doesn't exist. The correct name is STM32L1**5**1CBT6.
 
Have you by inadvertence changed the project files?

In case this doesn't help you can try to look or ask questions on coIDE forums.

The coIDE projects were made with version "Version: 2.0.1 Build id: 20150105-2.0.1"
