### ISSUE TITLE
Uart Receive Interrupt not working on LORAMAC Class A 

### ISSUE THREAD

**Issue by 9910292559** [Lora-net/LoRaMac-node#133]
Dear All
I want to send data on Uart while Lora Stack Running but receive interrupt not working properly.
my UART configuration show below

   FifoInit( &Uart1.FifoRx, Uart_data, 261 );
    UartInit( &Uart1, UART_1, UART_TX, UART_RX );
    UartConfig( &Uart1, RX_TX,115200, UART_8_BIT, UART_1_STOP_BIT, NO_PARITY, NO_FLOW_CTRL );

please suggest whats wrong with it

how to manage interrupt

**Comment by 9910292559** [comment]
it need some delay to work fine

**Comment by MichaelDevid** [comment]
What did you change?
