### ISSUE TITLE
Class B ping slot offset is not computed correctly when using LR11xx SE

### ISSUE THREAD

**Issue by adriansmares** [Lora-net/LoRaMac-node#1348]
Commit: 8deeabb47e58e4a9a6f6d3ffc79c00a15971b8cc
Custom settings:
  - `LORAWAN_DEFAULT_CLASS=CLASS_B`
  - `BOARD=NucleoL476`
  - `MBED_RADIO_SHIELD=LR1110MB1XXS`
  - `LORAMAC_LR_FHSS_IS_ON=ON` (should not matter, but I have it on already in my configuration)
  - `SECURE_ELEMENT=LR11XX_SE`

LR1110 firmware: [`lr1110_trx_0x0307`](https://github.com/Lora-net/SWTL001/wiki)

---

I was revisiting class B support in The Things Stack and I could not actually get the end device to receive data via the ping slot. I started comparing the parameters between what the NS was generating and what the end device was generating and I stumbled upon the fact that the ping slot offset was always zero for the end device.

`ComputePingOffset` does not check the error code of the `SecureElementAesEncrypt` call:
https://github.com/Lora-net/LoRaMac-node/blob/8deeabb47e58e4a9a6f6d3ffc79c00a15971b8cc/src/mac/LoRaMacClassB.c#L164-L168
I guess this error check is skipped because under `SOFT_SE`, it can never fail in this scenario. But it can fail under a real secure element, and it actually does with the LR1110 (at least with the transceiver firmware that I've mentioned above).

The error code reported via `status` is `6`, which is just a generic crypto error code. While checking `SecureElementAesEncrypt` of `lr11xx-se`, it seems that `lr11xx_crypto_aes_encrypt_01` is used for AES encryption instead of `lr11xx_crypto_aes_encrypt`:
https://github.com/Lora-net/LoRaMac-node/blob/8deeabb47e58e4a9a6f6d3ffc79c00a15971b8cc/src/peripherals/lr11xx-se/lr11xx-se.c#L218-L220

I don't fully understand the difference between `lr11xx_crypto_aes_encrypt_01` and `lr11xx_crypto_aes_encrypt`, but `01` always returns an error via `status` while using the `LR11XX_CRYPTO_KEYS_IDX_GP0` key. 

What I've tried and was successful with was to use `lr11xx_crypto_aes_encrypt` instead of `lr11xx_crypto_aes_encrypt_01` when `keyID` is `SLOT_RAND_ZERO_KEY`, and also manually initialized the key to all zero for safety. https://github.com/adriansmares/LoRaMac-node/commit/ea12fe3677250793af7ba9f6aaa9874dbb6ce35e what worked - this was enough to fix the encryption error and to basically get class B to work (the offset matched and then the ping slots matched).

Edit: The [LR1110 manual](https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R000000UuXU/V67TeKnUj5_zjQr7jb6BtTuBMns.4HEVdmodj11PNvI) describes the difference between `lr11xx_crypto_aes_encrypt_01` and `lr11xx_crypto_aes_encrypt`. It is indeed the case that `lr11xx_crypto_aes_encrypt` is meant to be used with the general purpose key:
![image](https://user-images.githubusercontent.com/36161392/187186959-d20dcd7a-3780-4eb1-a110-80648fbe832c.png)
<img width="933" alt="image" src="https://user-images.githubusercontent.com/36161392/187185891-404bd0be-bf65-4151-ad72-15cab0ba06dc.png">

**Comment by mluis1** [comment]
Thanks for the finding and analysis.

We will push the fix as soon as possible
