### ISSUE TITLE
Is there a problem with the RadioIsChannelFree() in sx126x->radio.c

### ISSUE THREAD

**Issue by guoweilkd** [Lora-net/LoRaMac-node#1351]
Whether the LORA mode is not considered in this [line]( https://github.com/Lora-net/LoRaMac-node/blob/master/src/radio/sx126x/radio.c#L592)

**Comment by mluis1** [comment]
RSSI readings are independent of the used modulation.

We decided to use the FSK modem to perform `RadioIsChannelFree` functionality because this modem provides more granularity for the used parameters as well as it is easier to setup the FSK modem than the LoRa modem for this specific task.
