### ISSUE TITLE
LmHandler.c: Warning if ACTIVE_REGION is undefined, but not used by this module

### ISSUE THREAD

**Issue by dmeehan1968** [Lora-net/LoRaMac-node#1356]
```
#ifndef ACTIVE_REGION

#warning "No active region defined, LORAMAC_REGION_EU868 will be used as default."

#define ACTIVE_REGION LORAMAC_REGION_EU868

#endif
```

The macro `ACTIVE_REGION` is not used by this module, its intention might be to ensure that somewhere the active region is defined, but given that its passed in `LmHandlerParams.Region`, this seems redundant.  Whilst the application examples need to ensure there is a defined active region, the LmHandler code only need validate the passed `Region`.

It's possible to define the symbol without a value in order to get the module to compile, as a workaround.

**Comment by mluis1** [comment]
Yes, indeed this can safely be removed.
I guess that when we first implemented LmHandler.c we had the need for it and then we forgot to remove it.
