### ISSUE TITLE
US band_915 Join request reschedule 

### ISSUE THREAD

**Issue by Kirankoneri** [Lora-net/LoRaMac-node#137]
Hi,

As per the LoRaWAN spec v1.0 for US 902-928Mhz ISM band, the JoinReq message should select alternate datarate either as DR4 or DR0. I have two queries in LoRaMAC v4.3.0,

1. AlternateDatarate is DR1 instead of DR0.
2. Before rescheduling for Join Request the AlternateDatarate is not chosen. 

Thank you,
Best Regards,
Kiran Koneri

**Comment by mluis1** [comment]
Thanks for the report.

We already corrected these issues in our internal repositories. 
The develop branch should be soon updated with these corrections.
