### ISSUE TITLE
LmHandlerSetSystemMaxRxError( uint32_t maxErrorInMs ) parameter value range checks missing.

### ISSUE THREAD

**Issue by kairoswater-jason** [Lora-net/LoRaMac-node#1372]
To my knowledge: the purpose of the function LmHandlerSetSystemMaxRxError( uint32_t maxErrorInMs ) is to cause the RX window to open earlier and close later to compensate for timing inaccuracies in the RX process.

If maxErrorInMs is made larger than approximately 7000ms the device will appear to hang - never opening the RX window. (at least, it odes on my custom US915 device)

I have not had time to investigate this. But I suspect that one of the RX timer parameters may experience an integer overflow. I suspect this because increasing values of maxErrorInMs seems to push the receive window to happen sooner. If maxErrorInMs is too large, the Rx window may be scheduled to occur in the past. (but experience a unsigned integer rollover and be scheduled far in the future instead)

I think this is a low priority issue caused by me misusing the API. Maybe an assertion of maxErrorInMs must be less than "some value" could be an easy "fix". Or maybe an assertion if an unintentional overflow occurs in the timer calculations (if that proves to be the issue).

My purpose in posting this is mostly to record the presence of this issue for future reference, should the need arise. I don't expect it to be worth the effort of fixing.

**Comment by mluis1** [comment]
If you don't mind I have edited the issue title as the original is quite long.

The `maxErrorInMs` value should not exceed more than a few tens of ms.

As you know the time between the end of a transmission and the opening of the 1st reception window is by default 1 second and 2 seconds for the 2nd window. 
The time between the 2 windows is always 1 second. It means that in theory the `maxErrorInMs`  should never exceed 500 ms as the error is centered on the Rx window open time.
However, I observed that in practice values bigger than 50 ms could eventually cause issues.

In case a system requires much higher values it means that there is a more fundamental issue with the hardware timer time source.

When using an XTAL as clock source a value of 20 ms is far enough to compensate the IRQ functions handling process time. When using a less precise clock source as an RC oscillator a value less then 50 ms should be enough.

We will consider to add `maxErrorInMs` value range checks in a future release. If you don't mind we close this issue as we have added this enhancement description in our internal development repository.

The below function documentation explains the influence of this parameter.
https://github.com/Lora-net/LoRaMac-node/blob/7f25f7adb5b9bf7142f98f77c68363e8b1f7e8ee/src/mac/region/Region.h#L940-L977

Note: the provided URLs are not up to date. Please find below the new URLs
SX1272 - https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/440000001NAm/Z0dk4s5E.mKYtg7cDIld77KvC7dKgWQLSEOaJc_OgGw
SX1276 - https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/440000001NAw/7YN8ZamV70_xR.vPDAAAshm.0Wt4jmRX0nOKkOzQqiI
