### ISSUE TITLE
FRAGMENTATION_FRAG_STATUS_ANS differences in specifications v1/v2

### ISSUE THREAD

**Issue by maxim-s-barabash** [Lora-net/LoRaMac-node#1407]
Hi all.
FragParam there are changes in the v2 specification, in addition, new flags have been added to the Status.MICError.
I did not find any changes in the code about this.
What do you think about this?

**v1**
![Screenshot from 2023-01-30 13-33-38](https://user-images.githubusercontent.com/2724325/215466358-8365e127-8411-44a1-aeb1-efc58db827b8.png)

**v2**
![Screenshot from 2023-01-30 13-34-30](https://user-images.githubusercontent.com/2724325/215466378-0b28ed56-2501-4dc6-a725-a3c34a438c77.png)

**Comment by mluis1** [comment]
This project currently implements version 1.0.0 of the specifications.

We did not had the time to implement version 2.0.0 of the specifications.
We don't know when we will be able to work on this update. 
However, everyone is welcome to propose such update.
