### ISSUE TITLE
Maximum Payload size with EU- ISM 868MHz

### ISSUE THREAD

**Issue by FoujanetG** [Lora-net/LoRaMac-node#15]
We would like to know if the maximum payload size in function of the DR is implemented? ==> 7.1.6 EU863-870 Maximum payload size in LoRaWAN™ Specification ,Version: V1.0

And we have try to send a Lora frame with a applicative payload of size 55. It doesn't work. 
The error code returned is 3.  Do you know if there is a bug?

Thanks a lot.
Guillaume

**Comment by mluis1** [comment]
Currently this is not implemented. 

As of today the maximum PHY payload that can be used is 64 bytes. Which means that the maximum FRMPayload size when no MAC commands is 64-1(MHDR)-7(FHDR)-1(FPort)-4(MIC) = 51 bytes. Currently this is independent of the DR.

The next version will not include this feature. But, the one after should include it.
