### ISSUE TITLE
Partial CFList 

### ISSUE THREAD

**Issue by Objenious** [Lora-net/LoRaMac-node#155]
If a device initializes its default channels with a frequency different than zero and the network sends a partial CFList (some channels with freq=0), then the device will not delete the channels and continue using the default frequency for those channels.

The problem may be at line 3697 in the `LoraMACCHANNELADD(channel, param*)` fonction: if the frequency = 0 it enters `else { frequencyInvalid = true; }`
Instead it should do: 
`if params.Frequency = 0, then LoRaMACCHANNELREMOVE.`

**Comment by mluis1** [comment]
Thanks for the report.

We will try to furnish a solution as soon as possible.
