### ISSUE TITLE
JoinRequest data rate?

### ISSUE THREAD

**Issue by SYSTOIT** [Lora-net/LoRaMac-node#158]
Hi everyone, 

My sensor node always is run with **SF7 data rate** in JoinRequest and JoinAccept message. How could be possible to change it to **SF12 data rate** for JoinRequest and JoinAccept message?
let me know,please.
Thanks in advance

**Comment by ckt1010** [comment]
Hi, they it data rate as pseudo random. you can check function AlternateDatarate in LoRaMac.c
