### ISSUE TITLE
Maximum payload length setting problem at 433Mhz

### ISSUE THREAD

**Issue by ckt1010** [Lora-net/LoRaMac-node#159]
Hi,
Thanks to co-work with @adonislixi on issue #151, we found there is a setting problem in funtion RxWindowSetup:
Radio.SetMaxPayloadLength( modem, MaxPayloadOfDatarate[datarate] + LORA_MAC_FRMPAYLOAD_OVERHEAD );

As we use 433Mhz, so MaxPayloadOfDatarate with DR_5 will choice 250, and LORA_MAC_FRMPAYLOAD_OVERHEAD is 13. Then  maxpayloadlength will set as 263. But this function declare as below:
void ( *SetMaxPayloadLength )( RadioModems_t modem, uint8_t max );

This is why DR_5 packet can't receive but DR_0 can. And I notice 915Mhz and 868Mhz is use 242, do you think we should change it to 242 also? 
Thanks!

**Comment by mluis1** [comment]
Thanks for the report. The issue comes from the specification itself. We took the values written in the document.

You are right we should change the value to 242.

For now I think that you can use the same table as for EU868.

I will ask the LoRa-Alliance technical committee to correct the maximum payload tables.

**Comment by ckt1010** [comment]
Thanks @mluis1 . I check specification, still have a question can't understand:
![image](https://cloud.githubusercontent.com/assets/1911313/20516353/23daf97a-b0d1-11e6-9fd4-5967285a55ab.png)
![image](https://cloud.githubusercontent.com/assets/1911313/20516372/3bac25b0-b0d1-11e6-8516-75a842b7f6d8.png)
The second one is EU433 maximum payload size.
Seems you use 'N' at EU902-928 but use 'M' at EU433. Since it already plus LORA_MAC_FRMPAYLOAD_OVERHEAD, shouldn't we use 'N' is more suitable?
Thanks!

**Comment by mluis1** [comment]
Yes, you are right. We should use N column instead.

We will provide a fix as soon as possible.

**Comment by ckt1010** [comment]
Thanks! Don't forget CN779-787, it also use 'M'.

**Comment by mluis1** [comment]
Yes, we will review all tables for all bands. 

Thanks again for the provide input. The most tested bands are EU868 and US915 as they have LoRa-Alliance certification test already in place.

**Comment by djaeckle** [comment]
Hi ckt1010,

we have updated the develop branch with the fixes.
