### ISSUE TITLE
TimerGetElapsedTime(0) always return 0

### ISSUE THREAD

**Issue by now9434** [Lora-net/LoRaMac-node#161]
Hi,
I see in LoRaMac.c (line 2704) that we use TimerGetElapsedTime(0) to know how long the device is on.
But when we look the implementation of RtcComputeElapsedTime (which is the return value of TimerGetElapsedTime), we see that RtcComputeElapsedTime(0) always return 0.
So RetransmissionDutyCylce always return BACKOFF_DC_1_HOUR.

Am I right?

Thanks in advance.

**Comment by mluis1** [comment]
Thanks for the report. We will try to provide a fix as soon as possible.
