### ISSUE TITLE
RX information in McpsConfirm callback

### ISSUE THREAD

**Issue by sdugua** [Lora-net/LoRaMac-node#162]
Hello, I would like to recover the information of RSSI, SNR, RxSlot, etc on reception of an acknowledgment.
The McpsConfirm callback only takes in parameter the McpsConfirm structure that do not include these information (only in sMcpsIndication structure). Do you see a way to recover sMcpsIndication data in McpsConfirm callback or is it something missing today in the implementation ? Thank you !

**Comment by mluis1** [comment]
Each time a downlink takes place the McpsIndication callback is called by the MAC layer.

In case of confirmed messages the McpsIndication is called and then the McpsConfirm callback is called.

The application examples for MoteII platform on develop branch shows how to handle the McpsIndication.

**Comment by sdugua** [comment]
Hi Miguel, thanks a lot and sorry because it was my mistake !
