### ISSUE TITLE
Class C downlink issue.

### ISSUE THREAD

**Issue by batulzii** [Lora-net/LoRaMac-node#166]
Using sx1276 lib for modified LoraMote. uplink is ok. downlink is good if haven't uplink before. Any uplink will stop get downlink any more.  For Class C mode.

**Comment by batulzii** [comment]
A quick fix would be to comment out Radio.Standby(); in the OnRxWindow1TimerEvent

if (LoRaMacDeviceClass == CLASS_C) {
//Radio.Standby();
}

But need to check why put radio to standby before Window2?

**Comment by Pupil2013** [comment]
we can see that in the function:it stops the RXtimeroutTimer,that's right according to the specification continuous listening no rxtimeout.it will set the radio in receieve mode later in function RxWindowSetup();
void SX1276SetStby( void )
{
    TimerStop( &RxTimeoutTimer );
    TimerStop( &TxTimeoutTimer );

    SX1276SetOpMode( RF_OPMODE_STANDBY );
    SX1276.Settings.State = RF_IDLE;
}

**Comment by Pupil2013** [comment]
Before we change the chip's mode ,we need to set it to standby mode.
That's why we need to put radio to standby before Window2;

**Comment by batulzii** [comment]
RxWindowSetup( Channels[Channel].Frequency, datarate, bandwidth, symbTimeout, false );
makes rxmode for A /B only. seems to be add case for class C with 
    RxWindowSetup( Channels[Channel].Frequency, datarate, bandwidth, symbTimeout, true);
?

**Comment by Pupil2013** [comment]
makes rxmode for A /B only. ---------that's not true.It's the same for CLASS C

**Comment by batulzii** [comment]
only works when comment in the OnRxWindow1TimerEvent

if (LoRaMacDeviceClass == CLASS_C) {
//Radio.Standby();
}
 otherwise uplink could not received. (Class C). Is It the same bug source as JOIN ACK problem

**Comment by Pupil2013** [comment]
It maybe the time issue.The node may open the recieve slot2 in wrong time or there eixts some time error.
"The receive windows should  achieve 5 overlapping symbols with the downlink preamble"
when you comment the standby() function,the node will stay in receive mode.So the receive time error don't exits any more. @batulzii

**Comment by batulzii** [comment]
Thanks for kind support! Please, advice how to debug time issue.

**Comment by Pupil2013** [comment]
`if( ( LoRaMacParams.Rx2Channel.Datarate == DR_3 ) || ( LoRaMacParams.Rx2Channel.Datarate == DR_4 ) )
    { // DR_4, DR_3
        symbTimeout = 8;
    }
    else if( LoRaMacParams.Rx2Channel.Datarate == DR_5 )
    {
        symbTimeout = 10;
    }`
you can try to increase the symbTimeout value. Make the receive slot longer.

**Comment by batulzii** [comment]
I tested with several increase without success. Interesting point that downlink is ok after reset. but nomore downlink, if sent uplink  at least once.

**Comment by mluis1** [comment]
Can we close the issue?
