### ISSUE TITLE
MAC Commands and FRMPayload size

### ISSUE THREAD

**Issue by GRomaniello** [Lora-net/LoRaMac-node#17]
Hello, 

sending large FRM payloads (45 bytes) with class A LoRa devices I see some packet length error.

It happens when LoRa stack includes MAC commands in the FHDR reducing the FRM payload length.

Example: Header 8 bytes + MAC Commands 12 bytes + FRM payload 45 bytes

If I have not misunderstood the code, LoRa stack adds MAC commands even if the MAC payload size exceeds the maximum MAC payload size causing a packet drop. 

How to overcome this issue? I have to consider the maximum FRM payload size of 36 bytes (51 N - 23  FHDR -1 Fport)  to guarantee a packet delivery in the worst case (FHDR of 23 bytes) or there is a solution to send MAC commands in a different way ?

Thanks in advance

Regards

**Comment by mluis1** [comment]
Version 4.0 will have an API to query if it is possible to send the given payload.
If the query reports that there are MAC commands to be sent then you may decide to send an empty frame in order to flush the MAC commands buffer.

```c
/*!
 * \brief   Queries the LoRaMAC if it is possible to send the next frame with
 *          a given payload size. The LoRaMAC takes scheduled MAC commands into
 *          account and reports, when the frame can be send or not.
 *
 * \param   [OUT] txInfo - The structure \ref LoRaMacTxInfo_t contains
 *                         information about the actual maximum payload possible
 *                         ( according to the configured datarate or the next
 *                         datarate according to ADR ), and the maximum frame
 *                         size, taking the scheduled MAC commands into account.
 *
 * \param   [IN] size - Size of applicative payload to be send next
 *
 * \retval  LoRaMacStatus_t Status of the operation. When the parameters are
 *          not valid, the function returns \ref LORAMAC_STATUS_PARAMETER_INVALID.
 *          In case of a length error caused by the applicative payload size, the
 *          function returns LORAMAC_STATUS_LENGTH_ERROR. In case of a length error
 *          due to additional MAC commands in the queue, the function returns
 *          LORAMAC_STATUS_MAC_CMD_LENGTH_ERROR. In case the query is valid, and
 *          the LoRaMAC is able to send the frame, the function returns LORAMAC_STATUS_OK. *
 */
LoRaMacStatus_t LoRaMacQueryTxPossible( LoRaMacTxInfo_t* txInfo, uint8_t size );
```
