### ISSUE TITLE
ADR: retrieve connectivity 

### ISSUE THREAD

**Issue by mbracq** [Lora-net/LoRaMac-node#174]
Hi all,

When ADR is enable, we have to receive a ack form network every (ADR_ACK_LIMIT+ADR_ACK_DELAY) uplink. If not, the node has to lower its datarate in order to retrieve connectivity (§4.3.1.1 of lorawan specification of lorawan v1.0.2).  It's right implemented in this stack. 

But the specification doesn't talk about power. 

Per example, if the network set DR7, Power5  (2 dBm) and then the connection is lost, the device will return to DR0 but will stay in Power5. Can we also increase power in this case?

I suggest that

```C
if( AdrAckCounter >= ( ADR_ACK_LIMIT + ADR_ACK_DELAY ) )
{
    if( ( AdrAckCounter % ADR_ACK_DELAY ) == 0 )
    {
   #if defined( USE_BAND_433 ) || defined( USE_BAND_780 ) || defined( USE_BAND_868 )
       if( datarate > LORAMAC_TX_MIN_DATARATE )
       {
         datarate--;
       }
```

will become

```C
if( AdrAckCounter >= ( ADR_ACK_LIMIT + ADR_ACK_DELAY ) )
            {
                if( ( AdrAckCounter % ADR_ACK_DELAY ) == 0 )
                {          
                    if( LoRaMacParams.ChannelsTxPower > LORAMAC_MAX_TX_POWER )
                    {
                        LoRaMacParams.ChannelsTxPower--;
                    }
#if defined( USE_BAND_433 ) || defined( USE_BAND_780 ) || defined( USE_BAND_868 )
                    if( datarate > LORAMAC_TX_MIN_DATARATE )
                    {
                        datarate--;
                    }
```

Thanks in advance for your reply,
++Manuel

**Comment by djaeckle** [comment]
Hi mbracq,

thanks for your request. We improved the function according to the feedback from the LoRa-Alliance.
