### ISSUE TITLE
Issue in ValidatePayloadLength().

### ISSUE THREAD

**Issue by now9434** [Lora-net/LoRaMac-node#177]
Hi,

I think there is an useless code in ValidatePayloadLength(), line 1967.
For me, maxN is always less than LORAMAC_PHY_MAXPAYLOAD.
So 
`if( ( payloadSize <= maxN ) && ( payloadSize <= LORAMAC_PHY_MAXPAYLOAD ) )`
could be : 
`if ( payloadSize <= maxN )`

Sincerely yours.

**Comment by djaeckle** [comment]
Hi now9434,

thanks for your report. We think that the additional check is useful. Otherwise, if the value of `LORAMAC_PHY_MAXPAYLOAD` changes, there could be a mismatch when the MAC sends a frame.

**Comment by now9434** [comment]
Thanks.
