### ISSUE TITLE
RTC calibration issue

### ISSUE THREAD

**Issue by BBoulet** [Lora-net/LoRaMac-node#182]
Hello,

I would like to know what is the purpose of CalibrateSystemWakeupTime() function called in BoardInitMcu. Sometimes (~10% chances) my system remains asleep and never wakes up, this is quite problematic.
Does anybody experienced this ?

**Comment by GregCris** [comment]
The function CalibrateSystemWakeupTime() is used to measure the time taken by the MCU to wake-up form stop mode and re-initialise the various peripherals (SPI, I2C, ...). The time varies from one HW to another due to the MCU Xtal (if used), the core clock speed, ....

**Comment by mluis1** [comment]
Can we close this issue?

**Comment by dmeehan1968** [comment]
I appreciate that this is an old issue, but the RtcSetMcuWakeUpTime implementation for STM32L0xx doesn't appear to work.  When this function is called 1 second after MCU initialisation is complete, the function fails to do the computation as `HAL_NVIC_GetPendingIRQ( RTC_IRQn ) == 1` is not true.  As a result, the global `McuWakeUpTimeCal` is left at 0.

The additional startup delay (1 sec) is redundant and unhelpful.

Also, the sample apps always set USB power connected, which effectively disabled low power modes, so this code gets skipped.  My use case is battery power, and so the startup delay is unhelpful.

**Comment by altishchenko** [comment]
@dmeehan1968 Hello Dave, leaving this value at 0 doesn't break anything in my devices running on L051 with LiPo's and using deepsleep extensively. I actually dropped this logic from my firmware some good time ago to save on space and remove unneeded complexity.

**Comment by mluis1** [comment]
While discussing with ST sometime ago they also said that they removed this logic from their port.

We will provide an update removing this logic as soon as possible.

I have created a new issue in order to not forget to this update.
