### ISSUE TITLE
question regarding release dates. 

### ISSUE THREAD

**Issue by e123h** [Lora-net/LoRaMac-node#189]
Can you please tell me when we can expect the 4.4 release of the LoRa stack? 
The roadmap says the end of last month. (The date shifted a couple of times)

Thanks in advance.

**Comment by mluis1** [comment]
The 4.4 development version will be available on the develop branch once we do the 4.3.1 release.

The 4.3.1 release is currently being under certification test validation. 
The release should happen (we hope) at latest end of next week, if everything goes well.

**Comment by mluis1** [comment]
We shifted the release to Monday 27th February 2017 due to the latest corrections done on develop branch.

**Comment by e123h** [comment]
Thanks for the update, much appreciated

**Comment by mluis1** [comment]
Release 4.3.1 done.
