### ISSUE TITLE
China 779-787MHz ISM Band

### ISSUE THREAD

**Issue by robxr** [Lora-net/LoRaMac-node#19]
Hello,

I would like to know if the stack is working with the China779-787MHz ISM Band.  
I have modified  the frequency definitions defined in "LoRaMac-board.h", and it can also communicate with gateway and server, which work at the same band. 
Furthermore, There is some code with "CLASS C", is the Class C fully implemented in the code?. I have debugged Class C mode(sensor node), and it seems doesn't work well.  Only one packet has been sent to gateway(and forwarded to server) when power on, and downlink data can't been passed to application by callback functions. it seems link the MAC schedule doesn't work well.

Thanks a lot.
Haibo Luo (NPLink)

**Comment by hongkongkiwi** [comment]
Hi, is this working okay now?
