### ISSUE TITLE
How to set the 470MHz band

### ISSUE THREAD

**Issue by zhoubx123** [Lora-net/LoRaMac-node#191]
I set the 470MHz from 433MHz，and just change #define LC1 433175000 to 471300000;#define LC2 433375000 to 471500000;#define LC1 433575000 to 471700000;
it works，However, after the ADR is  on, the SF7 and SF8 are unable to receive the gateway Ack.
Where do I need to set?

**Comment by djaeckle** [comment]
Hi zhoubx123,

you can configure the stack to use the CN470 band if you define the symbol `USE_BAND_470`. You need to define it in the preprocessor options of your environment.

**Comment by zhoubx123** [comment]
I have not define USE_BAND_470，and just USE_BAND_433,
at SF12 to SF9, module can receive gateway Ack, but SF8 and SF7 can not;
and gateway can receive date from module.
so I do not know some where must be set?

**Comment by djaeckle** [comment]
Do you want to use the EU433 or the CN470 band?

**Comment by zhoubx123** [comment]
no, i just use CN470 band.

**Comment by zhoubx123** [comment]
I would like to use the 433MHz definition, but running in 470MHz, modify the following（LoRaMac-definitions.h）:
/*!
 * LoRaMac default channels
 */
// Channel = { Frequency [Hz], { ( ( DrMax << 4 ) | DrMin ) }, Band }
//#define LC1                { 433175000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
//#define LC2                { 433375000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
//#define LC3                { 433575000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC1                { 471300000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC2                { 471500000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC3                { 471700000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC4                { 471900000, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
Do I need to set any place?

**Comment by djaeckle** [comment]
Hi zhoubx123,

have you also updated the RX2 window definition ( `RX_WND_2_CHANNEL` )?

Please note that your implementation will not be compliant to the LoRaWAN Specification as this regional definition is not specified.

**Comment by zhoubx123** [comment]
yes, I have:
/*!
 * Second reception window channel definition.
 */
// Channel = { Frequency [Hz], Datarate }
#define RX_WND_2_CHANNEL                                  { 478500000, DR_0 }
I just want to test, so  have not define CN470 band.
it can work, but SF7 and SF8, module can not receive gateway ACK.

**Comment by djaeckle** [comment]
Hi zhoubx123,

those adaptations are everything you need. Unfortunately, we cannot provide more support on your issue, as your regional definition is not compliant nor specified in the LoRaWAN Specification.
