### ISSUE TITLE
UpLink counter initial value should be 0

### ISSUE THREAD

**Issue by abouillot** [Lora-net/LoRaMac-node#195]
In LoRaWAN specs (1.0.2), the frame counter is supposed to be reset to 0 on start of ABP session. In the code the initial value was 1.

> 4.3.1.5 Frame counter (FCnt)
> 
> <...> After a JoinReq – JoinAccept message exchange or a reset for a personalized end-device, the frame counters on the end-device and the frame counters on the network server for that end-device are reset to 0. <...>

I've prepared a pull request for this.

**Comment by mluis1** [comment]
Pull request #193 merged.
