### ISSUE TITLE
Channel mask not working in OTAA, working in ABP

### ISSUE THREAD

**Issue by LaurentHB** [Lora-net/LoRaMac-node#202]
Hello,

I have a little problem regarding the channel mask I'm using when using OTAA compared to ABP.

I am using a multitech conduit gateway in NA so I have to use a frequency sub-band that has 8 channels.

When using ABP, I added these lines to my main and it worked fine. 

static uint16_t multitechGatewayChannelsMask[6] = { 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00};

// In the DEVICE_STATE_INIT case of the main loop
mibReq.Type = MIB_CHANNELS_MASK;
mibReq.Param.ChannelsMask = multitechGatewayChannelsMask;
LoRaMacMibSetRequestConfirm( &mibReq );

When I switched to OTAA I saw I was missing a lot of packets and that if I switched the sub-band on the gateway the same thing would happen without touching the mask. So my mask doesn't seem to be working at all.

Thanks for the help!

Laurent

**Comment by LaurentHB** [comment]
Turns out I missed that the parameters were reset during the join procedure, I'm not entirely sure why but I just commented the lines that were related to the channelmasks and everything seems to be working fine.

**Comment by mluis1** [comment]
Just to inform you that we have added a new parameter to the mac layer in order to handle this situation.

To initialize the default channels mask you need now to also modify the `MIB_CHANNELS_DEFAULT_MASK` parameter as shown below:
```C
static uint16_t multitechGatewayChannelsMask[6] = { 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00};

    mibReq.Type = MIB_CHANNELS_DEFAULT_MASK;
    mibReq.Param.ChannelsDefaultMask = multitechGatewayChannelsMask;
    LoRaMacMibSetRequestConfirm( &mibReq );

    mibReq.Type = MIB_CHANNELS_MASK;
    mibReq.Param.ChannelsMask = multitechGatewayChannelsMask;
    LoRaMacMibSetRequestConfirm( &mibReq );
```

**Comment by LaurentHB** [comment]
Thanks @mluis1 , I will get to updating to that version of the mac layer soon.

Do you think what I've done will cause any problems in the mean time?

**Comment by mluis1** [comment]
If you are sure that the network server doesn't change the channel mask then I think your temporary fix should be OK.

Please note that I think that you should also enable the 500 kHz channel corresponding to the enabled channels.
The Join procedure alternates between DR0 and DR4 each time a JoinReq is issued. Thus your channel mask should be:
```C
static uint16_t multitechGatewayChannelsMask[6] = { 0x00FF, 0x0000, 0x0000, 0x0000, 0x0001, 0x0000};
```

**Comment by LaurentHB** [comment]
I don't seem to ever be missing packets doing that and I'm doing everything on the gateway directly using node-red so I don't think it could be happening without me knowing. 

I'll make sure to add the channel too, I never thought about that. Thanks a lot!
