### ISSUE TITLE
Building LoRaMac apps without any IDEs

### ISSUE THREAD

**Issue by kqorany** [Lora-net/LoRaMac-node#203]
Hi Folks,

I am looking for building the apps without any IDEs just using the GCC ARM toolchain. So, I would like to ask if there is anybody did that before. If yes, please share with me how you did that.

Thanks in advance,
Khaled

**Comment by mluis1** [comment]
We have on our task list a task to put in place a CMAKE based system. For the moment this is very low priority for us.

Sometime ago someone proposed a pull-request with makefiles usage. You can take a look at pull-request #124.
