### ISSUE TITLE
Is RxChainCalibration and setting default register values required for LoRa mode as well

### ISSUE THREAD

**Issue by mazimkhan** [Lora-net/LoRaMac-node#207]
The registers used in RxChainCalibration and default values belong to FSK mode. Are these operations required in LoRa Mode as well?
It's a question.

**Comment by mluis1** [comment]
Yes, the RxChainCalibration is necessary for both FSK and LoRa modes.

Please read SX1276 datasheet chapter "4.2.3.8 Image and RSSI Calibration"

> *4.2.3.8. Image and RSSI Calibration*
An automatic calibration process is used to calibrate the phase and gain of both I and Q receive paths. This calibration allows enhanced image frequency rejection and improves the RSSI precision. This calibration process is launched under the following circumstances:
>* Automatically at Power On Reset or after a Manual Reset of the chip (refer to section 7.2). For applications where the temperature remains stable, or if the Image Rejection is not a major concern, this single calibration will suffice.
>* Automatically when a pre-defined temperature change is observed.
>* Upon User request, by setting bit ImageCalStart in RegImageCal, when the device is in Standby mode. Note that in LoRaTM mode the calibration command is inaccessible. To perform the calibration, the radio must be returned temporarily to FSK/OOK mode for the calibration process.
>
>A selectable temperature change, set with TempThreshold (5, 10, 15 or 20°C), is detected and reported in TempChange, if the temperature monitoring is turned On with TempMonitorOff=0.
>
>This interrupt flag can be used by the application to launch a new image calibration at a convenient time if AutoImageCalOn=0, or immediately when this temperature variation is detected, if AutoImageCalOn=1.
>
>The calibration process takes approximately 10ms.
