### ISSUE TITLE
Can't clear LORAMAC_TX_RUNNING state after A UNCONFIRMED McpsRequest

### ISSUE THREAD

**Issue by twowinter** [Lora-net/LoRaMac-node#210]
LORAMAC_TX_RUNNING state should only be cleared by OnMacStateCheckTimerEvent with (LoRaMacFlags.Bits.MacDone == 1 );

And the MacDone can only be set by these Radio CallBack.

I am confused which CallBack can set MacDone  after A UNCONFIRMED McpsRequest.
 
![macdone1](https://cloud.githubusercontent.com/assets/5105538/24069062/b91e60fe-0bd9-11e7-9aeb-07b30ea74177.png)

**Comment by twowinter** [comment]
### Is the MacDone flag setted by OnRxTimeout instead of OnTxDone

the RX2 is not start cause the default Receive window duration 3000ms, the RX2 RXtimeoutEvent can't be trigged.

After I modified the MAX_RX_WINDOW from 3000ms to 800ms, the RX2 go well, after RX2's OnRadioRxTimeout(), LORAMAC_TX_RUNNING state was cleared by OnMacStateCheckTimerEvent

#define MAX_RX_WINDOW                               800 // 3000

![image](https://cloud.githubusercontent.com/assets/5105538/24070424/41c88c22-0bf8-11e7-8797-54d72ae5b7a7.png)

--------

Is LORAMAC_TX_RUNNING state should be cleared by RX2 RXtimeoutEvent? If yes, Is it need to change MAX_RX_WINDOW to avoid problem like me?

**Comment by twowinter** [comment]
I tested a LoRaWAN BaseStation from CLAA(China Lora Application Alliance).
the RX1_WINDOW is should more than 1000ms, Is this a problem for  Gateway?

I should use RX1_WINDOW 3000ms in order to recvieve messages from gateway, and give up the RX2, it can't started.
------------
But this would cause my problem"Can't clear LORAMAC_TX_RUNNING state after A UNCONFIRMED McpsRequest", if the gateway didn,t answer to the end-device, it cann't send McpsRequest again.

**Comment by mluis1** [comment]
I guess that you are misunderstanding how all this works.

The MAX_RX_WINDOW timeout should never happen in the reality. It is there just in case there is really something very wrong happening.

What defines the Rx windows timeouts is the `symbTimeout ` when the `Radio.SetRxConfig` function is called.

Once the `symbTimeout ` is set in the radio hardware and the radio is put in RxSingle mode. Then the Radio will automatically timeout after the number of specified `symbTimeout ` value.

In case the radio detects a preamble it is kept in reception mode up until the frame is fully received.

Please note that we made a commit to the develop branch that now computes the RxWindows parameters automatically.

**Comment by twowinter** [comment]
thank you, maybe i found the reason.

My hardware didnot use DIO, i can only use REG_LR_IRQFLAGSMASK to judge RXDone/RXTimeout.

And the SX1276SetRx didnot set REG_LR_IRQFLAGSMASK with  RXDone/RXTimeout. So "very wrong happening".

**Comment by eric780711** [comment]
Hi twowinter
I have the same problem, you have successfully solved it, the downlink problem?
