### ISSUE TITLE
Region calculate max payload size needs to take into account dwell time

### ISSUE THREAD

**Issue by calebbramwell** [Lora-net/LoRaMac-node#221]
We have been testing AS923 on feature/4.4.0 branch and have encountered an issue with max payload size calculation. AS923 can be used with or without a 400ms Max dwell time limitation set in LoRaMacParams.UplinkDwellTime and LoRaMacParams.DownlinkDwellTime. 
The UplinkDwellTime parameter needs to be set in the getPhy structure and passed to the RegionGetPhyParam function for the AS923 region to correctly calculate the max allowed payload.

LoRaMac.c  : LoRaMacQueryTxPossible, ValidatePayloadLength
```
    // Setup PHY request
    getPhy.UplinkDwellTime = LoRaMacParams.UplinkDwellTime;  // new
    getPhy.Datarate = datarate;
    getPhy.Attribute = PHY_MAX_PAYLOAD;

    // Change request in case repeater is supported
    if( RepeaterSupport == true )
    {
        getPhy.Attribute = PHY_MAX_PAYLOAD_REPEATER;
    }
    RegionGetPhyParam( LoRaMacRegion, &getPhy );
    txInfo->CurrentPayloadSize = getPhy.Param.Value;
```

**Comment by djaeckle** [comment]
Hi calebbramwell,

thanks for the report. Your statement is correct. I will provide an update.
