### ISSUE TITLE
different crystal use 

### ISSUE THREAD

**Issue by batulzii** [Lora-net/LoRaMac-node#228]
please, advice to port if i use different crystal in Mote. We have design based Loramote but with different crystal frequency.

**Comment by djaeckle** [comment]
Hi batulzii,

could you please provide some more information? Which crystal do you want to change?

**Comment by batulzii** [comment]
we use 147456Mhz crystal for stm32L1516.  Where in which file (HAL) need to changes to keep right timing.

**Comment by djaeckle** [comment]
Do you mean the STM32L151R6? If not please provide the related datasheet.

**Comment by batulzii** [comment]
Oh, sorry for short part number. it is a STM32L151CBT6

**Comment by djaeckle** [comment]
Table 29. denotes that a maximum frequency of 24MHz is supported for the HSE. Or do I look in the wrong datasheet? Please provide the link to the datasheet to avoid missunderstandings.

**Comment by batulzii** [comment]
ok. 14Mhz is fine for stm32L151CB . question is where and in which file need to edit .
i had made changes as bellow:

#if !defined  (HSE_VALUE) 
  #define HSE_VALUE    ((uint32_t)8000000)

 changed to

#if !defined  (HSE_VALUE) 
  #define HSE_VALUE    ((uint32_t)14745600)

**Comment by djaeckle** [comment]
Hi batulzii,

the definitions of the clock frequencies are defined in file `stm32l1xx_hal_config.h`. You have to change the define for `HSE_VALUE`. You could either define `HSE_VALUE` in your preprocessor options or edit it in the file directly.

**Comment by batulzii** [comment]
thank you!
