### ISSUE TITLE
USE_BAND_915_HYBRID meaning

### ISSUE THREAD

**Issue by FoujanetG** [Lora-net/LoRaMac-node#23]
Hi,

What is the meaning of USE_BAND_915_HYBRID in LoraWan stack (V3.4) ?

Thank you,

Guillaume F.

**Comment by mluis1** [comment]
The USE_BAND_915_HYBRID is an interim method for supporting gateways that do not provide the implement the full 64+8 channels defined for North America operation. In LoRaWAN 1.1 this method will no longer be needed and the device will be provided a complete list of channels available upon joining the network. There are also regulatory restriction that affect the output power allowed when a device must use less than 50 channels in the USA. Please see FCC part 15.247 for details.
