### ISSUE TITLE
Bands[Channels[channel].Band].TimeOff is not reset.

### ISSUE THREAD

**Issue by anthonyblx** [Lora-net/LoRaMac-node#232]
Hi,

I am using the stack for dev. I use the region AU915. 
I have realised that the Bands[Channels[channel].Band].TimeOff is not reset to 0. 
I think when calling ScheduleTx(), CalculateBackOff(lastTxChannel); should be called. So that it will reset the Bands[Channels[channel].Band].TimeOff when the node has joined the network.

Regards,
Anthony

**Comment by djaeckle** [comment]
Hi Anthony,

thanks for the report. I will check it and come back to you soon.

**Comment by djaeckle** [comment]
Hi Anthony,

I have updated the develop branch. Please take a look at 54b814b.
