### ISSUE TITLE
LoRaMac.c's AggregatedTimeOff is never reset

### ISSUE THREAD

**Issue by jamesl-dm** [Lora-net/LoRaMac-node#234]
I haven't tested this personally, but it looks like AggregatedTimeOff is never reset (in the development branch). So if a gateway sets the node duty cycle, AggregatedTimeOff will increase with every transmission, causing larger and larger delays. 

Originally, it was reset to zero during the channel selection procedure, once the LastAggrTx time got large enough for a transmission. But it looks like this code got dropped when the channel selection code was factored out of LoRaMac.c.

**Comment by djaeckle** [comment]
Hi jamesl-dm,

thanks for the report. I will check it.

**Comment by djaeckle** [comment]
Hi jamesl-dm,

I have updated the develop branch. Please take a look at 59a21a5e.

**Comment by jamesl-dm** [comment]
Thanks @djaeckle, looks like that'll do it
