### ISSUE TITLE
rtc reading problem

### ISSUE THREAD

**Issue by batulzii** [Lora-net/LoRaMac-node#236]
now=RtcGetCalendar();
:
:		
s[2]=now.CalendarTime.Hours;										s[3]=now.CalendarTime.Minutes;
s[4]=now.CalendarTime.TimeFormat;
s[5]=now.CalendarDate.Date;										
s[6]=now.CalendarDate.Month;

getting random numbers not time&date

**Comment by temporaryaccount** [comment]
Have you actually set the date and time before trying to read it?

**Comment by batulzii** [comment]
Yes. RtcInit() do set defualts.

**Comment by batulzii** [comment]
first read seems to be correct

**Comment by batulzii** [comment]
i made small example for this board. reading is ok.

**Comment by batulzii** [comment]
but loramac could not

**Comment by batulzii** [comment]
Found reason. LoraMAC uses RTC for higher speed timing, so could not use normal calendar
