### ISSUE TITLE
20 Channel restriction no longer required in RegionAU915.c

### ISSUE THREAD

**Issue by jamesl-dm** [Lora-net/LoRaMac-node#237]
At [RegionAU915.c#L381](https://github.com/Lora-net/LoRaMac-node/blob/6e01e908e76722bb77772fb1466a685771749181/src/mac/region/RegionAU915.c#L381), channel mask sets with fewer than 20 channels are rejected on grounds of non-compliance with ACMA regulations.

The ACMA regulations were amended on the 4th of May 2016, removing the requirement for 'Digital modulation transmitters' to be wideband. Before, they were required to have 500 kHz 6 dB bandwidth. They are now only required to radiate no more than 25 mW per 3 kHz, which is more than enough for 125 kHz LoRa modulation. So the full 915-928 band can now be used under the 'Digital modulation transmitters' class instead of the 'Frequency hopping transmitters' class. During industry consultation, one of the arguments motivating this amendment was the inability of 8 channel LoRa gateways to hop on 20 channels.
See item 4 of [F2016L00636 Explanatory Statement](https://www.legislation.gov.au/Details/F2016L00636/Explanatory%20Statement/Text) for a description of the amendment, [NNNCoSubmission.pdf](http://www.acma.gov.au/~/media/Spectrum%20Engineering/Issue%20for%20comment/IFC%2032%202015/3%20NNNCoSubmission%20pdf.pdf) for some rationale.

Although LoRaWAN regional parameters document hasn't caught up with the legislation change yet, it would probably be best to disable the 20 channel restriction in RegionAU915.c. I believe it isn't being applied to MAC commands sent from the gateway in any case.

**Comment by mluis1** [comment]
Solved with commit dc87d5e60856d8a473ac22dcd71650c605876c41
