### ISSUE TITLE
Class C and downlink confirmed

### ISSUE THREAD

**Issue by FoujanetG** [Lora-net/LoRaMac-node#24]
If I well understand, when the stack receives a FRAME_TYPE_DATA_CONFIRMED_DOWN, the stack confirmes the frame. 

But if the latence is too big, or if there is a network problem with the acknowledge, the network server retries the FRAME_TYPE_DATA_CONFIRMED_DOWN. 

At each reception, the stack calls the callback "OnMacEvent". So if the network server tries 3 times to send the FRAME_TYPE_DATA_CONFIRMED_DOWN, the applicative part  receives 3 times the donwlink frame, with same data.

The stack can filter the FRAME_TYPE_DATA_CONFIRMED_DOWN, with the "DownLinkCounter".

Is it in the backlog for a next release?

Thank you very much,

GF.

**Comment by mluis1** [comment]
Will be solved on version 4.0
