### ISSUE TITLE
Error compiling and erasing flash

### ISSUE THREAD

**Issue by julienhans** [Lora-net/LoRaMac-node#242]
Error during the Build process of the LoRaMacClassC with CoIDE :
       [cc] c:/program files (x86)/gnu tools arm embedded/6 2017-q1-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld.exe: LoRaMacClassC.elf section `.text' will not fit in region `FLASH'
       [cc] c:/program files (x86)/gnu tools arm embedded/6 2017-q1-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld.exe: region `FLASH' overflowed by 25800 bytes

Error when trying to erase the Flash with CoIDE :
C:\CooCox\CoIDE_V2Beta>"C:/CooCox/CoIDE_V2Beta/bin\coflash.exe" erase STM32L051C8T6 --adapter-name=ST-Link --port=SWD --adapter-clk=1000000 --driver="C:/Users/julie/AppData/Roaming/CooCox/CoIDE/config/flash/STM32L0xx_64.elf;"  
Error: Failed to open flash driver file

Any idea ?

Thanks

Julien

**Comment by temporaryaccount** [comment]
Your microcontroller's flash size is too small and the compiled binary doesn't fit. Try to use the Release mode instead of Debug mode to vastly decrease the binary size, also change the Release mode's optimization level to size optimization (-Os) instead of speed optimization.
