### ISSUE TITLE
2mA consumption in stopmode

### ISSUE THREAD

**Issue by djnoc** [Lora-net/LoRaMac-node#245]
Hi,

I don't know why but my sx1272 never stops so when my µ sleeps my node consume almost 2mA.
I use the 4.1.0 version

Djnoc

**Comment by djnoc** [comment]
Ok i found a problem, now in stop mode i have 15µa
I can't do better.

Any idea?

**Comment by x893** [comment]
Disconnect (and possible disable) debugger
