### ISSUE TITLE
TimerTime_t   uint32_t/uint64_t?

### ISSUE THREAD

**Issue by hinaultd** [Lora-net/LoRaMac-node#247]
Hi, I  had the bad surprise found that my programs stops after 49.7 days. I think that the problem comes from the function "RtcConvertCalendarTickToTimerTime" that overflows when TimerTime_t is of type "uint32_t". " Did you had the problem?

**Comment by temporaryaccount** [comment]
See issue #218 and [this](https://github.com/Lora-net/LoRaMac-node/pull/243) pull request.
