### ISSUE TITLE
Receiving using Ettus N210

### ISSUE THREAD

**Issue by 97aditi** [Lora-net/LoRaMac-node#252]
HI! I am using Ettus USRP N210 to receive packets and SX1276 over STM32L152 as the LoRa node(using LoRaWAN demo 76 project). It seems he USRP is able to capture only a part of the preamble and not the entire LoRa packet. 
Here's a screenshot of what the USRP captures.

![image](https://user-images.githubusercontent.com/29413037/27155024-d28aee30-511c-11e7-8842-c79f61a7b4cf.png)

**Comment by mluis1** [comment]
The LoRa modulation specification is not publically available. 
The issue that you are encountering is related to your USRP N210 device. If you need support on this I would recommend that you contact the device manufacturer directly.
