### ISSUE TITLE
Mobile Device OTAA Timing

### ISSUE THREAD

**Issue by kungccm** [Lora-net/LoRaMac-node#271]
Hi Sir, 
I have a question about the mobile device OTAA timing.
The scenario is as blow.
1. Device Power on and Join to the LoRa Network by OTAA
2. The Device moves to another LoRa Network. However it doesn't know he is out of service. 
I have two solutions
  a. Device always sends the confirmed uplink. Once it doesn't get the confirmed ACK, it will send OTAA request to join the New network.
 b. Device always send the check_link MAC command before it sends the uplink.  Once it doesn't get the response form AP, it will send OTAA request to join the New network.

However these two solutions will impact to the LoRa Network Capacity. Because AP 1301 module is half-duplex.

Is there anyone has better idea to my question?
Please advise. Thanks a lot.

**Comment by mluis1** [comment]
This is a general question not really related to this project. I would advise you to ask this question on [LoRa Community](https://semtech.force.com/lora) portal.
