### ISSUE TITLE
The reply for the DevStatusReq MAC command is using the incorrect snr value

### ISSUE THREAD

**Issue by judedcruz** [Lora-net/LoRaMac-node#275]
Reference: 
- git develop branch
- LoraWAN Spec 1.0.1 and 1.0.2

The response to a DevStatusReq MAC command should contain the SNR value of the previously received packet casted to a 6-bit signed value. The SNR value originates from the SX1276 register:REG_LR_PKTSNRVALUE.

Problem: The current code is using the SX register value without casting it into a 6-bit signed value, which is inconsistent with our interpretation of DevStatusAns.

Code references: 

1.  We grab the value in LoRaMac-node/src/radio/sx1276/sx1276.c line:1520:
`
SX1276.Settings.LoRaPacketHandler.SnrValue = SX1276Read( REG_LR_PKTSNRVALUE );
`

2. We do Invert/shift into an "snr" variable but don't use it to pass downstream.
```
if( SX1276.Settings.LoRaPacketHandler.SnrValue & 0x80 ) // The SNR sign bit is 1
{
        // Invert and divide by 4
        snr = ( ( ~SX1276.Settings.LoRaPacketHandler.SnrValue + 1 ) & 0xFF ) >> 2;
        snr = -snr;
}
else
{
        // Divide by 4
        snr = ( SX1276.Settings.LoRaPacketHandler.SnrValue & 0xFF ) >> 2;
}
```
3. Then we use the register value (instead of the variable: snr) as the parameter to RadioEvents->RxDone()
```
if( ( RadioEvents != NULL ) && ( RadioEvents->RxDone != NULL ) )
{
        RadioEvents->RxDone( RxTxBuffer, SX1276.Settings.LoRaPacketHandler.Size, SX1276.Settings.LoRaPacketHandler.RssiValue, SX1276.Settings.LoRaPacketHandler.SnrValue );
}
```

4. This snr value gets consumed in the the loramac.c file ProcessMacCommands() function:
```
            case SRV_MAC_DEV_STATUS_REQ:
                {
                    uint8_t batteryLevel = BAT_LEVEL_NO_MEASURE;
                    if( ( LoRaMacCallbacks != NULL ) && ( LoRaMacCallbacks->GetBatteryLevel != NULL ) )
                    {
                        batteryLevel = LoRaMacCallbacks->GetBatteryLevel( );
                    }
                    AddMacCommand( MOTE_MAC_DEV_STATUS_ANS, batteryLevel, snr );
                    break;
                }
```

Thank you,
Jude

**Comment by mluis1** [comment]
Please note that we have already answered several times to this question.
Please refer to  issues #143, #104, #75 and #29
