### ISSUE TITLE
Antenna RX/TX switch - reverse values

### ISSUE THREAD

**Issue by victorovich2004** [Lora-net/LoRaMac-node#278]
void SX1272SetAntSw( uint8_t opMode )
{
    switch( opMode )
    {
    case RFLR_OPMODE_TRANSMITTER:
        GpioWrite( &AntRx, **1** );
        GpioWrite( &AntTx, **0** );
        break;
    case RFLR_OPMODE_RECEIVER:
    case RFLR_OPMODE_RECEIVER_SINGLE:
    case RFLR_OPMODE_CAD:
    default:
        GpioWrite( &AntRx, **0** );
        GpioWrite( &AntTx, **1** );
        break;
    }
}

I think, zero and one values should be changed?

**Comment by mluis1** [comment]
The current implementation is correct. The right RF power values are obtained.
But, in order to avoid confusions we will provide a fix that will use the right variable names.
