### ISSUE TITLE
LoRaWAN and SX1280(2.4GHz) support

### ISSUE THREAD

**Issue by Krasutski** [Lora-net/LoRaMac-node#291]
Hello, 
Anybody know about support of 2.4GHz band and support of sx1280? I know this question must be addressed to the LoRa Alliance but I hope, some people here can answer this question.

**Comment by mluis1** [comment]
This is a general question not really related to this project. I would advise you to ask this question on [LoRa Community](https://semtech.force.com/lora) portal or to contact the LoRa Alliance.
