### ISSUE TITLE
Bug in SendFrame() function

### ISSUE THREAD

**Issue by fahad80** [Lora-net/LoRaMac-node#292]
In  LoRaMac-node/src/apps/LoRaMac/classA/SK-iM880A/main.c:
line 281:

```
if( LoRaMacMcpsRequest( &mcpsReq ) == LORAMAC_STATUS_OK )
{
        return false;
}
```
I think it should be '!='

**Comment by djaeckle** [comment]
Hi fahad80,

this is not a bug. The return value of function `SendFrame` is set to false, if the status is `LORAMAC_STATUS_OK`. If it returns true, you could try to send another frame directly, since the application doesn't need to wait for the confirmation of the LoRaWAN stack.

**Comment by fahad80** [comment]
My bad. I must have been sleepy. Thanks for the clarification.
