### ISSUE TITLE
Question about TimerTime_t units

### ISSUE THREAD

**Issue by catsup** [Lora-net/LoRaMac-node#295]
Hello,

looking at timer.h (in branch devel):

```
/*!
 * \brief Timer time variable definition
 */
#ifndef TimerTime_t
typedef uint32_t TimerTime_t;
#endif
```
Is this data type supposed to be in milliseconds ?

Tia,
Marc

**Comment by djaeckle** [comment]
Hi catsup,

yes, it's milliseconds.

**Comment by catsup** [comment]
Thanks for the clarification djaeckle.

Closing the question.
