### ISSUE TITLE
node stop after about 4294360 seconds from boot

### ISSUE THREAD

**Issue by ASCOEL** [Lora-net/LoRaMac-node#307]
Hi All,

In  a sensor based on IM880 module and library rel 4.3.2 after about 4294360 seconds about 50pcs under stress test in field they are stop.
This value is showed on serial shell available on the sensor, and only the timer is stuck; the shell and other activity not timer-dependent still running fine.
Because the internal timer is express in mS, the value 4294360 is very near to 0xFFFFFFFF mS (4294967296 decimal).
My application reload every 20 seconds the timer for wake-up the processor and perform some activity, at end of activities the processor return in sleep mode awaiting the new timer interrupt within 20 seconds.
After 4294360 seconds the timer is not able to generte a new interrupt and the node remain in sleep mode.
This issue is very strange and is causing of a lot of problems.
Do you have an idea because this happen?
With the library release 3.x.x and the timer expressed in uS this problem was never happened.
thanks and regards
Jerry

**Comment by temporaryaccount** [comment]
Duplicate, see #218.

**Comment by ASCOEL** [comment]
Ok, I already know the whole problem, but the MASTER development team is not thinking about fixing the problem?
It's a big problem.

**Comment by mluis1** [comment]
A fix has been provided. Please refer to issue #218
