### ISSUE TITLE
Antenna gain clobbered during joins

### ISSUE THREAD

**Issue by jamesl-dm** [Lora-net/LoRaMac-node#312]
ResetMacParameters() is called during joins, and it resets the antenna gain to the default antenna gain. There is no way of setting the default antenna gain (short of changing the regional #defines). So there is currently no way to transmit a join request at full power if your board has an inefficient antenna, and join requests will be transmitted at additional power if your board uses a directional antenna.

Suggested fix: set the default antenna gain as well in the mib set request.

**Comment by djaeckle** [comment]
Hi jamesl-dm,

thanks for the report! We will check it.

**Comment by djaeckle** [comment]
Hi jamesl-dm,

this issue is on the roadmap for the next version: https://github.com/Lora-net/LoRaMac-node/wiki/LoRaMAC-node-Roadmap
