### ISSUE TITLE
Error message Lora communication

### ISSUE THREAD

**Issue by KarimelQ** [Lora-net/LoRaMac-node#316]
Hello everyone, 
i'm working on a Lora communication project, the problem is that when i receive data in gateway, there is an unexplicated message : 

2017-08-29 10:21:14.791 [error] <0.252.0> node 0100000A {unexpected_data,{rxdata,1,2,<<55,25,0>>,false,true}}

The data is correctly received ( humidity : 55 , temperature : 25 , xx: 0) 
But why is this considered as an error for gateway ?
and why the presece of message  : unexpected data 
Thank you

**Comment by mluis1** [comment]
No more activity we close the issue.
