### ISSUE TITLE
rtc-board.c :: RtcConvertCalendarTickToTimerTime(NULL) goes backwards

### ISSUE THREAD

**Issue by ChrisEAlfred** [Lora-net/LoRaMac-node#320]
We are using the L07x.

I have observed cases where time goes randomly backwards by a second within a few minutes.

This was first observed by setting a timer to go off every 30s in main.cpp and getting the time using TimerGetCurrentTime().

I added code inside RtcConvertCalendarTickToTimerTime() when passed NULL to capture the previous result and compare it to the new result, and verified that the time did go backwards.

As this function is also ultimately used by the MAC layer, it concerns me that this may cause false timeouts.

**Comment by GregCris** [comment]
This is not something we have observed.
I am sending you here an example of basic unit test which can be used to test the process of the timer implementation. (please change the .log in .c)
[main.log](https://github.com/Lora-net/LoRaMac-node/files/1579427/main.log)

Using the Tx-Cw project , you should be able to probe the timer completely using tests such as:

    while( i < 0xFFFF )
    {
        TimerSetValue( &Led1Timer, i );
        val1 = TimerGetCurrentTime( );
        TimerStart( &Led1Timer );
        
        while( Led1TimerEvent == false );

        Led1TimerEvent = false;

        val2 = TimerGetValue( );
        val3 = TimerGetCurrentTime( );
        val4 = TimerGetElapsedTime( val1 );

        if( val4 > ( i + 1 ) )
        {
            printf(" val4 %u  > i %u  ( val1 %u )\n\r", val4, i, val1 );
        }

        if( ( val2 != val4 ) && ( val2 > ( val4 + 1 ) ) )
        {
            printf("val2 %d, val4 %d \n\r", val2, val4 );
        }

        i++;
    }

**Comment by mluis1** [comment]
Can we close this issue?

**Comment by ChrisEAlfred** [comment]
I don't think you ran the test for long enough - you need to catch it at the right time when the milliseconds have rolled, but the seconds have not.

See https://github.com/Lora-net/LoRaMac-node/issues/480
It had to run for about 4 minutes.
