### ISSUE TITLE
file gpio.c, function GpioRemoveInterrupt, code commented

### ISSUE THREAD

**Issue by nestorayuso** [Lora-net/LoRaMac-node#325]
I don't know why the code is commented/removed in all branches, tags and releases
https://github.com/Lora-net/LoRaMac-node/blob/master/src/system/gpio.c#L61
https://github.com/Lora-net/LoRaMac-node/blob/master/src/system/gpio.c#L67

The lorawan stack and examples don't call to function GpioRemoveInterrupt anywhere so this is not a bug, But I want to use this function in my application and I realized the issue.

**Comment by mluis1** [comment]
Thanks for the report.

I guess that those are commented because we forgot to implement them for the different boards as well as for the IO expander.

We will try to add those functions implementation for the next release.

Sorry for the inconvenience.
