### ISSUE TITLE
DIO2 interrupt not used when FreqHopOn set to false?

### ISSUE THREAD

**Issue by rob2345** [Lora-net/LoRaMac-node#331]
Hello,

I'm developing a LoRa node with the LoRaMac code and the DIO 2 interrupt line was conflicting with another external interrupt pin during the sleep mode.

When I looked into this is seems that the SX1276OnDio2Irq will execute no code when FreqHopOn is set to false. By default FreqHopOn is set to false during the LoRamacInitialization for 868.

For now I was planning to disable the DIO 2 interrupt but I'm not sure if this can introduce new issues.

Does anyone know if the DIO 2 interrupt pin is also used when FreqHopOn is set to false and if it's safe to disable the interrupt pin?

Is there a chance that the FreqHopOn options will be used in the future?

**Comment by mluis1** [comment]
The DIO2 is used to get a SyncWord detect interrupt when the radio operates in FSK mode.

This means that if you don't intend to use the FSK modulation then you can disable this interrupt.

Concerning the usage f the FreqHopOn currently the LoRaWAN doesn't use it and there is no plan to use it in the future.
