### ISSUE TITLE
FCNT counter Missed while using Rx window 2 for receiving ACK from Server 

### ISSUE THREAD

**Issue by vikasrohal** [Lora-net/LoRaMac-node#333]
Hi 
I am testing with multiple End device and Sending Confirm Message , using Rx window 2 to receive ACK from Server (All devices listening on same frequency ) .
My Observation is some time FCNT missed(this issue faced while using Rx window 1 but its resolved, now same issue in Rx window 2) 

End Device version v4.3.2 (Indian ISM) tested v4.4.0 as well.

**Comment by djaeckle** [comment]
Hi vikasrohal,

thanks for the report. Could you please provide some more information?

**Comment by mluis1** [comment]
Can we close this issue?
