### ISSUE TITLE
EU868_BANDx definitions broken

### ISSUE THREAD

**Issue by svenKautlenbach** [Lora-net/LoRaMac-node#338]
Hi!

I get compilation error in **RegionEU868.c** file where **Bands** array is defined. The **struct Band_t** has 5 items while the macro only defines 4. Based on the comments in code it seems like **LastJoinTxDoneTime** member is missing.

`missing initializer for field 'TimeOff' of 'Band_t {aka struct sBand}' [-Werror=missing-field-initializers]`

![image](https://user-images.githubusercontent.com/1691796/31337673-12d9959c-ad05-11e7-98af-3ba4187e1534.png)

In order to make it compile I added missing initializer values.
![image](https://user-images.githubusercontent.com/1691796/31337288-4bb0137a-ad03-11e7-86a4-591d6ab41b73.png)

I am using GCC version from "GNU ARM Embedded Toolchain 6-2017-q2-update"  with -Wall and -Werror. This means also I am not utilizing the default project and build setup that is provided in the repo.

**Comment by nestorayuso** [comment]
I updated the pull request https://github.com/Lora-net/LoRaMac-node/pull/302 with this issue in all regions

**Comment by mluis1** [comment]
@nestorayuso Pull-request has been merged to develop branch.
We close the issue.
