### ISSUE TITLE
missing Timer

### ISSUE THREAD

**Issue by interfaith** [Lora-net/LoRaMac-node#341]
#define US915_BAND0                                 { 1, US915_MAX_TX_POWER, 0,  0 } //  100.0 %

should be

#define US915_BAND0                                 { 1, US915_MAX_TX_POWER, 0,  0, 0 } //  100.0 %

**Comment by djaeckle** [comment]
Hi interfaith,

thanks for the report. I think that the issue is related to the pull request #302 which we have applied already on the develop branch.
