### ISSUE TITLE
gps altitude

### ISSUE THREAD

**Issue by waltertakens** [Lora-net/LoRaMac-node#35]
Altitude is declared as an unsigned int in master/src/system/gps.c
In the Netherlands we live often under sealevel, eg where i live:
$GPGGA,160550.000,5200.5854,N,00442.9635,E,1,04,3.3,-40.8,M,47.1,M,,0000*4C
May i suggest you make Altitude in a future release signed ?
regards
Walter Takens

**Comment by mluis1** [comment]
Yes, you are right the altitude should be changed to a signed value. It will be done in a future release.
In the mean time you can just make a cast to the returned value
`int16_t altitude = ( int16_t ) GpsGetLatestGpsAltitude( );`
Even if the value is stored on a unsigned variable it is still a signed value.
