### ISSUE TITLE
LBT loop in AS923 and KR920 is potentially infinite

### ISSUE THREAD

**Issue by jamesl-dm** [Lora-net/LoRaMac-node#357]
RegionNextChannel() is called in a loop, until it returns an available channel. In the AS923 and KR20 regions, this involves scanning up to 16 channels for 6 ms each. If there is too much noise, RegionNextChannel will turn over until the system watchdog expires.

**Comment by djaeckle** [comment]
Hi jamesl-dm,

thanks for your report. We will verify it and come back to you.
