### ISSUE TITLE
SxRadio FSK packet of 64+ bytes

### ISSUE THREAD

**Issue by reissjason** [Lora-net/LoRaMac-node#36]
When transmitting a packet the size is the first byte. If 64 bytes are written after that FIFO will be overfilled.

Also, it seems support for FSK packets larger than 64 bytes is not complete in the SxRadio drivers.
The FifoLevel handler attempts to write data from the RxBuffer but the Send function did not copy the payload data into that buffer.

**Comment by mluis1** [comment]
The FIFO will not be overflowed if you write the packet size + 64 bytes of data. Actually the FIFO size is 65 bytes wide when variable length is used and it is 66 bytes wide in case of variable length and an address byte is used.

Yes, you are right the usage of RxBuffer variable is not correct. A correction will be provided in a future release.
