### ISSUE TITLE
HAL I2C problem with im880a module.

### ISSUE THREAD

**Issue by katariyanidhi6** [Lora-net/LoRaMac-node#361]
Hello,

I am working on im880a module. I am trying to write code for temperature sensor, that is present on im880a board on I2C protocol. I guess there is a problem in HAL I2C library. I wrote the code to for temperature sensor. It is not giving me acknowledgement. I have checked it on CRO. 

Please help me out.

Thanks in advance

**Comment by mluis1** [comment]
The im880a module itself has no I2C temperature sensor. This is maybe the reason why it is not working.

Have you solved your issue?
Can we close this issue?
