### ISSUE TITLE
OTAA join takes too long

### ISSUE THREAD

**Issue by Gecko05** [Lora-net/LoRaMac-node#367]
We're using the LoRaWAN-demo-76 in mbed at 915 MHz and trying to join a network by OTAA to a Gateway but it takes around 8 minutes and several join requests, is this normal? 
I've played around with RX timeouts, Number of Trials and Join Delays without success. Which parameters affect OTAA that I can modify to try to improve the OTAA join timing? 
ABP works without problems but we've noticed that it has some issues regarding security and packet counter after the node resets.

**Comment by fahad80** [comment]
I think that's because your gateway doesn't support all channel frequencies.

**Comment by Gecko05** [comment]
@fahad80 you're right, we're using sub band 4 with a Multitech gateway and it seems like the requests sent by the corresponding channel frequencies are the only ones being accepted, any idea of how could I configure sub band 4 into LoRaMac? I've something like this with the ChannelMask parameter but don't know how does it work.
'''static uint16_t multitechGatewayChannelsMask[6] = { 0x00FF, 0x0000, 0x0000, 0x0000, 0x0001, 0x0000};
'''

**Comment by Gecko05** [comment]
Nevermind I figured out how does the ChannelMask work, but seems like still takes several tries to join.

**Comment by fahad80** [comment]
I am not sure what is sub band 4. Do you know what frequencies your gateway is accepting?

**Comment by sabas1080** [comment]
Hi @Gecko05 

How work ChannelMask?

Thanks

**Comment by Gecko05** [comment]
Each byte of the channelmask controls up to 8 channels, for example to use sub band 3 you gotta have a channelmask of {0x00,0x00,0xFF,0x00,0x00...} Only the corresponding bytes of the channel sub band are enabled with the 0xFF, which means that we'd be using only 8 channels in the corresponding frequency to the sub band.
