### ISSUE TITLE
RtcComputeTimerTimeToAlarmTick(): Is TimeoutValueError calculated correctly?  

### ISSUE THREAD

**Issue by quylam925** [Lora-net/LoRaMac-node#369]
Hi all,

I have a little bit confused when reading the code in rtc-board.c
The function "RtcComputeTimerTimeToAlarmTick" converts the time value in ms to the value for RTC Alarm.
In this function, the error value is calculated by:
error = timeoutValue - timeoutValueTemp;       **<--- In TICK count unit**
TimeoutValueError += ( error  * 1000 );             **<--- In 1000 TICK count unit**
(**<---** indicates my comment)
then the TimeoutValueError value is compared with (RTC_ALARM_TICK_DURATION * 1000)  **<--- In us unit**
How can we compare like that???
I think the error value should be changed to us unit instead of Tick count unit before comparing with (RTC_ALARM_TICK_DURATION * 1000)
Therefore, the code should be changed from:
**error = timeoutValue - timeoutValueTemp;** 
to
**error = (timeoutValue - timeoutValueTemp) * RTC_ALARM_TICK_DURATION;** 
Is that correct?
Could somebody explain this to me please. It would be really appreciated,
Thanks

**Comment by mluis1** [comment]
Can we close this issue?

We think that the implementation is correct and validated.

**Comment by quylam925** [comment]
I have closed the issue.
Thanks

2018-02-05 22:40 GMT+09:00 Miguel Luis <notifications@github.com>:
