### ISSUE TITLE
The FSK mode in LoRaWAN

### ISSUE THREAD

**Issue by StevenChan0907** [Lora-net/LoRaMac-node#370]
Hi all,

I have some trouble in using the FSK mode in LoRaWAN EU868. I use Semtech default configuration:

#define USE_SEMTECH_DEFAULT_CHANNEL_LINEUP          1

#if( USE_SEMTECH_DEFAULT_CHANNEL_LINEUP == 1 ) 

#define LC4                { 867100000, 0, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC5                { 867300000, 0, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC6                { 867500000, 0, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC7                { 867700000, 0, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC8                { 867900000, 0, { ( ( DR_5 << 4 ) | DR_0 ) }, 0 }
#define LC9                { 868800000, 0, { ( ( DR_7 << 4 ) | DR_7 ) }, 2 }
#define LC10               { 868300000, 0, { ( ( DR_6 << 4 ) | DR_6 ) }, 1 }

Of course I also have enabled DR_7 in the code. But it can send data in FSK mode just once and then it can't work anymore.  Is there any  solution about this?

Thanks

**Comment by mluis1** [comment]
Have you found a solution to your issue?

Can we close this issue?
