### ISSUE TITLE
LoRA SX1276 can't send more than 64 byte

### ISSUE THREAD

**Issue by artuguy** [Lora-net/LoRaMac-node#373]
Hi, Everyone:
            
      I've ported sx1276 driver to the stm32f103c8,  havn't use loramac yet.  2 node work in LoRa mode,  one in continue  recieve mode,  one in send mode,  when I send < 64 bytes, everyting is OK, but when i send more than 64, ie 65,  it can't work,  the txdone  is trigger,  but  reciecve node can't indictate packet rxdone.

How dose it do?

Thanks

**Comment by fahad80** [comment]
Because:
```
#define LORAWAN_APP_DATA_BUFF_SIZE                 64
```

**Comment by artuguy** [comment]
fahad80：

           thank you， which file does the
                                 #define LORAWAN_APP_DATA_BUFF_SIZE                 64
reside？

**Comment by fahad80** [comment]
"lora.c"

**Comment by mluis1** [comment]
Can we close this issue?

**Comment by artuguy** [comment]
OK,  close it.
