### ISSUE TITLE
dr variable in RegionEU868RxConfig is signed

### ISSUE THREAD

**Issue by svenKautlenbach** [Lora-net/LoRaMac-node#374]
Hi!

Maybe it is nitpicking, since I do not know completely all the regions' implementations and requirements, but when talking about EU868, data rate is always unsigned. **Region.h** also states only positive integers. I understand that **RxConfigParams_t** has this field as a signed number. I do not know why, but in the context of **RegionEU868RxConfig()** where arrays are directly accessed (MaxPayloadOfDatarateEU868 and MaxPayloadOfDatarateRepeaterEU868) using signed integer seems ill-advised. This can be easily casted to unsigned variable.
`uint8_t dr  = (uint8_t)rxConfig->Datarate;`

Cheers!

**Comment by mluis1** [comment]
When the RxDrOffset parameter is applied to the expected datarate we may end up with a datare that is negative after the computation. That's why a signed value is used.
