### ISSUE TITLE
SetRfTxPower seems to limit TX power in SX1276

### ISSUE THREAD

**Issue by Gecko05** [Lora-net/LoRaMac-node#375]
Comparing this library to the one in lmic for Arduino we found out that this line `paConfig = ( paConfig & RF_PACONFIG_MAX_POWER_MASK ) | 0x70;` inside SetRfTxPower function seems to limit the Tx Power, makes a bitwise OR with a 0x70 where the Arduino library makes the same OR but with a 0x80. We had a lot of trouble getting our LoRa device to work properly in a decent range, but after changing it to `paConfig = ( paConfig & RF_PACONFIG_MAX_POWER_MASK ) | 0x80;` the device started working fine.   
Is there a specific reason to use 0x70 instead of 0x80?

**Comment by mluis1** [comment]
The implementation provided in this project is correct and conforms to the SX1276 datasheet.

The bit 7 of `RegPaConfing` selects which RF out put pin will be used. When the bit is 0 the RFO pin is selected and when the bit is 1 the PA_BOOST pin is selected.
The choice between the two is dependent on the PCB implementation.

To obtain the maximum output power out of the radio one must set the bits 6 to 4 at maximum value which is 7 (3 bits).

Looking at the driver implementation you will notice the 2 following lines:
```c
    paConfig = ( paConfig & RF_PACONFIG_PASELECT_MASK ) | SX1276GetPaSelect( SX1276.Settings.Channel );
    paConfig = ( paConfig & RF_PACONFIG_MAX_POWER_MASK ) | 0x70;
```

The first line selects which RF pin is enabled. In the SensorNode example it will depend on the returned value of `SX1276GetPaSelect` function. This PCB is optimized to output the max 20 dBm when the RF frequency is below 525 MHz thus the PA_BOOST pin is selected.
```c
uint8_t SX1276GetPaSelect( uint32_t channel )
{
    if( channel < RF_MID_BAND_THRESH )
    {
        return RF_PACONFIG_PASELECT_PABOOST;
    }
    else
    {
        return RF_PACONFIG_PASELECT_RFO;
    }
}
```

The second line sets the radio to output the maximum power.

Please refer to the radio datasheet.
