### ISSUE TITLE
Class C and JOIN issue

### ISSUE THREAD

**Issue by fahad80** [Lora-net/LoRaMac-node#376]
If I set my device as Class C before initiating join procedure, after a successful JOIN the radio is in sleep mode, instead of listening to RX2 window. I had to set my device to Class C again in order to open the window. 

I've tracked down the issue. Once I receive a rxDone interrupt (for a JOIN request) LoRaMac execute onRadioRxDone(). That function puts the radio in sleep. At the end of the function, it starts the OnMacStateCheckTimer. OnMacStateCheckTimerEvent() checks for class C only if LoRaMacFlags.Bits.McpsInd is set.
```
if( LoRaMacFlags.Bits.McpsInd == 1 )
{
        if( LoRaMacDeviceClass == CLASS_C )
        {
        	// Activate RX2 window for Class C
            OnRxWindow2TimerEvent( );
        }
        if( LoRaMacFlags.Bits.McpsIndSkip == 0 )
        {
            LoRaMacPrimitives->MacMcpsIndication( &McpsIndication );
        }
        LoRaMacFlags.Bits.McpsIndSkip = 0;
        LoRaMacFlags.Bits.McpsInd = 0;
}
```
As this was a JOIN request the flag isn't set hence RX2 window is never open.

So my question is, is this a bug or am I supposed to change class only after a JOIN?

**Comment by svenKautlenbach** [comment]
My CLASS C is working correct. Although what I discovered is that the radio is put to DR_3(SF9) instead of DR_0 for RX2 winow. This is EU868 band. I manually set the window dr parameter to DR_0.
![image](https://user-images.githubusercontent.com/1691796/33650742-f8448068-da6b-11e7-9d94-1d306928bffb.png)

I have not had time to track down why (maybe an error from human side - me) but maybe this helps.

**Comment by fahad80** [comment]
I never said Class C isn't working. It's working. But I had to change to class C after I JOINED a network. If I changed my class using LoRaMacMibSetRequestConfirm() before I join a network, it doesn't work. What order did you follow?

**Comment by fahad80** [comment]
Maybe I wasn't clear enough. My Class C works. I am asking a different question. Simply put:

1) Change Class to C ------ JOIN------> Doesn't work
2)Class A--JOIN--Change Class to C--> Works

Successful join puts Radio into sleep, even if you are class C. I beilieve its a bug.

**Comment by mluis1** [comment]
@fahad80 If you are using OTAA activation you must set the device in ClassC after the join procedure succeeds.
The device is supposed to always start as a ClassA device. Thus the device class parameter gets reset when performing the Join procedure.

When using ABP activation the issue isn't seen.

We will update the application examples as soon as possible.

**Comment by fahad80** [comment]
@mluis1 Thanks a lot. That's what I needed to know. Now I can go to sleep peacefully.
