### ISSUE TITLE
AckTimeoutTimer during Class C

### ISSUE THREAD

**Issue by fahad80** [Lora-net/LoRaMac-node#377]
@djaeckle 's commit https://github.com/Lora-net/LoRaMac-node/commit/32c9b19ad5059256dd92a85dec373a0f9b23b995 broke Class C (receiving data on RX window 2). Here is how:
After a successful JOIN, I can receive data from NS. All good. But as soon as I send a packet from node, it stops receiving packets from NS on RX window 2. I traced down the issue at `OnRadioRxDone()`:

```
 // Verify if we need to disable the AckTimeoutTimer
    CheckToDisableAckTimeout( NodeAckRequested, LoRaMacDeviceClass, McpsConfirm.AckReceived, AckTimeoutRetriesCounter, AckTimeoutRetries );

    if( AckTimeoutTimer.IsRunning == false )
    {
    	// Procedure is completed when the AckTimeoutTimer is not running anymore
        LoRaMacFlags.Bits.MacDone = 1;

        // Trig OnMacCheckTimerEvent call as soon as possible
        TimerSetValue( &MacStateCheckTimer, 1 );
        TimerStart( &MacStateCheckTimer );
    }
```

Although `CheckToDisableAckTimeout()` turned off `AckTimeoutTimer` but `AckTimeoutTimer.IsRunning` is still TRUE.

You can manually start the `AckTimeoutTimer` and stop it inside the callback and you will see `AckTimeoutTimer.IsRunning` is still true.

**Comment by djaeckle** [comment]
Hi fahad80,

thanks for your report! I will double check your finding. At least my simulations provide a pass for my commit - however, the timer implementation is abstracted here. I will come back to you soon.

**Comment by mluis1** [comment]
Could you please try the following patch?
Please let us know if it solves the issue.

```patch
diff --git a/src/system/timer.c b/src/system/timer.c
index 526e0e3..1aa6063 100644
--- a/src/system/timer.c
+++ b/src/system/timer.c
@@ -280,9 +280,9 @@ void TimerStop( TimerEvent_t *obj )
 
             remainingTime = obj->Timestamp - elapsedTime;
 
+            TimerListHead->IsRunning = false;
             if( TimerListHead->Next != NULL )
             {
-                TimerListHead->IsRunning = false;
                 TimerListHead = TimerListHead->Next;
                 TimerListHead->Timestamp += remainingTime;
                 TimerListHead->IsRunning = true;
```

**Comment by mluis1** [comment]
The proposed fix should solve the issue. As no feedback is provided we close the issue.
