### ISSUE TITLE
Porting to STM32F051R8 help

### ISSUE THREAD

**Issue by sommmen** [Lora-net/LoRaMac-node#378]
Hi,

I'm trying to get Lora to work on the STM32F051R8 discovery with an external SX1276.
But i am having trouble getting started.

I kind of need a barebones boilerplate, the current examples all have a lot of stuff implemented already and its hard to wrap your head around (I don't need GPS or battery level etc. I just need 'hello world').

a) Is there a more stripped down version available somewhere?
b) Where should I start? just go through Main.c trying to adapt everything?

The porting guide is a bit vague - without any architectural overview (what interupts do we need, what is DMA used?). Are there any other resources I could take a look at? (article on how the other boards where ported for example.)

**Comment by mluis1** [comment]
Please refer to the project Doxygen documentation [Porting Guide](http://stackforce.github.io/LoRaMac-doc/_p_o_r_t_i_n_g__g_u_i_d_e.html)
