### ISSUE TITLE
FRAME_TYPE_JOIN_REQ power optimization random seed source

### ISSUE THREAD

**Issue by hegetluk** [Lora-net/LoRaMac-node#384]
I have a power optimization question.
In LoraMac, when sending a Join Request a real random seed is taken from the Lora radio with radio.random().
Is this necessary if the pseudo random seed is already initialized with a real random number? The random functions are seeded during initialization in LoraMac.
Taking a random seed from randr when sending a Join Request would save a lot of energy....
or do we have security problems afterwards?

**Comment by mluis1** [comment]
The impact on the power consumption isn't really very big. A end-device will not execute the Join procedure very often in its life. In plus the power consumption used to generate the random number can be neglected compared to the power consumption of the JoinReq transmission.

A true random number is used for security reasons. A pseudo random sequence is reproductible even if it is seeded with a true random number.
In plus currently the LoRaWAN specification 1.0.x mandates the usage of a true random number for every JoinReq.

This will change for LoRaWAN specification 1.1 where a counter value will be used instead. The security has greatly been improved with this specification.
