### ISSUE TITLE
Class B/C Multicast / DownlinkCounter

### ISSUE THREAD

**Issue by GrumpyOldPizza** [Lora-net/LoRaMac-node#387]
Each downlink frame has the 16 LSBs of the DownlinkCounter embedded. The MIC embeds however the full 32 bit DownlinkCounter. 

At the start of a multicast session a node does not know the upper 16 bits of the DownlinkCounter. 

How are those upper 16 bits derived ?

**Comment by mluis1** [comment]
The LoRa-Alliance is currently defining an upper layer that will specify how the multicast channels must be handled.

One of the commands defined for this upper layer is the multicast channel setup where the server provides the counters initial values amongst other parameters.
