### ISSUE TITLE
'datarate' may be used uninitialized in this function

### ISSUE THREAD

**Issue by svenKautlenbach** [Lora-net/LoRaMac-node#391]
**datarate** variable inside LoRaMacMcpsRequest() can get a compile warning/error on row 3285. That is because the preceding switch/case does not handle the variable inside default case. 

The same problem can be spotted when running static (clang) analyzer which reports the following:
`The left operand of '<' is a garbage value `

My suggestion:
```
   default:
	datarate = 0;
        break;
```

**Comment by nestorayuso** [comment]
issue repeated and already fixed in the develp branch
https://github.com/Lora-net/LoRaMac-node/pull/340
