### ISSUE TITLE
Discrepancy in header registers and datasheet

### ISSUE THREAD

**Issue by photonthunder** [Lora-net/LoRaMac-node#395]
The sx1272Regs-LoRa.h file contains reference to SX127X_REG_LR_INVERTIQ2 (0x38) which does not exist in the latest datasheet (Rev. 3.1 - March 2017).  Furthermore, SX127X_REG_LR_INVERTIQ (0x33) exists in the datasheet but the values such as SX127X_RF_LORA_INVERTIQ_RX_ON do not.  I am assuming following the driver and header file is correct (since it appears to work), but why the discrepancy from the datasheet?

**Comment by mluis1** [comment]
The header files are correct and validated.

This question is related to the chip itself and not really related to this project. I would advise you to ask this question on LoRa Community portal or to contact Semtech directly.
