### ISSUE TITLE
REJOIN function

### ISSUE THREAD

**Issue by rrattinypcbs** [Lora-net/LoRaMac-node#401]
Hi,
In reading the LoRaWAN 1.1 spec, it seems apparent that our class A end node should issue a type 1 rejoin at some interval between a day and a week or two. This same function would facilitate rejoins after deep power cycles and when we run the frame count to the limit.
Is this buried in the source somewhere? If not any guidance would be greatly appreciated to get this moving forward and implemented in a manner that all can re-use.

I note the MAC commands in the spec 
0x0E ForceRejoinReq, 0x0F RejoinParamSetupReq and RejoinParamSetupAns but havent located how they are implemented in this code repository.
v/r,
Rob

**Comment by nestorayuso** [comment]
the code in the repository implements LoRaWAN 1.0.2 at the moment.
check https://github.com/Lora-net/LoRaMac-node/wiki/LoRaMAC-node-Roadmap for the LoRaWAN 1.1 implementation timeframe
