### ISSUE TITLE
Select sub-band for Gateway 8 channels

### ISSUE THREAD

**Issue by sabas1080** [Lora-net/LoRaMac-node#404]
Hi

I'm trying to connect to a multitech gateway that is listening in sub-band 7, I've seen some examples but I still can not understand how it works:

`static uint16_t multitechGatewayChannelsMask[6] = { 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00};`

Example:

`static uint16_t multitechGatewayChannelsMask[6] = { 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00};`

 ```   mibReq.Type = MIB_CHANNELS_DEFAULT_MASK;
    mibReq.Param.ChannelsDefaultMask = multitechGatewayChannelsMask;
    LoRaMacMibSetRequestConfirm( &mibReq );
   
    mibReq.Type = MIB_CHANNELS_MASK;
    mibReq.Param.ChannelsMask = multitechGatewayChannelsMask;
    LoRaMacMibSetRequestConfirm( &mibReq );`


Thanks

**Comment by jamesl-dm** [comment]
Don't you need:
static uint16_t multitechGatewayChannelsMask[6] = { 0x0000, 0x0000, 0x00FF, 0x0000, 0x0000, 0x0000};
?

**Comment by sabas1080** [comment]
Ok,

`static uint16_t multitechGatewayChannelsMask[6] = { 0x0000, 0x0000, 0x0000, 0x00FF, 0x0000, 0x0100};`

 for Subband 7 with channel of 500khz?
