### ISSUE TITLE
Track Radio Drivers in separate repository

### ISSUE THREAD

**Issue by loverdeg-ep** [Lora-net/LoRaMac-node#408]
Can each radio driver be tracked in it's own repository?
They could then be imported here as git sub modules or some other approach.

With the current setup if someone wanted to mirror or fork the drivers they need to drag the whole mac and all the examples and board support with it.

**Comment by mluis1** [comment]
As of today we never thought to make separate repositories.

At first sight the proposition looks valid but, we need to think how we could do it.

We will add this to our internal ticket system as a reminder. This task will be setup with a very low priority.
