### ISSUE TITLE
rxdone interrupt

### ISSUE THREAD

**Issue by gnob417** [Lora-net/LoRaMac-node#412]
Hi,
when does `rxDone` interrupt is called? 
i mean, there is max rx window timeout value such as 4000 ms.
and, a packet is received completely at 2000ms of 4000ms. 

in this time the interrupt is called or after 4000ms finished?

as far as i know, node could know the start of the packet from "SFD" signal, however it doesn't know when the packet transmission is finished.

any advice please?

**Comment by mluis1** [comment]
The RxDone interrupt is called when the radio has successfully finished a frame reception.

The max Rx window is there just in case the RxTimeout or RxDone interrupts aren't generated for some reason.

As already suggested in other issues (i.e: #398) this kind of questions are general and not really related to this project. I would recommend that in the future you try to ask your questions on the [LoRa Community](http://semtech.force.com/lora) portal.
