### ISSUE TITLE
Radio driver for SX1261

### ISSUE THREAD

**Issue by dsmith-tek** [Lora-net/LoRaMac-node#414]
Is there any plan to add driver support for the new SX1261 radio? Seems to be a big improvement over the sx1272 and sx1276.

Cheers

**Comment by nestorayuso** [comment]
there is a part implementation here:
https://github.com/LoRaWanMiniMouse/Mini-Mouse/tree/dev/radio/SX1276Lib

**Comment by mluis1** [comment]
Yes, we will add the support for the SX126x radio. 
The drivers are already implemented and ready to be pushed but, as of today Semtech hasn't made the radio publicly available.

**Comment by mluis1** [comment]
We just got the authorization to push the SX126x radio drives support. The develop and class_b branches have been updated.
