### ISSUE TITLE
LoRaWAN Regional Parameters v1.1rB

### ISSUE THREAD

**Issue by 4refr0nt** [Lora-net/LoRaMac-node#415]
Add RU regional parameters as LoRaWAN Regional Parameters v1.1rB

**Comment by mluis1** [comment]
This region will be added in the future.

Currently this project only provides LoRaWAN specification 1.0.2 implementation. The companion regional parameters document is LoRaWAN Regional Parameters v1.0.2rB.

Please note that the RU region addition should be quite straight forward as it very similar to the EU region.
