### ISSUE TITLE
Is the LoRashield from Dragino supported by this project?

### ISSUE THREAD

**Issue by desword** [Lora-net/LoRaMac-node#424]
The product from  http://www.dragino.org/.

http://wiki.dragino.com/index.php?title=Lora_Shield#Features

**Comment by x893** [comment]
Yes

**Comment by desword** [comment]
Thanks, I will have a try!

**Comment by x893** [comment]
But you need make change sources for this shield.

**Comment by desword** [comment]
Thanks, and could you please provide some details about how to change the sources?

**Comment by mluis1** [comment]
You may refer to the following documentation [Porting Guide](http://stackforce.github.io/LoRaMac-doc/_p_o_r_t_i_n_g__g_u_i_d_e.html)
