### ISSUE TITLE
VScode cmake error, clean repo clone 23-03-2018

### ISSUE THREAD

**Issue by littleboot** [Lora-net/LoRaMac-node#428]
Hello,

After following the WIKI step by step and installing VScode + cmake and minGW. (!note information that you also need to install minGW to make it work is missing on the wiki). Now I'm tying to compile the project latest version as of today (clone of the repo master an opening the extracted folder inside VScode) I get the following cmake errors:

```
[cmake-server] loading initial cache file c:\users\user\documents\loramac-node-master\build\CMakeTools\InitializeCache.cmake

-- CMake Error at src/CMakeLists.txt:63 (include):
  include could not find load file:

    stm32l1


-- CMake Error at src/apps/LoRaMac/CMakeLists.txt:75 (include):
  include could not find load file:

    gdb-helper


-- CMake Error at src/apps/LoRaMac/CMakeLists.txt:76 (include):
  include could not find load file:

    binutils-arm-none-eabi


-- CMake Error at src/apps/LoRaMac/CMakeLists.txt:79 (generate_run_gdb_stlink):
  Unknown CMake command "generate_run_gdb_stlink".


-- Configuring incomplete, errors occurred!
See also "c:/users/user/documents/loramac-node-master/build/CMakeFiles/CMakeOutput.log".
[vscode] Configure failed: [cmake-server] Configuration failed.
```

It looks like the errors are present inside the project (I didn't modify any files after downloading and extracting), but I'm not sure because this is the first time I used cmake. Could someone help me fix these problems?

**Comment by tpet93** [comment]
adding this line 

`set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/cmake" CACHE STRING "Modules for CMake" FORCE)`

to CMakeLists.txt in the main directory helps for me . I'm still getting other compiler issues which may be unrelated to LoraMac

**Comment by djaeckle** [comment]
Hi littleboot,

which CMake version are you using?

**Comment by littleboot** [comment]
Hello, Thank you very much I can compile the project without errors. But do you mind explaining what the above line in de CMakeLists.txt does? 
my CMake is already added to PATH, (verified using cmd-prompt "cmake -version return the cmake version correctly). So why does the above line solve my problems?

**Comment by littleboot** [comment]
cmake version 3.11.0-rc4

**Comment by djaeckle** [comment]
Have you also tried the latest release (3.10.3)?

**Comment by littleboot** [comment]
No I haven't tried, But it seems to be working now with version 3.11.0-rc4 after adding:
`set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_CURRENT_LIST_DIR}/cmake" CACHE STRING "Modules for CMake" FORCE)`

**Comment by jobrud** [comment]
Thanks for you feedback, we will update the instructions. We tested it with the latest full release of CMake but your issue doesn't occur on our desk.
It would be nice if you could try the latest full release as well.

The `CMAKE_MODULE_PATH` is the path where CMake search for CMake modules. Our CMake modules are located under `cmake/..` and this [line](https://github.com/Lora-net/LoRaMac-node/blob/1cdd9ccec4c9f05b616e7112059be4a9e358c571/cmake/toolchain-arm-none-eabi.cmake#L23) in the toolchain file adds this directory to the `CMAKE_MODULE_PATH`.

**Comment by littleboot** [comment]
@jobrud 
I just tried both CMAKE versions:
CMAKE 3.11.0 or 3.10.3 (makes no difference I get the same errors)

```
The C compiler identification is GNU 6.3.0
The CXX compiler identification is GNU 6.3.0
Could not determine Eclipse version, assuming at least 3.6 (Helios). Adjust CMAKE_ECLIPSE_VERSION if this is wrong.
Check for working C compiler: C:/MinGW/bin/gcc.exe
Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/MinGW/bin/g++.exe
Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - failed
CMake Error at src/CMakeLists.txt:63 (include):
  include could not find load file:

    stm32l1


The ASM compiler identification is GNU
Found assembler: C:/MinGW/bin/gcc.exe
CMake Error at src/apps/LoRaMac/CMakeLists.txt:75 (include):
  include could not find load file:

    gdb-helper


CMake Error at src/apps/LoRaMac/CMakeLists.txt:76 (include):
  include could not find load file:

    binutils-arm-none-eabi


CMake Error at src/apps/LoRaMac/CMakeLists.txt:79 (generate_run_gdb_stlink):
  Unknown CMake command "generate_run_gdb_stlink".


Configuring incomplete, errors occurred!
See also "C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeOutput.log".
See also "C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeError.log".
```

```
CMakeError.log

Detecting CXX [-std=c++98] compiler features failed to compile with the following output:
Change Dir: C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp

Run Build Command:"C:/MinGW/bin/mingw32-make.exe" "cmTC_dae0a/fast"
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_dae0a.dir\build.make CMakeFiles/cmTC_dae0a.dir/build

mingw32-make.exe[1]: Entering directory 'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp'

Building CXX object CMakeFiles/cmTC_dae0a.dir/feature_tests.cxx.obj

C:\MinGW\bin\g++.exe    -std=c++98 -o CMakeFiles\cmTC_dae0a.dir\feature_tests.cxx.obj -c C:\Users\KLIJN\Documents\LoRaMac-node\build\CDT\CMakeFiles\feature_tests.cxx

Linking CXX executable cmTC_dae0a.exe

"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\cmTC_dae0a.dir\link.txt --verbose=1

"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\cmTC_dae0a.dir/objects.a
C:\MinGW\bin\ar.exe cr CMakeFiles\cmTC_dae0a.dir/objects.a @CMakeFiles\cmTC_dae0a.dir\objects1.rsp
C:\MinGW\bin\g++.exe      -Wl,--whole-archive CMakeFiles\cmTC_dae0a.dir/objects.a -Wl,--no-whole-archive  -o cmTC_dae0a.exe -Wl,--out-implib,libcmTC_dae0a.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\cmTC_dae0a.dir\linklibs.rsp
mingw32-make.exe[1]: Leaving directory 'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp'


Cannot copy output executable
  'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp/cmTC_dae0a.exe'
to destination specified by COPY_FILE:
  'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/feature_tests.bin'


Detecting CXX [-std=c++98] compiler features failed to compile with the following output:
Change Dir: C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp

Run Build Command:"C:/MinGW/bin/mingw32-make.exe" "cmTC_dc3ea/fast"
C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_dc3ea.dir\build.make CMakeFiles/cmTC_dc3ea.dir/build

mingw32-make.exe[1]: Entering directory 'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp'

Building CXX object CMakeFiles/cmTC_dc3ea.dir/feature_tests.cxx.obj

C:\MinGW\bin\g++.exe    -std=c++98 -o CMakeFiles\cmTC_dc3ea.dir\feature_tests.cxx.obj -c C:\Users\KLIJN\Documents\LoRaMac-node\build\CDT\CMakeFiles\feature_tests.cxx

Linking CXX executable cmTC_dc3ea.exe

"C:\Program Files\CMake\bin\cmake.exe" -E cmake_link_script CMakeFiles\cmTC_dc3ea.dir\link.txt --verbose=1

"C:\Program Files\CMake\bin\cmake.exe" -E remove -f CMakeFiles\cmTC_dc3ea.dir/objects.a
C:\MinGW\bin\ar.exe cr CMakeFiles\cmTC_dc3ea.dir/objects.a @CMakeFiles\cmTC_dc3ea.dir\objects1.rsp
C:\MinGW\bin\g++.exe      -Wl,--whole-archive CMakeFiles\cmTC_dc3ea.dir/objects.a -Wl,--no-whole-archive  -o cmTC_dc3ea.exe -Wl,--out-implib,libcmTC_dc3ea.dll.a -Wl,--major-image-version,0,--minor-image-version,0 @CMakeFiles\cmTC_dc3ea.dir\linklibs.rsp
mingw32-make.exe[1]: Leaving directory 'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp'


Cannot copy output executable
  'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/CMakeTmp/cmTC_dc3ea.exe'
to destination specified by COPY_FILE:
  'C:/Users/KLIJN/Documents/LoRaMac-node/build/CDT/CMakeFiles/feature_tests.bin'
```

I also tried ninja instead of minGW but it makes no difference. I also tried only adding CMAKE to used path, also no difference.

**Comment by jobrud** [comment]
Unfortunately, I don't really have an idea what it could be. Just to be sure:
Did you delete the build directory before trying another CMake version?
The CMake error log doesn't look like the one showed in VSCode. In addition, there are eclipse related steps included. Did you try it with eclipse ?

I suggest to try it on the commandline like described [here](https://github.com/Lora-net/LoRaMac-node/blob/master/Doc/development-environment.md#commandline-build-instructions) to rule out other causes.

**Comment by GuntherSchulz** [comment]
Try running CMAKE with Administrator permissions

**Comment by littleboot** [comment]
@jobrud
Yes I deleted the build directory, tried different locations also. but same error.
I also tried Eclipse and VScode, still the same,
@GuntherSchulz 
Yes I've run CMake as administrator.

I even created an clean windows 10 installation inside a virtual box. only installed the needed tools, but I get exactly the same errors. I will upload and link my virtual disk image of this VM (virtual box) soon and post the link.
So if someone want to have a look, please I'm very curious about what is causing the problems.

**Comment by 1405224** [comment]
Hi,
I have also followed the instructions to implement this project and now I'm facing the errors below:
First when i build, I get:
[build] make[2]: *** [src/apps/LoRaMac/LoRaMac-classA] Error 1
[build] make[1]: *** [src/apps/LoRaMac/CMakeFiles/LoRaMac-classA.dir/all] Error 2
[build] make: *** [all] Error 2
[build] Build finished with exit code 2

Then, when i try to Debug, i get a popup message:
launch: program '/Users/LoRaMac-node/build/src/apps/LoRaMac/LoRaMac-classA' does not exist

Also, in the 'Problems' tap I've got:
Property MIDebuggerPath is not allowed

Could anyone please help me??

Thanks

**Comment by ZuratonE** [comment]
> Property MIDebuggerPath is not allowed
The file **loramac-node/cmake/launch.json.in** is used to generate launch.json for VSCode.
Edit this file: **change "MIDebuggerPath" to "miDebuggerPath"**

**Comment by mluis1** [comment]
The author of CMake Tools extension for VSCode has changed the way his extension works. The extension now relies on "Kits". Please refer to the extension documentation for further instructions [Getting Started](https://vector-of-bool.github.io/docs/vscode-cmake-tools/getting_started.html)

As this issue is not really related to this project we close it.
