### ISSUE TITLE
NucleoL073 & NucleoL152: Radio.IrqProcess() called in main(), but it is a NULL pointer

### ISSUE THREAD

**Issue by pieterconradie** [Lora-net/LoRaMac-node#430]
Hi everyone,

The LoraMac (class A, B & C) and ping-pong apps built for NucleoL073 & NucleoL152 with SX1272MBAS shield contain a call to Radio.IrqProcess() in main(), but this function pointer is set to NULL (it is not set to a valid value in sx1272-board.c. The only place where this field is set to a valid value is in src/radio/sx126x/radio.c

I have commented out the offending call to a NULL pointer, but the unit still does not join the LoRaWAN network and I'm investigating...

Regards,
Pieter

**Comment by mluis1** [comment]
This has been corrected on develop branch. We discovered the issue just after the release.
Please see commit bdb7a2e831dd6f788c8e1b9655df07694a992415.
