### ISSUE TITLE
RtcComputeTimerTimeToAlarmTick problem?

### ISSUE THREAD

**Issue by ThomasNauwelaerts** [Lora-net/LoRaMac-node#432]
In rtc-board.c there seems te be something wrong with the compute timer time to alarm tick.
At line 457 we are calculating the number of ticks in timeCounter. We save this value in timeoutValue.
At line 476 we compare timeoutValue >= SecondsInDay, where timeoutValue is in ticks, SecondsInDay is in seconds?

**Comment by mluis1** [comment]
This issue isn't anymore present. We have completely refactored the RTC drivers.
