### ISSUE TITLE
Frequency hopping in Ping Pong Example

### ISSUE THREAD

**Issue by rohitkumar5293** [Lora-net/LoRaMac-node#435]
Hi,

Is it possible to implement frequency hopping in PING PONG example because what i know PING PONG is based on LoRa communication ( pear to pear communication) whereas frequency hopping and channel masking is based on LoRaMAC protocol (LoRaWAN)? If yes please let me know how i can implement frequency hopping in lora (P2P) protocol. 

Thanks

**Comment by mluis1** [comment]
Unfortunately we have no such example. I would recommend that you post a question on the [LoRa Community](https://semtech.force.com/lora/LC_CommunityLanding) website.

But, yes, it should be possible to implement a frequency hopping algorithm for the ping-pong example.
