### ISSUE TITLE
Class B implementation 

### ISSUE THREAD

**Issue by 1405224** [Lora-net/LoRaMac-node#436]
Hi,
I’m trying to implement the LoRa class b, but due to my limited knowledge in embedded programming, I have few questions if you don’t mind answering them..
I would like to know which compiler are you using? And is it possible to use the mbed online compiler as I’m kind of familiar with it?
Also I would like to know if the code is compatible with the boards I have which are the MultiTech mDot and the LoRa LPWAN STM32L072 MCU Discovery Kit (STM32L072CZ). 
When I choose either of them in the mbed compiler and compile the code I get the same error below:

Error: Identifier "NSWITCH_1" is undefined "GpioInit(&Switch1, NSWITCH_1,PIN_INPUT,PIN_PUSH_PULL,PIN_NO_PULL,0);"
Error: Identifier "NSWITCH_2" is undefined "GpioInit(&Switch2, NSWITCH_2,PIN_INPUT,PIN_PUSH_PULL,PIN_NO_PULL,0);"
Error: Identifier "NSWITCH_3" is undefined "GpioInit(&Switch3, NSWITCH_3,PIN_INPUT,PIN_PUSH_PULL,PIN_NO_PULL,0);"

Any ideas on how to overcome these errors?  

Thanks

**Comment by djaeckle** [comment]
Hi 1405224,

you can find a description of the environment here: https://github.com/Lora-net/LoRaMac-node/wiki/Development-environment. Furthermore, a list of supported devices of this projects is available in the readme https://github.com/Lora-net/LoRaMac-node.
