### ISSUE TITLE
LoRaMacQueryTxPossible: if MAC commands do not fit current data rate

### ISSUE THREAD

**Issue by axu217** [Lora-net/LoRaMac-node#437]
_MacCommandsBufferIndex_ and _MacCommandsBufferRepeatIndex_ are both set to 0. Does this mean that MAC commands that were in the buffer are going to be ignored forever?

**Comment by djaeckle** [comment]
Hi axu217,

yes, thats true. The reason is that the MAC has to ensure that another uplink is possible. Please note that this procedure will change in LoRaWAN Specification v1.1 - here, the MAC commands are clipped.
