### ISSUE TITLE
Stack version 4.4.1 - Preferred method to enable/disable channels

### ISSUE THREAD

**Issue by SaintBorio** [Lora-net/LoRaMac-node#439]
Hi,

I was wondering, since the new Regional features have been implemented in the stack, which is the preferred and most clean way to enable/disable or assign frequency to a given channel.
At the moment, infact, I'm modifying directly the ChannelsMask and ChannelsDefaultMask as follow:

static uint16_t NewChannelsMask[6] = { 0xFFFF, 0xFFFF, 0x0000, 0x0000, 0x0000, 0x0000};

    mibReq.Type = MIB_CHANNELS_DEFAULT_MASK;
    mibReq.Param.ChannelsDefaultMask = NewChannelsMask;
    LoRaMacMibSetRequestConfirm( &mibReq );

    mibReq.Type = MIB_CHANNELS_MASK;
    mibReq.Param.ChannelsMask = NewChannelsMask;
    LoRaMacMibSetRequestConfirm( &mibReq );

Is there an alternative way ?
Regards.

**Comment by nestorayuso** [comment]
The most clean way is to use OTAA and let the Network Server to manage the channels in the join response.

The code you propose is fine if you use ABP, because you are personalizating the device to a specific network server and specific channel plan.

**Comment by SaintBorio** [comment]
Thanks for the answer. I’m actually concerned about the end device starting the otaa on a frequency outside the Gw and network server frequencies. For example on a US915 I get otaa requests on 908 MHz, far away from the 0-15 channels of the GW and Network Server. Am I wrong trying to limit the channels on the end device ?

**Comment by djaeckle** [comment]
Hi SaintBorio,

actually, I agree to the answer of nestorayuso - this is the most clean way, especially for devices with variable channel definitions. However, every region provides a definition o mandatory channels to ensure that a node is able to always send on a known channel.

I guess you are refering to the US-Hybrid version. Please note that this is not a region defined by the LoRaWAN Specification. You need to enable the compatibilty on your own.
