### ISSUE TITLE
Contiguous LinkADRReq commands invalid ChMaskCtrl (RFU) and ChMask 

### ISSUE THREAD

**Issue by JiapengLi** [Lora-net/LoRaMac-node#447]
Current implementation will ignore ChMask / ChMaskCtrl error except the last LinkADRReq command. 
This seems not LoRaWAN specification compatible, LoRaWAN specification allow to device to process `DataRate, TXPower and NbTrans` from the last message but doesn't include ChMask and ChMaskCtrl.

ChMask and ChMaskCtrl error should not be overwritten.

> The network server may include multiple LinkAdrReq commands within a single downlink  
> message. For the purpose of configuring the end-device channel mask, the end-device will  
> process all contiguous LinkAdrReq messages, in the order present in the downlink message,  
> as a single atomic block command. The end-device will accept or reject all Channel Mask  
> controls in the contiguous block, and provide consistent Channel Mask ACK status indications  
> for each command in the contiguous block in each LinkAdrAns message, reflecting the  
> acceptance or rejection of this atomic channel mask setting. The device will only process the  
> DataRate, TXPower and NbTrans from the last message in the contiguous block, as these  
> settings govern the end-device global state for these values. The end-device will provide  
> consistent ACK status in each LinkAdrAns message reflecting the acceptance or rejection of  
> these final settings. 

For example:
```c
uint8_t RegionKR920LinkAdrReq( LinkAdrReqParams_t* linkAdrReq, int8_t* drOut, int8_t* txPowOut, uint8_t* nbRepOut, uint8_t* nbBytesParsed )
{
    uint8_t status = 0x07;
    RegionCommonLinkAdrParams_t linkAdrParams;
    uint8_t nextIndex = 0;
    uint8_t bytesProcessed = 0;
    uint16_t chMask = 0;
    GetPhyParams_t getPhy;
    PhyParam_t phyParam;
    RegionCommonLinkAdrReqVerifyParams_t linkAdrVerifyParams;

    while( bytesProcessed < linkAdrReq->PayloadSize )
    {
        // Get ADR request parameters
        nextIndex = RegionCommonParseLinkAdrReq( &( linkAdrReq->Payload[bytesProcessed] ), &linkAdrParams );

        if( nextIndex == 0 )
            break; // break loop, since no more request has been found

        // Update bytes processed
        bytesProcessed += nextIndex;

        // Revert status, as we only check the last ADR request for the channel mask KO
        status = 0x07;

        // Setup temporary channels mask
        chMask = linkAdrParams.ChMask;

        // Verify channels mask
        if( ( linkAdrParams.ChMaskCtrl == 0 ) && ( chMask == 0 ) )
        {
            status &= 0xFE; // Channel mask KO
        }
        else if( ( ( linkAdrParams.ChMaskCtrl >= 1 ) && ( linkAdrParams.ChMaskCtrl <= 5 )) ||
                ( linkAdrParams.ChMaskCtrl >= 7 ) )
        {
            // RFU
            status &= 0xFE; // Channel mask KO
        }
        else
        {
            for( uint8_t i = 0; i < KR920_MAX_NB_CHANNELS; i++ )
            {
                if( linkAdrParams.ChMaskCtrl == 6 )
                {
                    if( Channels[i].Frequency != 0 )
                    {
                        chMask |= 1 << i;
                    }
                }
                else
                {
                    if( ( ( chMask & ( 1 << i ) ) != 0 ) &&
                        ( Channels[i].Frequency == 0 ) )
                    {// Trying to enable an undefined channel
                        status &= 0xFE; // Channel mask KO
                    }
                }
            }
        }
    }
```
```c
        // Revert status, as we only check the last ADR request for the channel mask KO
        status = 0x07;
```

**Comment by djaeckle** [comment]
Hi JiapengLi,

I see your point. However, i understand it in that way that e.g. for EU, every LinkAdrReq in a atomic block overwrites the previous one in the atomic block. Which means that only the settings of the last LinkAdrReq will be verified with respect to the data rate, the rx power and the nb trans. This results in

> consistent Channel Mask ACK status indications
> for each command in the contiguous block in each LinkAdrAns message, reflecting the
> acceptance or rejection of this atomic channel mask setting.

I think this feature is designed for regions which have more than 16 channels, e.g. the US band, especially. Here it's possible to configure more channel mask blocks.
