### ISSUE TITLE
MAC state

### ISSUE THREAD

**Issue by FoujanetG** [Lora-net/LoRaMac-node#45]
Hi,

I 'am in Class C, 868MHz.
I would like to use the LoraMac internal state with the variable  `LoRaMacState` . I created a function to return this state to the application. 
My goal is to know when we are in TX. 

When I send a Confirmed frame with 5 repetitions for example, the stack is in `MAC_TX_RUNNING` mode until the acknowledge reception.

I excepted that the stack switch from `MAC_TX_RUNNING`  to `MAC_RX` and so forth, until the acknowledge reception. And finally, the stack will be in  `MAC_RX` --> due to the Class C.

But the reality is : the state is `MAC_TX_RUNNING` until the acknowledge reception (even if there is several TX due to the repetitions (confirmed send) ). when the acknowledge is incoming, the state is `MAC_RX`  and after the state is `MAC_IDLE`.

Is it normal in Class C that the state stack can be `MAC_IDLE`?
Maybe the variable  `LoRaMacState` is the stack state and not the radio state. But between a TX and a new TX, the stack should be in `MAC_IDLE` . ? 

What are you think about that?

Thanks,

Guillaume F.

**Comment by djaeckle** [comment]
Hi FoujanetG,

yes, the `LoRaMacState `represents the internal state of the MAC and not the state of the radio. Thus, I think you should not use your implementation to query radio states.

> I excepted that the stack switch from `MAC_TX_RUNNING` to `MAC_RX` and so forth, until the acknowledge reception. And finally, the stack will be in `MAC_RX` --> due to the Class

> But the reality is : the state is `MAC_TX_RUNNING` until the acknowledge reception (even if there is several TX due to the repetitions (confirmed send) ). when the acknowledge is incoming, the state is `MAC_RX` and after the state is `MAC_IDLE`.

> Maybe the variable `LoRaMacState` is the stack state and not the radio state. But between a TX and a new TX, the stack should be in `MAC_IDLE` . 

Yes, this is correct. Currently, the state `MAC_TX_RUNNING` defines, that a request is in progress. The MAC will stay in this state until the requests is fully processed. This also includes retransmissions or repetitions. When the MAC processes a request, the MAC shall reject other application requests.

> Is it normal in Class C that the state stack can be `MAC_IDLE`?

Yes, this is true. However, I see your point.

I think that we will spend some time for a review of the LoRaMac states. But at the moment, I cannot say when we provide an update.
