### ISSUE TITLE
US region minimum datarate

### ISSUE THREAD

**Issue by smartyboy** [Lora-net/LoRaMac-node#450]
Hi
In mac/region/RegionUS915.h stands
`#define US915_TX_MIN_DATARATE                       DR_0
`
In mac/region/RegionUS915.c
```
int8_t RegionUS915AlternateDr( AlternateDrParams_t* alternateDr )
{
    int8_t datarate = 0;

    // Re-enable 500 kHz default channels
    ChannelsMask[4] = 0x00FF;

    if( ( alternateDr->NbTrials & 0x01 ) == 0x01 )
    {
        datarate = DR_4;
    }
    else
    {
        datarate = DR_0;
//     datarate = US915_TX_MIN_DATARATE;
    }
    return datarate;
}
```
I needed to define US915_TX_MIN_DATARATE as DR_1 (since my payload does not fit 11 bytes of DR0), but minimum datarate was not respected (by referred function) and packets were not transmitted.
I am using 4.4.0
Is this known issue?

**Comment by djaeckle** [comment]
Hi smartyboy,

thanks for your report. The reason why we didn't apply the definition `US915_TX_MIN_DATARATE` is that a switch between DR0 and DR4 is mandated by the LoRaWAN Specification for the join procedure.
