### ISSUE TITLE
AU915 ACMA regulation restriction removed in Regional Parameters v1.0.2rB

### ISSUE THREAD

**Issue by nestorayuso** [Lora-net/LoRaMac-node#451]
The Australian ACMA regulation requiring at least 20 125KHz channels in the old Regional Parameters v1.0.2(page 27, line 4) is removed in the new Regional Parameters v1.0.2rB. (basically because now AU915 is using in, not only Australia, but South America and more places)

But the ACMA regulation restriction is still present in the implementation https://github.com/Lora-net/LoRaMac-node/blob/v4.4.1/src/mac/region/RegionAU915.c#L390 and I think must be removed.

The LoRaMac-node v4.4.1 implementation suposed to be a { Release based on "LoRaWAN specification 1.0.2" and "LoRaWAN Regional Parameters v1.0.2rB"  } acording to https://github.com/Lora-net/LoRaMac-node/blob/v4.4.1/readme.md#2018-03-07-v441

**Comment by djaeckle** [comment]
Hi nestorayuso,

thanks for the report. We will double check it.
