### ISSUE TITLE
Send empty payload with port

### ISSUE THREAD

**Issue by Kamilcuk** [Lora-net/LoRaMac-node#455]
The LoRaWAN specification section 4.3.2. Frame Port specifies, that `If the frame payload field is not empty, the port field must be present.`. However, if payload field is empty, it is not specified if the port field must or must not be present. I am not sure how to interpret this, I think that when payload is empty, the frame port field is optional, may be present or may be not present in the packet.  
Currently port is not added to the message if payload is empty, see file https://github.com/Lora-net/LoRaMac-node/blob/master/src/mac/LoRaMac.c#L2275 , framePort is not added to LoRaMacBuffer the message is when LoRaMacTxPayloadLen == 0.   

Proposed solution:
When payload is empty, add port to the message only when the requested port number is different then zero.

            if( ( payload != NULL ) && ( LoRaMacTxPayloadLen > 0 ) )
            {
                LoRaMacBuffer[pktHeaderLen++] = framePort;

                if( framePort == 0 )
                {
                    // Reset buffer index as the mac commands are being sent on port 0
                    MacCommandsBufferIndex = 0;
                    LoRaMacPayloadEncrypt( (uint8_t* ) payload, LoRaMacTxPayloadLen, LoRaMacNwkSKey, LoRaMacDevAddr, UP_LINK, UpLinkCounter, &LoRaMacBuffer[pktHeaderLen] );
                }
                else
                {
                    LoRaMacPayloadEncrypt( (uint8_t* ) payload, LoRaMacTxPayloadLen, LoRaMacAppSKey, LoRaMacDevAddr, UP_LINK, UpLinkCounter, &LoRaMacBuffer[pktHeaderLen] );
                }
            } 
          + else 
          + {
          +    if ( framePort != 0 ) {
          +         LoRaMacBuffer[pktHeaderLen++] = framePort;
          +    }
          + }

This makes the assumption, that when frame port is equal to zero payload must not be empty, payload must contain MAC commands and none of MAC commands have an empty payload.   
This solution allows users to decide what they want to send: empty payload without port or empty payload with port.  
Existing code sending empty payload would need to be checked, if port is equal to 0.

**Comment by mluis1** [comment]
Our interpretation of the specification is that if there is no payload to be sent there is also no need to send the port number.

The current implementation is also more low-power friendly and for EU868 like regions it is duty-cycle friendly.

The transmission of 1 byte can have an high cost on the power consumption, this is true for highest spreading factors. For the duy-cycle computations the time to transmit an useless byte will increase the time to wait between transmissions.
