### ISSUE TITLE
SX126x's driver crashing radio chip in sniff mode

### ISSUE THREAD

**Issue by Atokulus** [Lora-net/LoRaMac-node#456]
https://github.com/Lora-net/LoRaMac-node/blob/1cdd9ccec4c9f05b616e7112059be4a9e358c571/src/radio/sx126x/sx126x.c#L113

After having received a package in sniff mode and processing the `IRQ_RX_DONE` interrupt, `SX126xWakeup()` is called even though the chip is already awake.

This results in the SX126x getting into an illegal state (the chip, not the driver), which has different strange & erroneous effects:

* Even though payload's size is correctly recognized in `SX126xGetPacketStatus()` (explicit header mode/variable length), the payload is only consisting of `0x24` (*$*) bytes. Consecutive register accesses return `0x24` (*$*) bytes as well.
* Putting the chip into Rx- or Sniff-mode afterwards might not work
* The `BUSY` signal might suddenly be staying high or toggling around fastly in a random way, even when there is no SPI transfer

To workaround this issue you can extend the code line referenced above:
```c
if( ( SX126xGetOperatingMode( ) == MODE_SLEEP ) || ( ( SX126xGetOperatingMode( ) == MODE_RX_DC && GpioRead( &SX126x.BUSY ) == 1 ) ) )
```

Please check whether you can reproduce this issue.

Cheers
@atokulus

**Comment by mluis1** [comment]
This question is of topic for this project. This project only concerns LoRaWAN protocol implementation.

Could you please ask your question on Semtech LoRa Community portal. Under collaborate page there is a specific forum for the SX126x devices. You may need to register first. [SX126x Forum](https://semtech.force.com/lora/_ui/core/chatter/groups/GroupProfilePage?g=0F944000000cCUc)

Thank you for your understanding.
