### ISSUE TITLE
appropriate value for rssiThresh when calling SX1276IsChannelFree(CN470 band)

### ISSUE THREAD

**Issue by topkinschen** [Lora-net/LoRaMac-node#459]
1,without reguard to other communication protocols running on the same frequency band of lora network, what is the appropriate(or best) value for rssiThresh when calling SX1276IsChannelFree,in order to realize LBT,?

2,considering other communication protocols running on the same frequency band of lora network, what is the appropriate(or best) value for rssiThresh when calling SX1276IsChannelFree,in order to realize LBT?
or do can you give some advice on how to select rssiThresh value of CN470 band?
need help on this.

**Comment by mluis1** [comment]
This value depends on your local RF regulations. I don't know what is the recommended value for CN470 region. If there is no recommendation you may use a value around -80 dBm.

The Japanese and Korean regulators specify a value of -85 dBm and -65 dBm respectively.
