### ISSUE TITLE
32 bit timer overflow with LoRaMacInitializationTime

### ISSUE THREAD

**Issue by GrumpyOldPizza** [Lora-net/LoRaMac-node#460]
In CalculateBackOff() "TimerGetElapsedTime( LoRaMacInitializationTime )" is used to  compute the elapsed time passed ultimately to  RegionCommonGetJoinDc().

That clearly wraps after about 49 days. So if a device tries to join via OTAA again after 49 days, it gets the wrong duty cycle. 

While this is perhaps just nitpicking, it will calculate the backoff wrong. If would seem reasonable to somehow add logic to CalculateBackOff() to use a upper limit for the elapsed time after say 7 days passed by ...

**Comment by mluis1** [comment]
You are right we need to update this.

The update should be easier with the recent addition of the systime.c/h module.
