### ISSUE TITLE
Non-spec compliant code with SRV_MAC_DUTY_CYCLE_REQ

### ISSUE THREAD

**Issue by GrumpyOldPizza** [Lora-net/LoRaMac-node#461]
The code should read:

            case SRV_MAC_DUTY_CYCLE_REQ:
                MaxDCycle = payload[macIndex++] & 0x0F;

And somewhere else the check for "MaxDCycle == 255" should be removed.

1.0.2 says explicitly that the upper 8 bits of the payload are RFU. The 255 check is a leftover form the ancient 1.0 spec.

**Comment by mluis1** [comment]
You are right. We will update it as soon as possible.
