### ISSUE TITLE
Default ChannelMask is not reset after a join procedure

### ISSUE THREAD

**Issue by f2ghazi** [Lora-net/LoRaMac-node#479]
I am currently working on the US915 band. 
Issue can be reproduced following these steps :
- Send some LinkAdrReq commands to set the device working only on the first 8 channels.
- Join the network again via a joinRequest/JoinAccept procedure.
- My device is still working on the 8 channels set before the join.

=> It should reset its channel mask during and after the join procedure (To match LoraWan certification).

**Comment by mluis1** [comment]
Which region setting are you using? (REGION_US915 or REGION_US915_HYBRID)
Have you made modifications to the original implementation?

The REGION_US915_HYBRID was a temporary US915 region implementation to ease the usage of 8 channels gateways. Nowadays the different network servers handle these gateways nicely.
Thus, if you are using the REGION_US915_HYBRID the behavior that you describe is normal.
Please note that we have removed this non official region implementation in the latest commits.

The LoRaWAN certification process has different tests that check this behavior and the REGION_US915 has passed successfully all the tests.

**Comment by daltonate** [comment]
I believe #511 should fix your problem # @f2ghazi, do you mind confirming ?
