### ISSUE TITLE
TimerGetCurrentTime() accumulation of time

### ISSUE THREAD

**Issue by ChrisEAlfred** [Lora-net/LoRaMac-node#480]
In the main loop on a STM32L07x port, I have code like:

~~~~code
    timertime_t timerNow = TimerGetCurrentTime();
    
    // Sometimes the seconds are not updated yet and time goes backwards
    if (_masterLastReadTime > timerNow)
    {
        // TIME WENT BACKWARDS    
    }
    _masterLastReadTime = timerNow;
~~~~

I have found that there are periods where the seconds (timerNow / 1000) have not changed and time goes backwards as the milliseconds continue to count from 0. 1 second later all is ok.

**Comment by ZuratonE** [comment]
It seems that actually, time goes forward for 1 s, when subseconds aren't updated.
See table:
```
seconds | subseconds | PREDIV_S
	43  |     0      | 2047 
    43  |     0      | 2047 
    44  |     0      | 2047 <- faulty place
    44  |  2047      | 2047 
    44  |  2047      | 2047                                                        

```

**Comment by ZuratonE** [comment]
I made following changes ( and it yet works for for me after ~12 hours of running your loop):

file _stm32l1xx_hal_rtc_ex.c_ function **HAL_RTC_GetTime**

```
...

#if defined(STM32L100xBA ...) 
  /* Get subseconds structure field from the corresponding register*/
  sTime->SubSeconds = (uint32_t)((hrtc->Instance->SSR) & RTC_SSR_SS);

  /* Get SecondFraction structure field from the corresponding register field*/
  sTime->SecondFraction = (uint32_t)(hrtc->Instance->PRER & RTC_PRER_PREDIV_S);

  // ========== ADD THIS 
  /* If shift is pending, set subseconds */
  tmpreg = (uint32_t)(hrtc->Instance->ISR & RTC_ISR_SHPF);
  if(tmpreg == 0){
	  sTime->SubSeconds = sTime->SecondFraction+1;
  }
  // ==========

#endif

...
```

**Comment by mluis1** [comment]
We will soon update the develop branch. We are finalizing some basic tests.

For this update we have completely refactored the RTC drivers, timer.c/h and we have added a systime.c/h module implementation with ST help.

We believe that with the new implementation these kind of issues aren't anymore present.

**Comment by ZuratonE** [comment]
I see two workarounds for this:
1 - do not use async prescaler. But this added ~0.5 mA in StopMode for my mcu.
2 - in **RtcGetCalendar()** in HAL_RTC_GetTime exit while loop only if subseconds!=0.

**Comment by ChrisEAlfred** [comment]
Does this affect the LoRa stack operation?

**Comment by ChrisEAlfred** [comment]
Unfortunately the drivers refactoring makes back porting tricky and risky.

Note that TimerGetCurrentTime() returns a rounded milliseconds time. If you are detecting time after TimerGetCurrentTime(), the error case is:

`
if (lastMs > currentMs && (lastMs / 1000 == currentMs / 1000)
{
    // Error case: time went backwards, but seconds stayed the same
}
`
