### ISSUE TITLE
AckTimeoutRetry issue

### ISSUE THREAD

**Issue by rohitkumar5293** [Lora-net/LoRaMac-node#481]
Hi,

I would like to check AckTimeoutRetry is for class A or class C. According to stack, functionalities of AckTimeoutRetry is for class C only, but when i check LoRa vendor they told AckTimeoutRetry is for all classes. 

Please confirm me AckTimeoutRetry  is for Class A or Class C

**Comment by mluis1** [comment]
AckTimeout retry is for ClassA only. Thus, each time an end-device send an uplink (ClassA) the AckTimeoutRetries are handled.

Please note that even if the end-device is operating in ClassB or ClassC all end-device uplinks are ClassA.
