### ISSUE TITLE
LinkADRReq NAKs when ADR is disabled

### ISSUE THREAD

**Issue by jamesl-dm** [Lora-net/LoRaMac-node#482]
In LoRaMAC.c:ProcessMacCommands() and RegionLinkAdrReq, the entire LinkADRReq is NAKed if any of the component parts are rejected. We've had queries from both Orange and Comcast about this behavior. They seem to expect the device to apply the channel mask, even if the power and datarate components are rejected due to the ADR being disabled.

The standard seems a bit ambiguous on this point. In Section 5.3, line 977 of the final 1.1 spec, it says (referring to the 3 status bits): "If any of those three bits equals 0, the command did not succeed and the node has kept the previous state.". This sound like the whole request should not be applied, and indeed this is what has been implemented. However, the language in the preceding table doesn't agree 100%. It says that if any of the individual accept / reject flags are set to accept, then the data rate was successfully set. Furthermore, the LoraMac-Node stack sets all of them to reject if the power / datarate are rejected due to ADR being disabled. Which begs the question, why are there 3 flags, if they will always take on the same value?

So I'd like to ask how confident you are that the implemented behavior is correct, so I know what to tell the compliance testers when they ask about this.

**Comment by mluis1** [comment]
The behavior when the ADR is disabled has been recently discussed by the Alliance technical committee. The outcome of the discussion is that the end-device must accept the channel mask modifications and ignore all other parameters.

Please refer to commit 734ab91 specifically the changes made on RegionCommon.c file.
