### ISSUE TITLE
Problem with channel selection in US915 Region

### ISSUE THREAD

**Issue by Adamzat** [Lora-net/LoRaMac-node#484]
Hi every one,

I'm using the Lora Stack v4.4.0. I have a question about the channel selection in US915.
Actually, the Join procedure is very long if we use a gateway supporting just 8 channels (which are the most used in US). 
The actual stack 4.4.0 and also 4.4.1 do the channel selection randomly in this function:

bool RegionUS915NextChannel( NextChanParams_t* nextChanParams, uint8_t* channel, TimerTime_t* time, TimerTime_t* aggregatedTimeOff )
{
.... *channel = enabledChannels[randr( 0, nbEnabledChannels - 1 )];
}
- I have done many tests and I have observed that the device transmits on each of the 8 sub bands using all the channels, but sometimes it can "reuse the same channel" that is used previously (in a block of 8)? These mechanism will enhance the time of the join, do you think that is normal? I think that the best would be to transmit on each of the 8 sub bands and not fully randomized across all 64.

-In the other hand, after joining the gateway, the device scans again all channels? Is it possible to change that, so the first uplink will be in the same bank of 8 as the successful Join-Request was?

Actually, that first uplink will have a high probability of allowing the network to send an immediate ADR command to set the appropriate channel mask.

Please, any one has faced that before. 
Thank you for your help.

**Comment by mluis1** [comment]
Commit e60bd86 implements the new algorithm defined by the [LoRaWAN Regional Parameters v1.1rB](https://lora-alliance.org/resource-hub/lorawantm-regional-parameters-v11rb)

The newly proposed algorithm is as follows:

> For rapid network acquisition in mixed gateway channel plan environments, the device SHOULD follow a random channel selection sequence which efficiently probes the octet groups of eight 125 kHz channels followed by probing one 500 kHz channel each pass. Each consecutive pass SHOULD NOT select a channel that was used in a previous pass, until a Join-request is transmitted on every channel, after which the entire process can restart. 
>
>Example:	 First pass: Random channel from [0-7], followed by [8-15]… [56-63], then 64 
                 Second pass: Random channel from [0-7], followed by [8-15]… [56-63], then 65 
                 Last pass: Random channel from [0-7], followed by [8-15]… [56-63], then 71 
>
>Personalized devices SHALL have all 72 channels enabled following a reset and shall use the channels for which the device’s default data-rate is valid.
