### ISSUE TITLE
SX126x's RADIO_SET_TXCONTINUOUSPREAMBLE (infinite preamble) sends payload buffer first

### ISSUE THREAD

**Issue by Atokulus** [Lora-net/LoRaMac-node#485]
Executing the RADIO_SET_TXCONTINUOUSPREAMBLE (infinite preamble mode) on the SX126x, a complete valid LoRa frame with the latest configured payload will be sent before the Radio actually switches into Infinite Preamble mode:

```c
SX126xWriteCommand(RADIO_SET_TXCONTINUOUSPREAMBLE, 0, 0 );
````

![infinite_preamble_bug](https://user-images.githubusercontent.com/1159506/41419227-d0b417ae-6ff1-11e8-85ed-c7f00e78bd47.PNG)

This behaviour should not be expected.

Best regards
@atokulus

**Comment by mluis1** [comment]
This question is of topic for this project. This project only concerns LoRaWAN protocol implementation.

Could you please ask your question on Semtech LoRa Community portal. Under collaborate page there is a specific forum for the SX126x devices. You may need to register first. [SX126x Forum](https://semtech.force.com/lora/_ui/core/chatter/groups/GroupProfilePage?g=0F944000000cCUc)

Thank you for your understanding.
