### ISSUE TITLE
SX126x's SetRxDutyCycle (listen/sniff-mode) is glitching in FSK mode

### ISSUE THREAD

**Issue by Atokulus** [Lora-net/LoRaMac-node#486]
Putting the SX126x into listen/sniff-mode, while being configured **for FSK** reception, the chip goes into a corrupted state after a while (1ms - 1s) where the BUSY line shows many glitchy HIGH spikes. Depending on the Rx & Sleep period, the spikes can be very densy and randomly distributed.  PreambleDetected is not triggered, and LoRa listen/sniff-mode is working fine.

```c
Radio.SetRxDutyCycle(rx, sleep);
```

![tek00000_li](https://user-images.githubusercontent.com/1159506/41420325-76909006-6ff4-11e8-9565-a97d1fa79f90.jpg)

**Comment by mluis1** [comment]
This question is of topic for this project. This project only concerns LoRaWAN protocol implementation.

Could you please ask your question on Semtech LoRa Community portal. Under collaborate page there is a specific forum for the SX126x devices. You may need to register first. [SX126x Forum](https://semtech.force.com/lora/_ui/core/chatter/groups/GroupProfilePage?g=0F944000000cCUc)

Thank you for your understanding.
