### ISSUE TITLE
I-CUBE-LRWAN STM32 MCU freezes at Lora_Init(), need help!

### ISSUE THREAD

**Issue by benjaminlhind** [Lora-net/LoRaMac-node#494]
Hi,

I have the STM Nucleo L452RE Board with the SX1276MB1MAS DevKit.
I created the Project with STM32CubeMX and added the I-CUBE-LRWAN LoRaWAN Stack (Based on LoRaMac from Stackforce) to it.
The Project is now compiling fine without errors, but if I execute the LORA_Join() Method, the complete MCU freezes (also in Debugging) in the function Radio.Init( &RadioEvents ); in LoRaMac.c line 2533. 

Then the SX1276Init( RadioEvents_t *events ) is called in sx1276.c. In the end the MCU freezes exactly at line 286 in sx127.c at SX1276SetModem( MODEM_FSK );

How can this happen? SPI works well, the other functions like SX1276Write and SX1276Read are working.

If I replace SX1276SetModem(MODEM_FSK); to SX1276SetModem(MODEM_LORA); everythings works. But if I reset the CPU with the reset button, the cpu freezes every second reset.... So Its not working stable.

What am I doing wrong? I work with the I-CUBE-LRWAN in Version V1.1.5.

Thanks in advance!

**Comment by mluis1** [comment]
Could you please post your question on ST forums?

This question is related to the I-CUBE-LRWAN which is a port of this project. ST are the right people to ask for support on this.
