### ISSUE TITLE
Lora CSMA/CA supported?

### ISSUE THREAD

**Issue by jackshu** [Lora-net/LoRaMac-node#50]
how does LoraWAN MAC support CSMA/CA management?

**Comment by mluis1** [comment]
Currently the LoRaWAN specification doesn't specify any CSMA/CA management.
The specification states the following:

> In order to access the physical medium the ETSI regulations impose some restrictions such maximum time the transmitter can be on or the maximum time a transmitter can transmit per hour. The ETSI regulations allow the choice of using either a duty-cycle limitation or a so called Listen Before Talk Adaptive Frequency Agility (LBT AFA) transmissions management. The current LoRaWAN specification exclusively uses duty-cycled limited transmissions to comply with the ETSI regulations.

It means that it is currently a pure ALOHA management.
