### ISSUE TITLE
LBT RSSI threshold isn't adjusted for antenna gain

### ISSUE THREAD

**Issue by jamesl-dm** [Lora-net/LoRaMac-node#502]
The LBT thresholds are read directly from the modem's RSSI register, and compared to the region's specified value. Shouldn't they be modified for antenna gain to give an accurate result?

**Comment by GuntherSchulz** [comment]
The RSSI value is what the radio module physically sees after all hardware in the chain, so I'm guessing no

**Comment by jamesl-dm** [comment]
If you have a very inefficient antenna, and it reads an artificially low value, you shouldn't be allowed to transmit just because you _thought_ the channel was quiet. Only if it really is quiet.

**Comment by GuntherSchulz** [comment]
Your point is well made. The converse is also true. A super-high gain antenna will result in "seeing" a string signal, even though that which is on air is truly weaker.
The region specs couldn't care less what you/your device THINKS, they care about what actually IS ON AIR.

Changing my answer above, I now strongly agree with you.
+1

**Comment by mluis1** [comment]
The provided thresholds are the values provide by the national regulators specifications.

If you want to take in account the RF path gains/losses you can do so. If in the end your device gets the specific national regulator approval then your are safe.

**Comment by jamesl-dm** [comment]
I can't claim to have read the Korean specification, or whichever harmonized spec the AS923 numbers come from. But I know in EN 300 220, when they specify an LBT threshold, it is supposed to be adjusted:
![image](https://user-images.githubusercontent.com/28915246/42212454-beb748fe-7ee8-11e8-8e08-2c4b31dcadce.png)
I'd have expected other specs to do the same thing.

**Comment by GuntherSchulz** [comment]
@mluis1 The point here is that the regulator don't know / probably can't measure your entire RF signal chain, so the only sensible point to measure is at the AIR interface.

**Comment by mluis1** [comment]
As already said you are free to change the behavior/values as soon as you respect and are able to pass the national regulations.

On this project by default we take the values provided by the specifications. There is no way for us to provide a value that will suit all RF implementations.

The "ARIB STD-T108 Version 1.0 920 MHz band - Telemeter, Telecontrol and Data Transmission Radio Equipment" specification says something like the following:

>Carrier sense
A carrier sense procedure shall be performed before transmitting on a radio channel. It shall be able to
determine the presence of RF power on the radio channel (one or more) at a level of at least **-80 dBm**.
In that case, the channel is considered occupied and shall not be used for transmission.
The analysis duration shall be at least 5 ms for the channels 24 to 38.

The Korea TTAK.KO-06.0246 "900 MHz Physical Layer (PHY) Specification for Low-Rate Wireless
Personal Area Networks (LR-WPANs)" specification says something like the following:
>The receiver shall implement a listen before talk mechanism that comply with the following rules:
> - A carrier sense mechanism shall be able to determine the presence of RF power on the radio
channel (one or more) at a level of at least **-65 dBm**. 
> - It shall be performed for at least 5 ms.
> - The emission time shall be lower than 4 s.
> - Finally, two consecutive emissions shall be separated by at least 50 ms.

**Comment by jamesl-dm** [comment]
Ok - thanks
