### ISSUE TITLE
Why default data rate range is between DR_0 and DR_5 in applying CFList? Why not something liku XXXX_TX_MIN_DATARATE and XXXX_TX_MAX_DATARATE?

### ISSUE THREAD

**Issue by MaheshKumarPN** [Lora-net/LoRaMac-node#516]
I see form the RegionXXXX.c files that RegionXXXXApplyCFList() api definition has default data rate to be DR_0 and DR_5 hard coded.
Do we have a way now to update them form application context?
Do we have any future plan to move it to application context?

or Am i missing something?

**Comment by mluis1** [comment]
The 3 default channels are defined with a range between DR_0 to DR_5.
For EU868 the regional parameters (LoRaWAN Regional Parameters v1.0.3rA) table 3 shows this:

![image](https://user-images.githubusercontent.com/5763295/43121249-68c6a3dc-8f1d-11e8-8286-0b4329ff3ef4.png)

Please note that it is up to the network server to then instruct the end-device to enable the upper datarates.

The NewChannelReq MAC command provides the way to change the datarate range. (LoRaWAN Specification v1.0.3)

![image](https://user-images.githubusercontent.com/5763295/43121415-fd7edc38-8f1d-11e8-9743-be8f7fdc0ddf.png)

**Comment by mluis1** [comment]
I forgot to mention that the DR_6 and DR_7 datarates use a specific modems on the SX1301. These modems have independent channel frequencies parameters.

This means that there is no way for an end-device to figure out which frequencies are being used. This is one of the reasons why the Network Server must create/change the channels on the end-device.
