### ISSUE TITLE
 SK-iM880A debugging 

### ISSUE THREAD

**Issue by yoniwt** [Lora-net/LoRaMac-node#519]
As I can see from the documentation, currently, the project supports  debugging for LoRaMote, MoteI, SAML21. Any  recommendation for debugging SK-iM880A/B?

Thank you in advance

**Comment by mluis1** [comment]
All platforms support debugging.

For the SK-IM88xx platforms you must use for example a [ST-Link](https://www.st.com/en/development-tools/st-link-v2.html) and then connect the wires to the right places on the Starter Kit.

Please refer to the [SK-iM880B - Long Range Radio Starter Kit](https://wireless-solutions.de/products/starterkits/sk-im880b.html) documentation.
