### ISSUE TITLE
ADR_ACK_LIMIT & ADR_ACK_DELAY 

### ISSUE THREAD

**Issue by heroichornet** [Lora-net/LoRaMac-node#522]
LoRaWAN Spec 1.0 says for example for EU868 Regio: 

#define EU868_ADR_ACK_LIMIT                         64
#define EU868_ADR_ACK_DELAY                       32

For LoRaWAN Spec 1.1 there are MAC commands to change these parameters.

My question is, may an end-device change these parameters on his own when using LoRaWAN Spec 1.0

For example: when transmitting X Uplinks per day I would like ACK_LIMIT to be X and ACK_DELAY to be X aswell. (X = 96, 24 or 1 )

**Comment by djaeckle** [comment]
Hi heroichornet,

thanks for your report. Please see the related description in the specification LoRaWAN 1.0.3 Regional Parameters (ref B), chapter 2.2.9:

> If the actual parameter values implemented in the end-device are different from those default values (for example the end-device uses a longer RECEIVE_DELAY1 and RECEIVE_DELAY2 latency), those parameters MUST be communicated to the network server using an out-of-band channel during the end-device commissioning process. The network server may not accept parameters different from those default values.

**Comment by heroichornet** [comment]
Thank you
