### ISSUE TITLE
Only one of a multiple sticky MAC Response cleared on reception of a class A downlink

### ISSUE THREAD

**Issue by ConnyBusy** [Lora-net/LoRaMac-node#529]
Hi,
I am using the current development branch here.
if a Node has more than one sticky Mac Responses in it's FOpts field or Frame Payload field and receives a class A downlink only one of them is cleared. Is this a bug??. I would expect the MAC buffer to be cleared. See example below:

UL 1:  40:9F:24:82:00:84:1D:01:_**0A:00:0A:00**_:E0:1B:41:37:3D:67:D0 Here 2 sticky DlChannelRespone
DL 1:  60:9F:24:82:00:00:21:00:E0:B0:71:08:E4:F6:50:23:4D:7E
UL 2:  40:9F:24:82:00:82:1E:01:_**0A:00**_:E0:D0:EB:B8:11:83:11:D4:97:01 Here 1 sticky DlChannelRespone
DL 2:  60:9F:24:82:00:00:22:00:E0:46:88:F5:A4:CD:FE:01:9E:B2
UL 3:  40:9F:24:82:00:80:1F:01:E0:CB:08:78:4F:90:5B:7F:79:B6 Here no sticky DlChannelRespone

**Comment by djaeckle** [comment]
Hi ConnyBusy,

thanks for your report. I think this is an issue. We will apply it to the next milestone.
