### ISSUE TITLE
RegionAU915 Default Dwell Time

### ISSUE THREAD

**Issue by DominusFulguris** [Lora-net/LoRaMac-node#531]
I have had problems getting my node to accept a new channelmask as part of an ADR command from the gateway.

The problem is the channel mask is being rejected because the gateway had specified a minimum DR_0 but the node wanted DR_2 as a minimum.  I found that this was caused indirectly by the following in RegionAU915.h

#define AU915_DEFAULT_UPLINK_DWELL_TIME             1

Looking at the regional parameters specifications (1.02, 1.03, 1.1), there is no mention of dwell being required for AU915.

By rejecting the channel mask from the gateway, the node continues to transmit on all channels, resulting in an average 7 out of 8 packets being lost.  The problem is resolved by setting the default uplink dwell time to zero.

**Comment by jamesl-dm** [comment]
News to me too - but does seem to be in the 1.1rB regional params:

![image](https://user-images.githubusercontent.com/28915246/44251223-30737800-a22a-11e8-8ec8-9a3dc7ff4981.png)

**Comment by jamesl-dm** [comment]
Its going to be a bit of a parameter soup trying to support both old and new region definitions in commercial devices... Thankfully everyone here seems to be switching to AS923. TTN is still on the original AU915 though.

**Comment by DominusFulguris** [comment]
Ok, so what appears to be happening is that the LinkADRReq from the server is being received with the correct channel mask and a requested data rate DR0.

Because the UplinkDwellTime=1, the Tx data rate is DR2.  This is causing the channel mask in the LinkADRReq to be tossed out by RegionCommonLinkAdrReqVerifyParams().

I think what perhaps should be happening is the data rate used for ADR just needs to be the greater of the two.

Without something like this, ADR seems to be failing and the node keeps transmitting data across the entire band.

If ADR is turned off, it all seems to work as expected with a correct TxParamSetupReq  being processed.

Gateway/Network server is Multitech Conduit AP (LoRaWAN 1.0.2rB)
Node is ST B-L072Z-LRWAN1 running LoRaWAN 1.0.3 (STM32Cube Expansion for LoRaWAN 1.20)

**Comment by DominusFulguris** [comment]
Opening this as a new issue based on updated analysis.

**Comment by aoyarce** [comment]
This is the spec for Lora 1.0.3 for the Dwell uplink time;
this is the reason why it wont work for DR_0  or DR_1 using dwell time uplink to 1:

![imagen](https://user-images.githubusercontent.com/47367518/68312142-5e441700-0091-11ea-9201-6d4bdbe3a898.png)
