### ISSUE TITLE
DutyCycleEnabled not checked for AU915 region ?

### ISSUE THREAD

**Issue by la-urre** [Lora-net/LoRaMac-node#534]
Hello

It appears to me that the `DutyCycleEnabled` variable should be checked in the following branch of the code:

https://github.com/Lora-net/LoRaMac-node/blob/a390fe6b38ff84e702ea13411294f2cf6005350d/src/mac/region/RegionAU915.c#L914

Shouldn't the `delayTx` and `nextTxDelay` be assigned only if `DutyCycleEnabled` is `true` ? Or am I missing something ?

I don't know how this is for other regions but maybe a similar change is required.

I can contribute if you feel the fix is pertinent.

**Comment by djaeckle** [comment]
Hi laurre,

thanks for your report. The aggredated transmit duty cycle is independent from the region specific implementation. Its defined by the MAC and provides the possibility for a network server to manage it via the command DutyCycleReq/Ans.
