### ISSUE TITLE
Opening Class C Rx window between Tx and Rx1 can lead to lost packets

### ISSUE THREAD

**Issue by reissjason** [Lora-net/LoRaMac-node#541]
If a packet is received between Tx and Rx1 when the device is in Class C mode, it may not be possible to then open the Rx1 window depending on the length of the received Class C packet and where the beginning of the packet occurs in the delay.

With sufficient Class C packets being transmitted from various gateways within range of a device, the Rx1 window will be unstable for Class C devices.

**Comment by jamesl-dm** [comment]
From the 1.1 spec, section 17:

> Note: If the device is in the process of demodulating a downlink using the RX2 parameters when the RX1 window should be opened, it shall drop the demodulation and switch to the RX1 receive window

Haven't checked if loramac-node actually does this, but that's how its supposed to work.

**Comment by reissjason** [comment]
When Rx1 timer fires the radio is put into sleep mode which will drop any current packet being received. Then the Rx1 window is opened. Looks like the code is correct, it just wasn't described in the spec.

Looks like 1.0.3 and 1.1 spec has incorporated this text.

**Comment by Adamzat** [comment]
Hi reissjason, 
What Lora Stack you are using. I observed this issue in Lora Stack 4.4.0 (spec 1.0.2)?
