### ISSUE TITLE
randr called with max = -1

### ISSUE THREAD

**Issue by pblach** [Lora-net/LoRaMac-node#550]
The below function is called at one point when availableChannels = 0, so it calls randr with that being set to -1.
*newChannelIndex = findAvailableChannelsIndex[randr( 0, ( availableChannels - 1 ) )];

min = 0, max = -1:
int32_t randr( int32_t min, int32_t max )
{
    return ( int32_t )rand1( ) % ( max - min + 1 ) + min;
}

Naturally this crashes the program.

**Comment by mluis1** [comment]
Thanks for the report. 

We think that PR #511 should fix this issue. We will merge this PR as soon as possible.

**Comment by djaeckle** [comment]
Hi pblach,

this issue should be fixed with the merge of pull request #511 f75c97433b97a411164202cb19c5cc0566b0bfe7.
