### ISSUE TITLE
Not able to get UART data on NUCLEO-L073RZ + SX1272 mbed shield

### ISSUE THREAD

**Issue by vyas-sourabh** [Lora-net/LoRaMac-node#553]
Greetings to all,
I'm new with this development board. i download the I-CUBE- LRWAN for end node creation on NUCLEO-L073RZ + SX1272 mbed shield. i tried to get the log and other data over UART and send the data via USB to TTL dongle over termite or docklight. i tried all the UART pin in the development board but i'm not getting anything. please help me.
Thanks in advance

**Comment by mluis1** [comment]
The i-cube-lrwan is a fork of this project done by ST.

Could you please redirect your questions to ST?

Thanks.
