### ISSUE TITLE
Failed Join Request

### ISSUE THREAD

**Issue by coljander** [Lora-net/LoRaMac-node#56]
What is the philosophy when a Join Request fails?  At the moment we get no feedback from the code which places the onus on us to place a timer in our code to wait for the 10 or so seconds to see id the Join Accept message has been received.

Would it not be better for the RxTimeout message to be routed out as in indication of the failed attempt?  In the MlmeConfirm() function the LoRaMacEventInfo.Status never gets set to the correct state as it only gets set if the mlmeConfirm->Status is equal to  LORAMAC_EVENT_INFO_STATUS_OK.  Which as the attempt has failed it hasn't been set to this value.

If I add code along the line of 

    if( mlmeConfirm->Status == LORAMAC_EVENT_INFO_STATUS_OK )
   {
     '''
    }
    else
    {
        if (mlmeConfirm->MlmeRequest == MLME_JOIN)
        {
            LoRaMacEventInfo.Status = mlmeConfirm->Status;
        }
    }

I get the Timeout event and I can deal with the failure.

However this raises another problem.  If I do add this code and get the timeout and use this to send another JoinRequest, the transmission time is calculated using a duty cycle of 1%.  But the spec states that the "JoinReq message transmit duty-cycle should never exceed 0.1%".  So we would be breaking the spec.  In this instance are we expected to handle the duty cycle calculations ourselves?

**Comment by djaeckle** [comment]
Hi coljander,

thanks for your report. I guess you are using the v3 wrapper. I think the demo-app provides re-join attempts - but it is correct, that the wrapper does not set `LoRaMacEventInfo.Status` in case of an error. We will provide an update on the develop branch.

Regarding the duty cycle, your statement is also correct. We will provide an update on the develop branch, as soon as we have a solution.

Please note, that we will stop the support for the v3 wrapper not later than version 5.0.0. For more information on next releases, please take a look in the wiki.
