### ISSUE TITLE
Class C on WiMOD SK-iM880A with CoIDE acts like Class A

### ISSUE THREAD

**Issue by Crossfire60** [Lora-net/LoRaMac-node#57]
While testing my SK-iM880A I found two issues:

1. (minor)
The project file includes the classA "main.c" in stead of the classC "main.c".

2. (major)
While using the Class C mode I find that the device acts like a Class A device. The device only sets LED3 afters first sending data. And when sending data from the basestation, the basestations shows "active" and when the data is sent, "Try1". This implies that the end-device does not send a "ACK". When the end device sends new data, the status is set to "Success".

I am using the Kerlink LoRa IoT Station 868 with SPN software.

**Comment by pdemil** [comment]
When the end device sends new data, it includes the ACK of the previous received downlink message (from basestation to end device) that requested confirmation. So that is why you see the "Success" message only when the end device sends new data.

**Comment by Crossfire60** [comment]
It seems that the SPN software on base station doesn't support Class C devices yet (finally got the answer from the customer service). Thanks for the reply.
