### ISSUE TITLE
Bug in RtcSetAlarm

### ISSUE THREAD

**Issue by simonnilsson** [Lora-net/LoRaMac-node#570]
One of the latest commits to fix compiler warnings broke the RTC-code, when setting a longer timeout the mcu may now get stuck in a non-sleep state.

Offending code in RtcSetAlarm:
```
    if( ( MIN_ALARM_DELAY + McuWakeUpTimeCal ) < ( int16_t )( timeout - RtcGetTimerElapsedTime( ) ) )
```

Specifically it's the cast to **int16_t** here, both timeout and RtcGetTimerElapsedTime are uint32_t and these can overflow several times in a int16_t. 

I recommend casting it to int64_t as that should be safe.

**Comment by mluis1** [comment]
Thanks for the report.

We will propose an update as soon as possible.
