### ISSUE TITLE
AS923 rejoin command does not reset RX frequencies

### ISSUE THREAD

**Issue by psuggate** [Lora-net/LoRaMac-node#591]
**Problem:** Once an end-device has reconfigured its (asymmetric) up/down channels on our AS923 network, then subsequent rejoin attempts (e.g., via `AT+JOIN`) fail for these devices. And when using an AT modem interface, there is no method to bring the devices back to a known state without issuing a reset; i.e., `ATZ`. The cause seems to be that the rejoin code does not reset the `LC1` and `LC2` Rx channels.

**More info:** After initially joining, via `AT+JOIN`, and receiving a CFList with 5 new channels, followed by channel-configuration MAC commands:

 + `RXParamSetupReq`
 + `NewChannelReq`
 + 8x `DlChannelReq`

with the appropriate `xxAns` commands, the device is now configured to use `LC1-8` for uplinks and `LC127-134` for downlinks. Now, if this is followed by issuing `AT+JOIN`, then the device fails to rejoin to the AS923 network.

The gateway receives the `JoinRequest` and then sends a `JoinAccept`, but the end-device (STM Discovery B-L072Z-LRWAN1 with the *AT_Slave* application/firmware) appears to be listening on the wrong channel, and does not receive the message.

**Fix:** modifying `region/RegionAS923.c` (in the `Middlewares/Third_Party/LoRaWAN/Mac` subdirectory of the current release of the `en.i-cube_lrwan.zip` firmware) to properly reset the `LC1` & `LC2` downlink frequencies fixes the problem. Such a change is given in the following code (`line 386` of `RegionAS923.c`):

```C
void RegionAS923InitDefaults( InitDefaultsParams_t* params )
{
    Band_t bands[AS923_MAX_NB_BANDS] =
    {
        AS923_BAND0
    };

    switch( params->Type )
    {
        /* NOTE: the original code does not restore the default channels if
             the channels have been configured to use asymmetric uplink and
             downlink frequencies */
        case INIT_TYPE_INIT:
        case INIT_TYPE_RESTORE_DEFAULT_CHANNELS: /* ADDED */
        case INIT_TYPE_APP_DEFAULTS:             /* ADDED */
        {
            // Initialize bands
            memcpy1( ( uint8_t* )NvmCtx.Bands, ( uint8_t* )bands, sizeof( Band_t ) * AS923_MAX_NB_BANDS );

            // Channels
            NvmCtx.Channels[0] = ( ChannelParams_t ) AS923_LC1; //  <-- IMPORTANT
            NvmCtx.Channels[1] = ( ChannelParams_t ) AS923_LC2; //  <-- IMPORTANT

            // Initialize the channels default mask
            NvmCtx.ChannelsDefaultMask[0] = LC( 1 ) + LC( 2 );
            // Update the channels mask
            RegionCommonChanMaskCopy( NvmCtx.ChannelsMask, NvmCtx.ChannelsDefaultMask, 1 );
            break;
        }
        case INIT_TYPE_RESTORE_CTX:
        {
            if( params->NvmCtx != 0 )
            {
                memcpy1( (uint8_t*) &NvmCtx, (uint8_t*) params->NvmCtx, sizeof( NvmCtx ) );
            }
            break;
        }
    /* REMOVED
        case INIT_TYPE_RESTORE_DEFAULT_CHANNELS: ...
        case INIT_TYPE_APP_DEFAULTS: ...
    */
        default:
        {
            break;
        }
    }
}
```

The rejoin code calls the `RegionAS923InitDefaults` function with:

    params->Type == INIT_TYPE_APP_DEFAULTS             /* STM, or */
    params->Type == INIT_TYPE_RESTORE_DEFAULT_CHANNELS /* Lora-net */

which (pre-fix) did not restore the first & second receive channels to `LC1` & `LC2`.

While the firmware was built from the sources included in the STMicroelectronics `en.i-cube_lrwan.zip` distribution, it appears that the code in this repository will have the same problem?

**Comment by sparkiot** [comment]
This bug affects quite a few customers on our nationwide LoRaWAN network, and we'd like to help get this patched. What would any of the developers recommend for getting this fix included in the source-code, and ideally with the fix that was given in [issue #614](https://github.com/Lora-net/LoRaMac-node/issues/614) as well?

I haven't put together a proper patch, and pull request, because I have not had time to see if this issue affects other regions, and therefore whether they need patching also. The fix above does change the behaviour, so it should probably be:

```C
void RegionAS923InitDefaults( InitDefaultsParams_t* params )
{
    Band_t bands[AS923_MAX_NB_BANDS] =
    {
        AS923_BAND0
    };

    switch( params->Type )
    {
        case INIT_TYPE_INIT:
        {
            // Initialize bands
            memcpy1( ( uint8_t* )NvmCtx.Bands, ( uint8_t* )bands, sizeof( Band_t ) * AS923_MAX_NB_BANDS );

            // Channels
            NvmCtx.Channels[0] = ( ChannelParams_t ) AS923_LC1;
            NvmCtx.Channels[1] = ( ChannelParams_t ) AS923_LC2;

            // Initialize the channels default mask
            NvmCtx.ChannelsDefaultMask[0] = LC( 1 ) + LC( 2 );
            // Update the channels mask
            RegionCommonChanMaskCopy( NvmCtx.ChannelsMask, NvmCtx.ChannelsDefaultMask, 1 );
            break;
        }
        case INIT_TYPE_RESTORE_CTX:
        {
            if( params->NvmCtx != 0 )
            {
                memcpy1( (uint8_t*) &NvmCtx, (uint8_t*) params->NvmCtx, sizeof( NvmCtx ) );
            }
            break;
        }
        case INIT_TYPE_RESTORE_DEFAULT_CHANNELS:
        {
            // Restore channels default mask
            NvmCtx.ChannelsMask[0] |= NvmCtx.ChannelsDefaultMask[0];

            // Channels
            NvmCtx.Channels[0] = ( ChannelParams_t ) AS923_LC1; //  <-- NEW
            NvmCtx.Channels[1] = ( ChannelParams_t ) AS923_LC2; //  <-- NEW
            break;
        }
        default:
        {
            break;
        }
    }
}
```
