### ISSUE TITLE
move function LoRaMacCheckForBeaconAcquisition from LoRaMac.c to LoRaMacClassB.c

### ISSUE THREAD

**Issue by nestorayuso** [Lora-net/LoRaMac-node#595]
I think we should move LoRaMacCheckForBeaconAcquisition from LoRaMac.c to LoRaMacClassB.c and use #ifdef LORAMAC_CLASSB_ENABLED statement to reduce code if class-B is not enabled at compile time.

**Comment by mluis1** [comment]
Thanks @nestorayuso, we will do it as soon as possible.

**Comment by nestorayuso** [comment]
The #ifdef LORAMAC_CLASSB_ENABLED statement can be used inside LoRaMac.c to reduce more code, and maybe a #ifdef LORAMAC_CLASSC_ENABLED statement to remove class-c code and multicast code.

Upgrading from v4.4.1 to v4.4.2 the code size increased a lot.

**Comment by djaeckle** [comment]
Hi nestorayuso,

we will not move it for now, as it has some dependencies to the LoRaMac.c. However, we will consider it for the future.
