### ISSUE TITLE
Missing code in RegionRU864.c

### ISSUE THREAD

**Issue by sergug** [Lora-net/LoRaMac-node#596]
In the RegionRU864.c  in the function  PhyParam_t RegionRU864GetPhyParam
for some reason the following code is missing, but it is present in all other regional files RegionXXXXX.c

```
case PHY_MAX_FCNT_GAP:
         {
             phyParam.Value = RU864_MAX_FCNT_GAP;
             break;
         }
```

Node cannot correctly handle downlink frames without this code

**Comment by mluis1** [comment]
We will correct this as soon as possible.
