### ISSUE TITLE
Minimum active channels in 915 band

### ISSUE THREAD

**Issue by Mobiak** [Lora-net/LoRaMac-node#60]
Is there a minimum channels to be active for a device in 915 MHz ?

For a device in USE_BAND_915_HYBRID I got Channel mask KO when the gateway send a SRV_MAC_LINK_ADR_REQ with only three channels to activate.

After investigation the code responsible is in the function ProcessMacCommands(), checking if there is at least 6 channels enabled.

```
                        if( CountNbEnabled125kHzChannels( channelsMask ) < 6 )
                        {
                            status &= 0xFE; // Channel mask KO
                        }
```

**Comment by mluis1** [comment]
As per FCC rules the end-device must hop on at least six 125 kHz channels.
The hybrid mode follows the same exact rules as the 64 channels mode. 
The hybrid mode is just a way to be able to use a 8 channels gateway on the US915 band.
