### ISSUE TITLE
SX126x CalibrateImage data differes between code and datasheet

### ISSUE THREAD

**Issue by alex00971** [Lora-net/LoRaMac-node#601]
Hi

When calling command "CalibrateImage"
For freq 868Mhz , Base on datasheet, this Number should be 0xDB , but in SX126x.c, this code is 0xD8
![image](https://user-images.githubusercontent.com/9721014/49447003-dc979980-f7ee-11e8-83bd-5a1ed8daff52.png)
![image](https://user-images.githubusercontent.com/9721014/49447118-284a4300-f7ef-11e8-83f3-6610de5d3bc8.png)

Which one is correct ?
I think the correct one is in Datasheet. DB.

**Comment by mluis1** [comment]
Value 0xDB is the correct value. We will provide a fix as soon as possible.
