### ISSUE TITLE
Timer objects and scheduling management

### ISSUE THREAD

**Issue by yanxicheung** [Lora-net/LoRaMac-node#61]
Hello,I have difficulty in understanding scheduling management.Can you explain it to me,and I want to know what documents should I refer to.Thank you very much.My Email is :danielzpp@163.com.

**Comment by mluis1** [comment]
Unfortunately there is no documents where to refer to.

Mainly the Timers are managed using a sorted link list where the head of the list is the next timer to expire.

**Comment by yanxicheung** [comment]
Thank you all the same.
