### ISSUE TITLE
What about first tutorial?

### ISSUE THREAD

**Issue by AlessandroSpallina** [Lora-net/LoRaMac-node#611]
Hello, i have 2 stm nucleo pack with the lora mbed board.
I need to deploy my first network, i am unable to understand how to make the thing work and check that is really running.

If i compile the binary with the mbed compiler (ide), the browser version, i see the ping pong; but i do the same with cmake directly from the forked code of this repository, after the flashing of the firmware in my serial monitor cutecom i am unable to see any message of ping/pong. What's wrong with ping-pong??

And, i want to make a gateway and a node, this node need to randomize number do uplink to the gateway, i don't understand..

Thanks

**Comment by mluis1** [comment]
The ping-pong example on this project doesn't print anything on the UART. It just blinks LEDs.

The LoRaWAN examples currently use 921600 bits/s as bit rate for the UART.
