### ISSUE TITLE
One more missing code in RegionRU864.c

### ISSUE THREAD

**Issue by sergug** [Lora-net/LoRaMac-node#615]
In the RegionRU864.c in the function PhyParam_t RegionRU864GetPhyParam
for some reason the following code is missing, but it is present in all other regional files RegionXXXXX.c

```
case PHY_MAX_TX_POWER:
        {
            phyParam.Value = RU864_MAX_TX_POWER;
            break;
        }
```

**Comment by mluis1** [comment]
Fixed with commit 55d4f4cde3b07b8a92465b63575d89d07037e8ef.
The commit message references the wrong issue.
