### ISSUE TITLE
Question about the SX126xReset funtion

### ISSUE THREAD

**Issue by Lozeonjyu** [Lora-net/LoRaMac-node#616]
Hi,

I am using the Nucleo L073+Sx1261 shield to load the code. During the code reading, I find something that confuses me a little bit. 

In the file sx1261mbxbas-board.c, it introduces the sx126x reset function:
```
void SX126xReset( void )
{
    DelayMs( 10 );
    GpioInit( &SX126x.Reset, RADIO_RESET, PIN_OUTPUT, PIN_PUSH_PULL, PIN_NO_PULL, 0 );
    DelayMs( 20 );
    GpioInit( &SX126x.Reset, RADIO_RESET, PIN_ANALOGIC, PIN_PUSH_PULL, PIN_NO_PULL, 0 ); // internal pull-up
    DelayMs( 10 );
}
```

It seems like the micro drives the reset pin low and let the reset pin go back, but why it initializes again as analog rather than just writegpio 1 to the reset pin? And why setting the pin analogic can let the reset pin go back high again?

Thanks

**Comment by abrinlee** [comment]
Just clarifying... 

The questions is why the use of PIN_ANALOGIC (Which I believe makes it an analog input pin) for the GPIO pin type instead of PIN_OUTPUT and then set back to a "1".

**Comment by mluis1** [comment]
The radio reset pin has an internal pull-up. 
Thus, in order to avoid the MCU driving a 1 we just set the pin as input.

**Comment by abrinlee** [comment]
Thank you for responding. I appreciate the follow up. Close the issue.
