### ISSUE TITLE
Questions for target compile definitions

### ISSUE THREAD

**Issue by outely** [Lora-net/LoRaMac-node#623]
Hi!
At develop\src\mac\CMakeLists.txt  line52:
`target_compile_definitions(${PROJECT_NAME} PUBLIC -D"${REGION}")`

Whether it needs to be changed to `target_compile_definitions(${PROJECT_NAME} PUBLIC -D${REGION})`

**Comment by mluis1** [comment]
CMake accepts the 2 ways. We don't think it is necessary to change it.
