### ISSUE TITLE
SX126x IRQ handling: IRQ_HEADER_ERROR should invoke RxError callback

### ISSUE THREAD

**Issue by firmwareguru** [Lora-net/LoRaMac-node#634]
It seems to me that both radio RX errors, HEADER and CRC, should behave the same, that is, invoke the `RadioEvents->RxError()` callback.  

However, the IRQ_HEADER_ERROR event behaves like an RX_TIMEOUT event and triggers the RxTimeout callback.  

I am wondering, is there some rational behind this difference in error handling in terms of the LoRaWAN stack?

**Comment by mluis1** [comment]
The rational behind is that if for some reason the header has an error it means that the frame the radio started to receive is wrong. As such this is similar to the RX_TIMEOUT interrupt.

The RX_TIMEOUT interrupt is generated if the radio doesn't receive something in symbTimeout number of symbols.

The radio only continues the demodulation if a well formed header is received in the symbTimeout window period.
