### ISSUE TITLE
[I-CUBE-LRWAN] Gateway stops receiving packets 

### ISSUE THREAD

**Issue by EHR11** [Lora-net/LoRaMac-node#637]
Hello,

I'm using the STM fork of this implementation, on a STMl151RE processor and a RFM95 module.
I have made the changes to make the code work with my node and my providers' gateway configuration.

The issue comes when, after sending a number of packages (From 6 to 8, as I have tested) the gateway stops recognising the rest of them. 

At first I thought it was a hopping issue, but sometimes packets change DR's so I'm not too sure.
I can't notice differences before and after this happens when debugging.

Any Thoughts? I will try to provide any additional information you need to help.

Thanks in advance and cheers!

**Comment by mluis1** [comment]
As we don't know which modifications you have done to the project and as the i-cube-lrwan project has some differences against this project. We can't really help.

We would advise that you contact the ST support in order to get your questions answered.
