### ISSUE TITLE
Fcnt issue when uplink counter is greater than  65535

### ISSUE THREAD

**Issue by flyingmaster** [Lora-net/LoRaMac-node#639]
I find server would reset the downlink counter to 0 and reported mic error if device sent uplink packet with local FCntUp greater than 65535.   I reviewed the code in LoRaMacCryptoSecureMessage() and found the mic computation was different from the earlier release:

retval = ComputeCmacB0( macMsg->Buffer, ( macMsg->BufSize - LORAMAC_MIC_FIELD_SIZE ), NWK_S_ENC_KEY, false, UPLINK, macMsg->FHDR.DevAddr, macMsg->FHDR.FCnt, &macMsg->MIC );

Here the macMsg->FHDR.FCnt is 16bit but the FCntUp is 32bits,  Is it a issue?

**Comment by xeb246** [comment]
no.the node only send the lower 16bits
