### ISSUE TITLE
Time on air calculations 915US band 

### ISSUE THREAD

**Issue by pBiczysko** [Lora-net/LoRaMac-node#64]
Hello, 

I did some calculations for timeOnAir on US band with LoRa Calculator as well as the formula from sx1272 spec and there is one thing that bothers me. My understanding was that in US band the max timeOnAir for a given channel was 400 ms and that factor was limiting the max payload of messages for a given DR. But for certain examples (SF8BW125, SF12BW500, SF11BW500, SF10BW500) timeOnAir for maximum payload with minimal coding rate is bigger than 400 ms. Does that mean that the hopping mechanism would change the channel in the middle of the packet?

Best regards,
Pawel

**Comment by mluis1** [comment]
The LoRaWAN1.0 specification tables 20 & 21 have some wrong values. LoRaWAN1.0.1 specification corrects those values. Only DR2 (SF8BW125) has an error.

Please note that only 125 kHz channels must comply with 400 ms dwell time. FCC Freq Hopped.
The 500 kHz channels do not have a dwell time limit, it conforms to FCC DTS regulations.
