### ISSUE TITLE
Need help with compiling this project

### ISSUE THREAD

**Issue by Gep93** [Lora-net/LoRaMac-node#669]
Hey,

I am sorry for asking such a noob question and for this not being and actual issue but I am totally in the dark about how to proceed after downloading the code from this github.

I would like to test class A device code with my loraserver network but have no idea how to compile this code and get it to my node (murata type ABZ module).

I have a code from ST which I have gotten from someone and I upload that code to my node with KEIL. The code was already set to go so I didn't have to create the project and do everything myself. Since STs code has some weird behaviour I would like to test the code from here but like I said I have no idea how to do it.

Could somone be so kind and walk me through it?

EDIT: I don't know why I didn't find this before but I found some instructions here:
https://github.com/Lora-net/LoRaMac-node/wiki/Development-environment
will try to follow these and keep you updated of how it goes.

Thanks,
G

**Comment by Gep93** [comment]
Ok, so now I have Cmake and MinGW on my computer (Windows).

I used this command in cmd:

`cmake -DCMAKE_TOOLCHAIN_FILE="cmake/toolchain-arm-none-eabi.cmake" -DTOOLCHAIN_PREFIX="/path/to/the/toolchain" -G "MinGW Makefiles"`

I left first path as is, and changed the second path to the path of "cmake" folder located in ...\LoRaMac-node-4.4.1\cmake

Am I doing this right?

**Comment by djaeckle** [comment]
Hi Gep93,

you need to setup DTOOLCHAIN_PREFIX to your local path of your toolchain. E.g. if you are on windows and you have downloaded '6_2017-q2-update' and you have installed it directly in 'C:\', you should apply  the path 'TOOLCHAIN_PREFIX":"c:/6_2017-q2-update/".

**Comment by djaeckle** [comment]
Hi Gep93,

have you solved it? Can we close this issue?

**Comment by Gep93** [comment]
Hey, 

sorry I haven't. Had to work on some other stuff regarding LoRa and will get back to this issue soon.

If this thread could stay open for now I would greatly appreaciate it!

**Comment by mluis1** [comment]
As there is no updates we decided to close the issue.
