### ISSUE TITLE
when TimerLowPowerHandler ,it looks like execute BoardInitMcu Function,but send and receive buffer OK 

### ISSUE THREAD

**Issue by workholic365** [Lora-net/LoRaMac-node#680]
Hi,everybody:
    when I add Uart printing in BoardInitMcu Fun (board.c ) for testing:
        #if defined(USE_DEBUGGER)
          .......
          UartPutBuffer(&Uart1,"Pa lora node demo\r\n",strlen("Pa lora node demo\r\n"));   
          ........
        #endif
   both compiled and flash successfully ,I can also see interaction information by building [lorawan-server](https://github.com/gotthardp/lorawan-server)  in my PC .
![image](https://user-images.githubusercontent.com/41599448/52933833-87036f80-338f-11e9-8b8f-adb5518e99f5.png)
   everything seems OK,but when I see UART information by serial tool. it seems that it  always initialize board and always execute BoardInitMcu function when it was revoked by timer. the serial output information as following:
     "
         Pa lora node demo
        +JOIN:CLASS_C STARTING...
        PaPaPaPaPaPaPae demo
        +JOIN:DONE

        +STATE:WAITINPaPaPaPaaPa lora node demo
        +STATE:WAITING FOR SEPPaPaPaPaPaaPa lora node demo
        +STATE:WAITING FOR SEPaPaPaPaPaPaPa
     "
    but when I uncomment RtcEnterLowPowerStopMode int TimerLowPowerHandler in timer.c ,it output information OK, 
    "
        Pa lora node demo
        +JOIN:CLASS_C STARTING...
        +JOIN:DONE

        +STATE:WAITING FOR SENDING...
        +STATE:SENDING...
        +SEND:ACK RECEIVED
        +SEND:DONE
    "
    I don't know how this abnormal happen, does anyone give some suggestion or solution? 
    many thanks.

**Comment by mluis1** [comment]
The `BoardInitMcu` function is not the right place to put this message printing. As general rule in board files you should only implement something related to the platform itself.
In your case you are printing a string that is application specific. I would recommend that you move 
```c
#if defined(USE_DEBUGGER)
...
UartPutBuffer(&Uart1,"Pa lora node demo\r\n",strlen("Pa lora node demo\r\n"));
...
#endif
```

to your main.c file

```c
/**
 * Main application entry point.
 */
int main( void )
{
    LoRaMacPrimitives_t macPrimitives;
    LoRaMacCallback_t macCallbacks;
    MibRequestConfirm_t mibReq;
    LoRaMacStatus_t status;

    BoardInitMcu( );
    BoardInitPeriph( );

#if defined(USE_DEBUGGER)
    UartPutBuffer(&Uart1,"Pa lora node demo\r\n",strlen("Pa lora node demo\r\n"));
#endif
...
}
```
