### ISSUE TITLE
AdrAckCounter reset when datarate is minimal

### ISSUE THREAD

**Issue by priit1** [Lora-net/LoRaMac-node#682]
Hello LoRaMac-node developers!

Currently in the master branch, regionXXYYY.c files contain the function RegionXXYYYAdrNext and that function has code similar to this:

```
if( adrNext->AdrEnabled == true )
{
        if( datarate == EU868_TX_MIN_DATARATE )
        {
            *adrAckCounter = 0;
            adrAckReq = false;
        }
        else
        {
            // ...
        }
}
 ```

The code behind else never gets executed, if the current datarate is already at minimum.

I see this happening in two scenarios: 

1. ADR decides to use minimum datarate, but you would still want the channel restore(and maybe TxPower = max?)
2. Confirmed uplinks with >=3 retries lower the DR to minimum. Same issue as option 1, however you would care more about the tx power. Based on my understanding, only DR gets lowered with multiple retries in LoRaMac.c. AdrNext function also adjust the DR. TxPower is only adjusted when AdrAckCounter >= ADR_ACK_LIMIT.

Both these could happen before ADR_ACK_LIMIT(+ADR_ACK_DELAY), so the device would not exhaust all possibilities to recover from a "lost" state.

Based on the 1.0.2 spec, I would understand this to be the correct behaviour, because it only talks about datarate, however it certainly isn't optimal in a real scenario. 

I am working on a 4.4.0 release, however I see the same issue in 4.4.1. Development branches have Adr functionality in LoRaMacAdr.c, and I see the same pattern there. However I have read the new 1.1 spec, and it contains changes in wording and functionality related to this part of the code. So is this a bug or is it considered a feature of the spec? Has this issue been looked into in 1.0.3 and 1.1? 

I tried looking at similar issues, but didn't notice a report about this one. Sorry if I missed it.

Thanks in advance for the feedback.

**Comment by mluis1** [comment]
The behavior you describe is the one provided in the LoRaWAN 1.0.x specifications as such the implementation is correct.

In LoRaWAN 1.1.x specifications this behavior and its description has been improved.
If you take a look at the feature/5.0.0 (1.1.x implementation) branch code you will find the new implementation as well as the old one.

https://github.com/Lora-net/LoRaMac-node/blob/5991d2e4f7e461dd46eceea0e465f49897ad21b8/src/mac/LoRaMacAdr.c#L109
