### ISSUE TITLE
keil 

### ISSUE THREAD

**Issue by megahertzmetal** [Lora-net/LoRaMac-node#684]
can you add support keil? or maybe you have old project on the keil ?

**Comment by djaeckle** [comment]
Hi megahertzmetal,

we have sample projects for old versions of this repository. Please take a look e.g. at tag v4.0.0.

**Comment by yanzi418** [comment]
I wrote a lorawan code for keil project based on stm32l073rz

https://download.csdn.net/download/qq_34710245/10982357

**Comment by megahertzmetal** [comment]
yanzi418, thank you! but i can't download your project because i'm from europe region. Maybe you can upload project on other resource? maybe https://dfiles.ru or dropbox?

**Comment by megahertzmetal** [comment]
and i have questions, why u use STM32L151 platform for your project? why not F series?

**Comment by yanzi418** [comment]
megahertzmetal Give me your mailbox I'll send it to you.

**Comment by yanzi418** [comment]
megahertzmetal，My mailbox is 975375246@qq.com
