### ISSUE TITLE
The node can't go to sleep when slowing down the system clocks

### ISSUE THREAD

**Issue by outely** [Lora-net/LoRaMac-node#686]
hello!

Recently, I found such a problem: when the node works at 32MHz by default, it can enter the low power mode normally. However, in order to reduce the power consumption during operation, when I reduce the system frequency below 4MHz, the node can't enter the low power mode. However, when the system is running above 6MHz, it can enter the low power mode normally. Has anyone tried to sleep normally below 4MHz?

**Comment by mluis1** [comment]
This question is not related to this project it is more a question on how to use the MCU. 
We would recommend that you ask your question directly to your MCU provider.

**Comment by fahad80** [comment]
@outely I have tried MSI at 2.1MHz with STM32L053 and was able to go to the stop mode.

**Comment by outely** [comment]
@fahad80 Thank you for your reply. I used HSI before. Now I try MSI and see if the MCU can enter sleep mode.
