### ISSUE TITLE
How to get EUI from LoRa Node

### ISSUE THREAD

**Issue by danielrsfreitas** [Lora-net/LoRaMac-node#687]
Hi, I would like to know how do I get the EUI identification number to register my LoRa node on a specific application server/gateway.

Thanks

**Comment by Lozeonjyu** [comment]
You need the DevEUI programmed into the node and also register the same DevEUI on network server site. There may or may not be restrictions on the node and network server. It depends on what you are using.

**Comment by mluis1** [comment]
Can we close this issue?
