### ISSUE TITLE
APP_TX_DUTYCYCLE ignored 

### ISSUE THREAD

**Issue by malroe** [Lora-net/LoRaMac-node#69]
Doing the LoRaMote ClassA project trying to change the APP_TX_DUTYCYCLE from 5000000 (5s) does not have any influence on the payload transmission rate! The TX transmission rate is app 2,5 min! How do I reduce the TX transmission rate?

Tried to remove the "LOW_POWER_MODE_ENABLE" from the compiler!

BR
Michael

**Comment by pdemil** [comment]
Are you transmitting at SF12?
There is a duty cycle limitation of 1%. 
For testing purposes you can disable this duty cycle limitation:
LORAWAN_DUTYCYCLE_ON false

Or you can use Spreading Factor 7.

**Comment by malroe** [comment]
Did go for the LORAWAN_DUTYCYCLE_ON false, which worked fine - thank you :-)
