### ISSUE TITLE
How to change Spreading Factor (SF)

### ISSUE THREAD

**Issue by danielrsfreitas** [Lora-net/LoRaMac-node#706]
Hello,

In my country (Brazil) the regulation says the data can not stay on air for more than 400 ms. 

Does anyone know how to change the Spreading Factor (SF) from SF12 to a lower SF, let's say SF10 and help me understand what changes in behavior will be related to this modification ?

**Comment by ConnyBusy** [comment]
Hi @danielrsfreitas 
I suppose you are using EU433 Band. You can do this by changing the following in RegionEU433.h File 

**FROM** 
![image](https://user-images.githubusercontent.com/42280888/55157753-7f3ca500-515d-11e9-83a8-6a6b360f9d70.png)

**TO**
![image](https://user-images.githubusercontent.com/42280888/55157843-bb700580-515d-11e9-9b61-c3f389b24f10.png)

**Comment by danielrsfreitas** [comment]
Hi @ConnyBusy ,

I'm actually using AU915 band. I already changed DR_0 to DR_2 but it didn't seem to work. The only thing that really changed the SF was:

![8DE48ED8](https://user-images.githubusercontent.com/30504231/55171504-384bb100-5157-11e9-9572-253766bd8ea1.PNG)

But I'm not sure if this is the best.

Thanks!

**Comment by mluis1** [comment]
Without changes the AU915 region is already compliant with your requirements.
If you look at file `RegionAU915.h` you will see the bellow line

```c
#define AU915_DEFAULT_UPLINK_DWELL_TIME             1
```
When set to 1 it means that the 400 ms restrictions are enabled.

This means that by default the minimum usable data rate is DR_2 which ensures that the 400 ms restrictions are applied.

**Comment by danielrsfreitas** [comment]
Hi @mluis1 ,

Just saw your commit "e60bd869 Update AU915 and US915 regions according to "LoRaWAN Regional Parameters v1.0.3rA" specification."

I realized that I'm using release 4.4.1.

Thank you so much!
