### ISSUE TITLE
Lorawan 1.1 feature version code confirmation frame problem

### ISSUE THREAD

**Issue by yanzi418** [Lora-net/LoRaMac-node#708]
The lorawan version 1.1 code confirms that the frame is abnormal, no response is received, and the frame count increases.

lorawan1.1
In ProcessRadioTxDone() function
    if( MacCtx.NodeAckRequested == false )
    {
        MacCtx.McpsConfirm.Status = LORAMAC_EVENT_INFO_STATUS_OK;
    }
    MacCtx.ChannelsNbTransCounter++;
    MacCtx.McpsConfirm.NbTrans = MacCtx.ChannelsNbTransCounter;

lorawan1.03
In ProcessRadioTxDone() function
    if( MacCtx.NodeAckRequested == false )
    {
        MacCtx.McpsConfirm.Status = LORAMAC_EVENT_INFO_STATUS_OK;
        MacCtx.ChannelsNbTransCounter++;
    }

**Comment by ConnyBusy** [comment]
Hi @yanzi418,
LoRaWAN1.1.x and LoRaWAN1.0.X do not handle confirmed frames in the same way. In LoRaWAN1.1.x both confirmed and unconfirmed retransmissions are managed by NbTrans. See screenshot below from the spec.

![image](https://user-images.githubusercontent.com/42280888/55309506-4dc62100-545e-11e9-8a5d-a9747644a9fb.png)
