### ISSUE TITLE
ping-pong should not hog the band

### ISSUE THREAD

**Issue by UweBonnes** [Lora-net/LoRaMac-node#717]
At the moment , the ping pong example nearly immediate sends an answer when some ping/pong message has been received. This hogs the band. I propose to answer only after a delay  of one or two seconds to keep the band free for most of the time. Making the Buffersize smaller, e.g. to 8 bytes also saves airtime.

**Comment by mluis1** [comment]
The ping-pong example is just a point to point communication example. It helps one verify if 2 radios are communicating. Test purposes only

For a production firmware one must ensure that the firmware respects the local regulations.

We think that there is no need to change the current example.
