### ISSUE TITLE
How to verify/filter ACK for different Confirmed msgs

### ISSUE THREAD

**Issue by AnilkumarKomanduru** [Lora-net/LoRaMac-node#718]
Hi,
I'm using LoRaMac v4.4.1 (EU868). Currently I have a problem in verification of ACK from application for different features. Lets say i have to send different sensor data(Confirmed) on different Port numbers and now I have to verify ACK for each port is received or Not(though Stack retries for No ACK) from application perspective. 

Can some body help me here ? 
My goal is to identify the ACK received for which packet ? Is that for Tx packet on Port 3 or Port 4 or Port 5 ... ? 

Thank you.

**Comment by fahad80** [comment]
In Class A, you cannot send more than one uplink without waiting for the receive windows. And you receive ACK for confirmed packets during those receive windows. So, in usual cases, the ACK you will receive will be the for the last uplink you send, with whatever port you used.


But if you have some customized way to do so, usually the ACK comes as a downlink that has the port number associated with it. And application provides the McpsConfirm function to Loramac. So you can add port variable into McpsConfirm_t, and then when Loramac call OnRadioRxDone, you can populate that variable with the port number. This way when your application calls McpsConfirm function it will know the port number.
