### ISSUE TITLE
Possible array overrun on LoRaMacChannelRemove

### ISSUE THREAD

**Issue by daniwebCH** [Lora-net/LoRaMac-node#72]
The implementation of LoRaMacChannelRemove does not prevent an array overrun by not verifying the parameter "id".

`if( id < 3 )
    {
        return LORAMAC_STATUS_PARAMETER_INVALID;
    }
    else
    {
        // Remove the channel from the list of channels
        **Channels[id] = ( ChannelParams_t ){ 0, { 0 }, 0 };**
        
        // Disable the channel as it doesn't exist anymore
        if( DisableChannelInMask( id, ChannelsMask ) == false )
        {
            return LORAMAC_STATUS_PARAMETER_INVALID;
        }
    }
    return LORAMAC_STATUS_OK;`

you should add this before the else:

`else if( id >= LORA_MAX_NB_CHANNELS )
    {
        return LORAMAC_STATUS_PARAMETER_INVALID;
    }`

**Comment by djaeckle** [comment]
Hi daniwebCH,

thanks for the report. We will provide an update.
