### ISSUE TITLE
What is the latest LoRaWAN 1.0.2 US915-certified release?

### ISSUE THREAD

**Issue by jonkensta** [Lora-net/LoRaMac-node#720]
The [changelog](https://github.com/Lora-net/LoRaMac-node#2018-03-07-v441) indicates v4.4.1 has passed US915 certification; however, the [releases](https://github.com/Lora-net/LoRaMac-node/releases) page seems to contradict this information, instead stating that v4.4.0 is the latest to pass certification tests.

Which page should I believe?

Thank you very much in advance for your help!

**Comment by mluis1** [comment]
You can rely on the  [changelog](https://github.com/Lora-net/LoRaMac-node#2018-03-07-v441) . We forgot to update the release table as well as the wiki pages.

**Comment by mluis1** [comment]
I have updated the  [release](https://github.com/Lora-net/LoRaMac-node/releases) to reflect the latest status
