### ISSUE TITLE
FSK Configuration

### ISSUE THREAD

**Issue by ontares** [Lora-net/LoRaMac-node#734]
I tried Ping Pong application example and it works fine with the default configuration:
    #define FSK_FDEV                                    25000     // Hz
    #define FSK_DATARATE                            19200     // bps
    #define FSK_BANDWIDTH                        50000     // Hz
    #define FSK_AFC_BANDWIDTH                83333     // Hz
    #define FSK_PREAMBLE_LENGTH             5         // Same for Tx and Rx
and Manchester coding.

Now I want trie the same application but with other FSK configuration:
    #define FSK_FDEV                                    62500     // Hz
    #define FSK_DATARATE                             250000    // bps
    #define FSK_BANDWIDTH                         250000    // Hz
    #define FSK_AFC_BANDWIDTH                 50000     // Hz
    #define FSK_PREAMBLE_LENGTH              5         // Same for Tx and Rx
but it does not work most of the times;
 some times (about 1 time of 20 times) the slave receive the "ping" messagge but never the master receive the "pong" sent.
Have you have an idea about if modulation parameter are good enough or could other reason to investigate?

PS: I attach images with consumption of device of two test (40 mA  == TX, 15 mA  ==  RX).

TK
Ontares

![pp1_consumption](https://user-images.githubusercontent.com/16191830/56416072-1514ad00-6290-11e9-90c0-09d9585f4563.png)
![pp2_consumption](https://user-images.githubusercontent.com/16191830/56416073-1514ad00-6290-11e9-90b7-bd65e8701d96.png)

**Comment by mluis1** [comment]
The parameters that you use don't look correct.
The `FSK_FDEV` value looks to be very low according to the wanted datarate.
Same applies to `FSK_AFC_BANDWIDTH`.

Unfortunately, we don't know which would be the right values to set.

I would recommend that you post your question on the [Semtech LoRa Developers portal](https://lora-developers.semtech.com/knowledge-base/forum/) forum.
