### ISSUE TITLE
sx1276 radio increase the TX power up to +20dbm

### ISSUE THREAD

**Issue by sagar-patel-sls** [Lora-net/LoRaMac-node#735]
Hii
how can we increase TX power up to +20dbm for EU433?

```
radio: sx1276
ISM band: EU433
MBED_RADIO_SHIELD: SX1276MB1MAS
```

Thank you

**Comment by mluis1** [comment]
The LoRaWAN regional parameters specification doesn't allow this. Please refer to the specification.

![image](https://user-images.githubusercontent.com/5763295/56736854-7f828d00-6769-11e9-8927-0b545314640d.png)

Maximum allowed EIRP is 12.5 dBm

**Comment by sagar-patel-sls** [comment]
Thank you @mluis1

**Comment by sagar-patel-sls** [comment]
@mluis1 

we are getting only 100m range. what we can do for maximum range?

**Comment by mluis1** [comment]
It may depend on your PCB design, PCB antenna matching, used antenna, etc...

As this is not related to this software project it would be nice if you post this kind of questions on Semtech forums (please select the right topic). https://lora-developers.semtech.com/knowledge-base/forum/
