### ISSUE TITLE
LoraServer v2.8 multiple device issue

### ISSUE THREAD

**Issue by sagar-patel-sls** [Lora-net/LoRaMac-node#738]
Hii All,

1. In LoRaServer older version we have tested `LoRaWAN v1.1.x` 3 devices were working perfectly at a same time.
2. When we upgraded to latest version of `LoRaServer` & `Lora App Server` and tried to test all `v1.1.x` 3 devices running same time, We have seen strange behavior. See below
- When we are starting 3 devices, our first device is working fine but other 2 devices are not getting `JoinAccept` `ACK` or `rx2timeout`  so they are sending `JoinRequest` again
- after some time 2nd or 3rd device successed and able to work normally, however then our 1st devices loose its connectivity and it doesn't get `ACK` so it moves to BUSY state. 
- So we observed that at the given time, only one device is able to work successfully

```
ISM Band: EU433
Enabled_uplink_channel:[0,1,2]
```

**Comment by mluis1** [comment]
Please refer to the following discussion on LoRaServer forum.
https://forum.loraserver.io/t/release-lora-server-v2-8/4377/13?u=mluis1

As the end-device behavior is compliant with specifications we close this issue.
