### ISSUE TITLE
Battery ADC calculation problem

### ISSUE THREAD

**Issue by outely** [Lora-net/LoRaMac-node#751]
Hi!
At src/boards/SKiM880B/board.c,  Why is the **batteryVoltage** calculated like this？Is it a error?
```
uint16_t BoardBatteryMeasureVolage(void)
{
    uint16_t vref = 0;
    uint32_t batteryVoltage = 0;

    // Read the current Voltage
    vref = AdcReadChannel(&Adc, ADC_CHANNEL_1);

    // We don't use the VREF from calibValues here.
    // calculate the Voltage in millivolt
    batteryVoltage = (uint32_t)ADC_VREF_BANDGAP * (uint32_t)ADC_MAX_VALUE;
    batteryVoltage = batteryVoltage / (uint32_t)vref;

    return batteryVoltage;
}
```
I think the batteryVoltage calculation should be 
`batteryVoltage = (uint32_t)vref * (uint32_t)ADC_VREF_BANDGAP / (uint32_t)ADC_MAX_VALUE;`

**Comment by trick2011** [comment]
It seems alright though. This is found inside the reference manual for the STM32L0x2 on page 322

![image](https://user-images.githubusercontent.com/11191396/59414225-68ebd000-8dc1-11e9-800f-ec1d90de001f.png)

As opposed to the next page:
![image](https://user-images.githubusercontent.com/11191396/59414417-c2ec9580-8dc1-11e9-824a-665be661d250.png)

I do see a optimization oppertunity as the `ADC_VREF_BANDGAP` and `ADC_MAX_VALUE` are constant and could be used in the initialization of `batteryVoltage`.

**Comment by mluis1** [comment]
@trick2011 Thanks for providing the answer.

We close this issue.
