### ISSUE TITLE
Unable to find "rm-none-eabi-lldb"

### ISSUE THREAD

**Issue by digidhamu** [Lora-net/LoRaMac-node#754]
I am getting an error below when I try to debug via VSCode with all the required tools installed on macOS. However, I was able to run via command line successfully.

`Unable to find GDB in default search path and /usr/local/bin/arm-none-eabi-lldb.`

Please advise.

**Comment by trick2011** [comment]
Seems like GDB wasn't installed or was installed at an other location.

**Comment by digidhamu** [comment]
@trick2011 Thanks your reply. This issue was not appearing via command line as described.

**Comment by mluis1** [comment]
Have you solved your issue?
If yes, can we close the issue?
