### ISSUE TITLE
Why  packets data from RF are always CRC error ?

### ISSUE THREAD

**Issue by wuylz** [Lora-net/LoRaMac-node#76]
Hi,
I use iC880A as a concentrator,  iM880A as nodes.
the concentrator is running "basic_packet_forward" program, and the node is running the "LoRaMac-node" code.
I have defined OVER_THE_AIR_ACTIVATION 1   to using OTAA,  but when I start the node, the concentrator can receive any packet, but CRC error  why?
the rasberry Pi printf message is : 
### [UPSTREAM] ###
# RF packets received by concentrator: 14
# CRC_OK: 0.00%, CRC_FAIL: 85.71%, NO_CRC: 0.00%
# RF packets forwarded: 0 (0 bytes)
# PUSH_DATA datagrams sent: 0 (0 bytes)
# PUSH_DATA acknowledged: 0.00%
### [DOWNSTREAM] ###
# PULL_DATA sent: 3 (100.00% acknowledged)
# PULL_RESP(onse) datagrams received: 0 (0 bytes)
# RF packets sent to concentrator: 0 (0 bytes)
# TX errors: 0
##### END #####
INFO: [down] PULL_ACK received in 0 ms
lgw_receive:1197: FIFO content: 1 c0 2 7 28

Thanks

**Comment by rossihwang** [comment]
you should make sure they are in same frequency plan, and no other environmental interference

**Comment by mluis1** [comment]
Can we close this issue?
