### ISSUE TITLE
SAML21 platform SX1276 "Wing Board"

### ISSUE THREAD

**Issue by KaDw** [Lora-net/LoRaMac-node#762]
Hi,

SAML21 port uses SAML21 Xplained Pro with SX1276 "Wing Board". Unforunately SX1276 "Wing Board" is not available in any shop. This setup is a bit out of date and Microchip replaced it with SAMR34. I understand that I can port it myself (eg. to SAMR34) but with up to date hardware more people can contribute and give some feedback. 

Are there any plans to support other hardware platform from Microchip that is not discontinued?

**Comment by mluis1** [comment]
Unfortunately, it is not on our plans to add more platforms to this project at short or long term.

**Comment by elsalahy** [comment]
@KaDw we added support for the SAMR34 instead of SAML21
see:
https://github.com/TheThingsNetwork/LoRaMac-node/tree/feature/SAMR34%2BATECC608A

as part of 
https://github.com/TheThingsNetwork/lorawan-example-atecc608a-tnglora

Hope this is still relevant for you.
