### ISSUE TITLE
Bug in LoRaMacMibSetRequestConfirm() of "case MIB_CHANNELS_DEFAULT_MASK:"

### ISSUE THREAD

**Issue by Dollar-Yao** [Lora-net/LoRaMac-node#764]
https://github.com/Lora-net/LoRaMac-node/blob/32554735fc4e8c764b150497115e71bd67341050/src/mac/LoRaMac.c#L4072
It's should be chanMaskSet.ChannelsMaskIn = mibSet->Param.ChannelsDefaultMask;

**Comment by djaeckle** [comment]
Hi @Dollar-Yao ,

thanks for the report. We will fix this.
