### ISSUE TITLE
McRootKey derivation 

### ISSUE THREAD

**Issue by KaDw** [Lora-net/LoRaMac-node#766]
Hi,

Consider following scenario:
OTAA device supporting LoRaWAN 1.1 boots for the first time and derive McRootKey using APP_KEY. If network server supports LoRaWAN 1.1 all is good (key remains the same). However, problem arises when network server responds that it only supports LoRaWAN 1.0.3 (in code it is done by checking DLsettings flag in join accept). Then crypto derive McRootKey for the second time, now using GEN_APP_KEY which is 0 because it is not used in 1.1. Is this correct?

**Comment by mluis1** [comment]
If the end-device is supposed to work with 1.0x and 1.1.x servers the it means that the end-device manufacturer must set both keys APP_KEY and GEN_APP_KEY.
