### ISSUE TITLE
FOUTA / fragmentation support

### ISSUE THREAD

**Issue by FlorianLudwig** [Lora-net/LoRaMac-node#775]
The `LmhpFragmentationProcess` function contains an intersting TODO: 

https://github.com/Lora-net/LoRaMac-node/blob/a6d958c60235ca3025ec0923458f2aa5c827344b/src/apps/LoRaMac/common/LmHandler/packages/LmhpFragmentation.c#L209-L213

With no timer implemented it seems that all nodes would be sending their answer synchronized at the same time, guaranteeing collisions, making broadcasting data via the fragmentation service unfeasible.

**Comment by mluis1** [comment]
Nowadays, we have only implemented what was required to handle the 1st FUOTA test scenario.
You will notice that there are other TODOs in the current implementation of the FUTOA packages.

If you are interested in implementing the missing parts you are more than welcome to propose your contributions trough pull-requests.
