### ISSUE TITLE
Remote mulitcast setup class switch

### ISSUE THREAD

**Issue by KaDw** [Lora-net/LoRaMac-node#778]
Hi,

I'm testing fuota example that you provided. I noticed that during remote multicast setup node has problems with switching to class C. After a closer look LmHandlerRequestClass() returns LORAMAC_HANDLER_ERROR because LoRaMacMibSetRequestConfirm says that LORAMAC_TX_RUNNING.
Here is a piece of code that switches class (LmHandlerRequestClass).

```
case CLASS_C:
            {
                if( currentClass != CLASS_A )
                {
                    errorStatus = LORAMAC_HANDLER_ERROR;
                }
                // Switch is instantaneous
                mibReq.Param.Class = CLASS_C;
                if( LoRaMacMibSetRequestConfirm( &mibReq ) == LORAMAC_STATUS_OK )
                {
                    LmHandlerCallbacks->OnClassChange( CLASS_C );
                }
                else
                {
                    errorStatus = LORAMAC_HANDLER_ERROR;
                }
            }
            break;
```
I can't reproduce this issue every time.

The solution migth be to disable TX just before switching to class C (set another timer that would disable tx eg 5 seconds before session starts?)

**Comment by mluis1** [comment]
Your solution of avoiding transmissions just before the Class switch is I think the right one.
The current implementation provides I think everything needed to be able to solve this situation.

This means that you must find a way at application level to know when the Class switch is supposed to happen and stop  periodically transmitting uplinks  up until the multicast session is finished.
