### ISSUE TITLE
EU868 BAND2 max time on air

### ISSUE THREAD

**Issue by reissjason** [Lora-net/LoRaMac-node#78]
When BAND2 is used should the MaxPayload for be reduced to stay below the 0.72 second time-on-air limitation?

868.7-869.2 MHz  - <= 0.1%

Page 77
http://www.erodocdb.dk/docs/doc98/official/pdf/rec7003e.pdf

Page 12
http://www.ti.com/lit/an/swra048/swra048.pdf

**Comment by mluis1** [comment]
We don't think it is necessary to change the MaxPayload for BAND2.
There are 2 main reasons for this:
1. The 0.72 second limit only concerns pre-programmed devices. The LoRaWAN protocol is a frequency hopping based system.
2. The documents described limits are advisory only.
