### ISSUE TITLE
FragDecoder GetParity and SetParity uint8_t overflow

### ISSUE THREAD

**Issue by KaDw** [Lora-net/LoRaMac-node#785]
`GetParity` and `SetParity` functions are using `uin8_t index` as argument but it can overflow if FragNb is >255 (which can happen). If that is the case, whole LDPC algorithm gets corrupted and it is unable to repair any frames. Solution is to change `GetParity` and `SetParity` argument `uint8_t index` to `uint16_t index`.

**Comment by mluis1** [comment]
Thanks for the finding.

Would it be possible for you to propose a pull request with the fixed types?

**Comment by KaDw** [comment]
sure, here it is https://github.com/Lora-net/LoRaMac-node/pull/786
