### ISSUE TITLE
Downlink Data Fragment header

### ISSUE THREAD

**Issue by KaDw** [Lora-net/LoRaMac-node#787]
Hi,

According to LoRaWAN Fragmented Data Block Transport Specification header for Downlink Data Fragment it should be: 
![23485448b9a6b01ba9930c1fc2dc54f5f2ca5c34](https://user-images.githubusercontent.com/9391995/64610976-acf66d00-d3d0-11e9-8815-52aebf60c99d.png)

I think in `LmhpFragmentationOnMcpsIndication` fragCounter is parsed the other way around:
```
                fragCounter = ( mcpsIndication->Buffer[cmdIndex++] << 0 ) & 0x00FF;
                fragCounter |= ( mcpsIndication->Buffer[cmdIndex++] << 8 ) & 0xFF00;

                fragIndex = ( fragCounter >> 14 ) & 0x03;
                fragCounter &= 0x3FFF;
```
whereas it should be:
```
                fragCounter = ( mcpsIndication->Buffer[cmdIndex++] << 8 ) & 0xFF00;
                fragCounter |= ( mcpsIndication->Buffer[cmdIndex++] << 0 ) & 0x00FF;

                fragIndex = ( fragCounter >> 14 ) & 0x03;
                fragCounter &= 0x3FFF;
```
Eg. LoRaMac-node expects 8th data fragment to be `08 09 00` instead of `08 00 09` 
Also, similar bug is present in loraserver.io which generates wrong frames. I assume that loraserver.io is also used for testing fuota so headers are compatible

**Comment by mluis1** [comment]
The current LoRaMacNode and I guess loraserver.io implmentations are correct.

If you look at the beginning of the specification document you will notice that multi-byte data is sent LSB first.

![image](https://user-images.githubusercontent.com/5763295/64612789-f052da80-d3d4-11e9-9d22-a22421cc1461.png)

**Comment by KaDw** [comment]
Thanks, that makes sense now.
