### ISSUE TITLE
Latest release has NVM context manager, but comment says it is still untested

### ISSUE THREAD

**Issue by jeremyherbert** [Lora-net/LoRaMac-node#794]
`NvmCtxMgmt.c` contains the following comments:

```
/*!
 * Enables/Disables the context storage management storage at all. Must be enabled for LoRaWAN 1.1.x.
 * WARNING: Still under development and not tested yet.
 */
```

```
/*!
 * Enables/Disables maximum persistent context storage management. All module contexts will be saved on a non-volatile memory.
 * WARNING: Still under development and not tested yet.
 */
```

But the latest release notes imply that the feature is not experimental anymore. It would be good to clarify which of these is true.

**Comment by mluis1** [comment]
Yes, the mention is there because we haven't tested it on all supported platforms.

But, at least for NucleoL073 and B-L072Z-LRWAN1 platforms we didn't saw issues yet.

**Comment by darkfader** [comment]
Well, it seems buggy to me. DataBlockAdrCnt keeps on increasing.
Is it supposed to be some circular buffer? ;)
