### ISSUE TITLE
Fuota-test-01/Information

### ISSUE THREAD

**Issue by Devd2101** [Lora-net/LoRaMac-node#795]
Hi,
device doesn't receive ACK response for file crc check

###### =====   UPLINK FRAME        8   ===== ######

CLASS       : A

TX PORT     : 201
TX DATA     : UNCONFIRMED
05 B5 AD 6E 0C 

DATA RATE   : DR_0
U/L FREQ    : 865062500
TX POWER    : 5
CHANNEL MASK: 0007

**Comment by mluis1** [comment]
According to the 1st test scenario specification the server can decide if it provides an answer to that uplink or not.

Please note that Command 0x05 is not specified. It was just a way to notify the server with computed CRC after full reception of the file.

Like this at the server one can check if the original file CRC is equal to the one computed by the end-device.

In your example the CRC is 0x0C6EADB5.
