### ISSUE TITLE
Error in building pkg_semtech-loramac package test application

### ISSUE THREAD

**Issue by sethuramanrao** [Lora-net/LoRaMac-node#798]
serao@saclay:~/RIOT$ make -C tests/pkg_semtech-loramac clean all
make: Entering directory '/senslab/users/serao/RIOT/tests/pkg_semtech-loramac'
Building application "tests_pkg_semtech-loramac" for "b-l072z-lrwan1" with MCU "stm32l0".

git -C /senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac checkout -f 1cdd9ccec4c9f05b616e7112059be4a9e358c571
HEAD est maintenant sur 1cdd9cc... Merge branch 'release/v4.4.1'
git -c user.email=buildsystem@riot -c user.name="RIOT buildsystem" -C /senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac am --no-gpg-sign --ignore-whitespace "/senslab/users/serao/RIOT/pkg/semtech-loramac"/patches/*.patch
usage : git am [options] [(<mbox>|<Maildir>)...]
   ou : git am [options] (--continue | --skip | --abort)

    -i, --interactive     run interactively
    -3, --3way            allow fall back on 3way merging if needed
    -q, --quiet           être silencieux
    -s, --signoff         add a Signed-off-by line to the commit message
    -u, --utf8            recode into utf8 (default)
    -k, --keep            pass -k flag to git-mailinfo
    --keep-non-patch      pass -b flag to git-mailinfo
    --keep-cr             pass --keep-cr flag to git-mailsplit for mbox format
    --no-keep-cr          do not pass --keep-cr flag to git-mailsplit independent of am.keepcr
    -c, --scissors        strip everything before a scissors line
    --whitespace ...      pass it through git-apply
    --ignore-space-change
                          pass it through git-apply
    --ignore-whitespace   pass it through git-apply
    --directory ...       pass it through git-apply
    --exclude ...         pass it through git-apply
    --include ...         pass it through git-apply
    -C ...                pass it through git-apply
    -p ...                pass it through git-apply
    --patch-format ...    format the patch(es) are in
    --reject              pass it through git-apply
    --resolvemsg ...      override error message when patch failure occurs
    --continue            continue applying patches after resolving a conflict
    -r, --resolved        synonyms for --continue
    --skip                skip the current patch
    --abort               restore the original branch and abort the patching operation.
    --committer-date-is-author-date
                          lie about committer date
    --ignore-date         use current timestamp for author date
    --rerere-autoupdate   update the index with reused conflict resolution if possible
    -S, --gpg-sign[=...]  GPG-sign commits

/senslab/users/serao/RIOT/pkg/pkg.mk:27: recipe for target '/senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac/.git-patched' failed
make[1]: *** [/senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac/.git-patched] Error 1
/senslab/users/serao/RIOT/tests/pkg_semtech-loramac/../../Makefile.include:499: recipe for target 'pkg-prepare' failed
make: [pkg-prepare] Error 2 (ignorée)
"make" -C /senslab/users/serao/RIOT/pkg/semtech-loramac
git -C /senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac checkout -f 1cdd9ccec4c9f05b616e7112059be4a9e358c571
HEAD est maintenant sur 1cdd9cc... Merge branch 'release/v4.4.1'
git -c user.email=buildsystem@riot -c user.name="RIOT buildsystem" -C /senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac am --no-gpg-sign --ignore-whitespace "/senslab/users/serao/RIOT/pkg/semtech-loramac"/patches/*.patch
usage : git am [options] [(<mbox>|<Maildir>)...]
   ou : git am [options] (--continue | --skip | --abort)

    -i, --interactive     run interactively
    -3, --3way            allow fall back on 3way merging if needed
    -q, --quiet           être silencieux
    -s, --signoff         add a Signed-off-by line to the commit message
    -u, --utf8            recode into utf8 (default)
    -k, --keep            pass -k flag to git-mailinfo
    --keep-non-patch      pass -b flag to git-mailinfo
    --keep-cr             pass --keep-cr flag to git-mailsplit for mbox format
    --no-keep-cr          do not pass --keep-cr flag to git-mailsplit independent of am.keepcr
    -c, --scissors        strip everything before a scissors line
    --whitespace ...      pass it through git-apply
    --ignore-space-change
                          pass it through git-apply
    --ignore-whitespace   pass it through git-apply
    --directory ...       pass it through git-apply
    --exclude ...         pass it through git-apply
    --include ...         pass it through git-apply
    -C ...                pass it through git-apply
    -p ...                pass it through git-apply
    --patch-format ...    format the patch(es) are in
    --reject              pass it through git-apply
    --resolvemsg ...      override error message when patch failure occurs
    --continue            continue applying patches after resolving a conflict
    -r, --resolved        synonyms for --continue
    --skip                skip the current patch
    --abort               restore the original branch and abort the patching operation.
    --committer-date-is-author-date
                          lie about committer date
    --ignore-date         use current timestamp for author date
    --rerere-autoupdate   update the index with reused conflict resolution if possible
    -S, --gpg-sign[=...]  GPG-sign commits

/senslab/users/serao/RIOT/pkg/pkg.mk:27: recipe for target '/senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac/.git-patched' failed
make[1]: *** [/senslab/users/serao/RIOT/tests/pkg_semtech-loramac/bin/pkg/b-l072z-lrwan1/semtech-loramac/.git-patched] Error 1
/senslab/users/serao/RIOT/tests/pkg_semtech-loramac/../../Makefile.include:503: recipe for target 'pkg-build-semtech-loramac' failed
make: *** [pkg-build-semtech-loramac] Error 2
make: Leaving directory '/senslab/users/serao/RIOT/tests/pkg_semtech-loramac'
serao@saclay:~/RIOT$

**Comment by mluis1** [comment]
This issue doesn't look to be related to this project directly.

It looks to be an issue related to the build system of the RIOT project. 
You should ask your question there.
