### ISSUE TITLE
Delay function implementation

### ISSUE THREAD

**Issue by yanfli** [Lora-net/LoRaMac-node#80]
HAL_DELAY is used by Delay in new HAL. This will use an extra systick timer. This seems to be a problem for power consumption. How do you consider about this?
Thank you.

**Comment by mluis1** [comment]
You are right the new HAL relies on the SysTick timer.
But, this has almost no impact on the power consumption as when the device goes in to sleep the SysTick timer is also stopped.
When the microcontroller is awaken the power consumption of the other elements is much higher than the SysTick timer one which implies that it can be neglected.

**Comment by yanfli** [comment]
@mluis1 Thanks for your answer.
