### ISSUE TITLE
SyncWord may sometimes let msg in

### ISSUE THREAD

**Issue by mttbx** [Lora-net/LoRaMac-node#804]
I also find crc may sometimes not working when explicit header off.
https://github.com/Lora-net/LoRaMac-node/issues/803
Any reply would be nice!

**Comment by trick2011** [comment]
Why did you open another issue? This seems more like a comment for under #803

**Comment by mttbx** [comment]
@trick2011 This issue is about syncword, #803 is about crc. Not the same at all... I just metion #803 here.

**Comment by mluis1** [comment]
This question is more related to the radio usage and not to the LoRaWAN MAC layer implementation.

Could you please ask these kind of questions on [LoRa Developer Portal](https://lora-developers.semtech.com/knowledge-base/forum/)
