### ISSUE TITLE
Firmware update with context storage enabled

### ISSUE THREAD

**Issue by KaDw** [Lora-net/LoRaMac-node#807]
Hi,

I'm trying to run FUOTA with context management enabled,
 `#define CONTEXT_MANAGEMENT_ENABLED         1`
`#define MAX_PERSISTENT_CTX_MGMT_ENABLED    0`

My goal is to update same device for the second time. Here's what I do:
First I run firmware update, all goes well. After FragDataBlockAuthReq I reset the device (), wait for join, wait for time sync and then run another FUOTA. Then device joins multicast session but I can't receive any downlink after Class C switch.

However If I disable storage of `SeNvmCtx` 
```c   
if( CtxUpdateStatus.Elements.SecureElement == 1 )
    {
        // if( NvmmWrite( &SecureElementNvmCtxDataBlock, MacContexts->SecureElementNvmCtx, MacContexts->SecureElementNvmCtxSize ) != NVMM_SUCCESS )
        // {
        //     return NVMCTXMGMT_STATUS_FAIL;
        // }
    }
```
I can run second update without any problem. My first though was that multicast keys are not updated but I can see that device is joined to multicast session. Any idea which member of `SeNvmCtx` struct might cause this sort of problems? 

I'm using loraserver.io and SAMR34J18B as end-device

**Comment by KaDw** [comment]
Ok, I think I found the cause. Device holds multicast session downlink counter (`CryptoCtx.NvmCtx->FCntList.McFCntDown0`) even if there is new multicast session started using remote. Solution is to restart specific multicast downlink counter when new session is about to start (I think `REMOTE_MCAST_SETUP_MC_GROUP_CLASS_C_SESSION_REQ` case in `LmhpRemoteMcastSetupOnMcpsIndication` is a good place)

```
LoRaMacStatus_t LoRaMacMcChannelSetupRxParams( AddressIdentifier_t groupID, McRxParams_t *rxParams, uint8_t *status )
{
   *status = 0x1C + ( groupID & 0x03 );

    if( ( MacCtx.MacState & LORAMAC_TX_RUNNING ) == LORAMAC_TX_RUNNING )
    {
        return LORAMAC_STATUS_BUSY;
    }

    DeviceClass_t devClass = MacCtx.NvmCtx->MulticastChannelList[groupID].ChannelParams.Class;
    if( ( devClass == CLASS_A ) || ( devClass > CLASS_C ) )
    {
        return LORAMAC_STATUS_PARAMETER_INVALID;
    }

    if( ( groupID >= LORAMAC_MAX_MC_CTX ) || 
        ( MacCtx.NvmCtx->MulticastChannelList[groupID].ChannelParams.IsEnabled == false ) )
    {
        return LORAMAC_STATUS_MC_GROUP_UNDEFINED;
    }
    *status &= 0x0F; // groupID OK

    VerifyParams_t verify;
    // Check datarate
    if( devClass == CLASS_B )
    {
        verify.DatarateParams.Datarate = rxParams->ClassB.Datarate;
    }
    else
    {
        verify.DatarateParams.Datarate = rxParams->ClassC.Datarate;
    }
    verify.DatarateParams.DownlinkDwellTime = MacCtx.NvmCtx->MacParams.DownlinkDwellTime;

    if( RegionVerify( MacCtx.NvmCtx->Region, &verify, PHY_RX_DR ) == true )
    {
        *status &= 0xFB; // datarate OK
    }

    // Check frequency
    if( devClass == CLASS_B )
    {
        verify.Frequency = rxParams->ClassB.Frequency;
    }
    else
    {
        verify.Frequency = rxParams->ClassC.Frequency;
    }
    if( RegionVerify( MacCtx.NvmCtx->Region, &verify, PHY_FREQUENCY ) == true )
    {
        *status &= 0xF7; // frequency OK
    }

    if( *status == ( groupID & 0x03 ) )
    {
        // Apply parameters
        MacCtx.NvmCtx->MulticastChannelList[groupID].ChannelParams.RxParams = *rxParams;
    }
    /* ADDED CODE */
    // reset counter for specific Multicast session
    UpdateFCntDown(MC_FCNT_DOWN_0 + groupID, 0);
    /* ADDED CODE */

    EventMacNvmCtxChanged( );
    EventRegionNvmCtxChanged( );
    return LORAMAC_STATUS_OK;
}
```

**Comment by mluis1** [comment]
Thank you for proposition. Nice finding.

I guess that the counter reset shouldn't be done on this function but, instead on `LoRaMacMcChannelSetup` function.

The problem that I foresee is that if we reset the counter as proposed we may end-up using (repeating) the same counter values with same set of keys. This will create a potential security breach.
While if we reset the counter on `LoRaMacMcChannelSetup` each time the keys are changed the counter gets reset.

I'll check with my colleagues what would be the best solution.

**Comment by KaDw** [comment]
I agree, that is a better place. Also, one more thing that I found. Downcounter should be reset to FCNT_DOWN_INITAL_VALUE, not 0. If we reset to 0, first downlink frame will not be received
`UpdateFCntDown(MC_FCNT_DOWN_0 + groupID, FCNT_DOWN_INITAL_VALUE);`

**Comment by mluis1** [comment]
Thanks, we will provide a fix as soon as possible.

Another issue with your proposition is the usage of `UpdateFCntDown` function call at LoRaMac layer level. This function is supposed to be private to the LoRaMacCrypto layer. Indded for security reason only the LoRaMacCrypto layer should be able to modify counter values.

This means that the  `UpdateFCntDown(MC_FCNT_DOWN_0 + groupID, FCNT_DOWN_INITAL_VALUE);` behavior must be moved and replicated on the function `LoRaMacCryptoDeriveMcSessionKeyPair` implementation.

**Comment by mluis1** [comment]
Actually it is even simpler than I thought. We have a direct access to the Multicast downlink counter value at the LoRaMac layer level.

```c
LoRaMacStatus_t LoRaMacMcChannelSetup( McChannelParams_t *channel )
{
    if( ( MacCtx.MacState & LORAMAC_TX_RUNNING ) == LORAMAC_TX_RUNNING )
    {
        return LORAMAC_STATUS_BUSY;
    }

    if( channel->GroupID >= LORAMAC_MAX_MC_CTX )
    {
        return LORAMAC_STATUS_MC_GROUP_UNDEFINED;
    }

    MacCtx.NvmCtx->MulticastChannelList[channel->GroupID].ChannelParams = *channel;

    const KeyIdentifier_t mcKeys[LORAMAC_MAX_MC_CTX] = { MC_KEY_0, MC_KEY_1, MC_KEY_2, MC_KEY_3 };
    if( LoRaMacCryptoSetKey( mcKeys[channel->GroupID], channel->McKeyE ) != LORAMAC_CRYPTO_SUCCESS )
    {
        return LORAMAC_STATUS_CRYPTO_ERROR;
    }

    if( LoRaMacCryptoDeriveMcSessionKeyPair( channel->GroupID, channel->Address ) != LORAMAC_CRYPTO_SUCCESS )
    {
        return LORAMAC_STATUS_CRYPTO_ERROR;
    }

    if( channel->Class == CLASS_B )
    {
        // Calculate class b parameters
        LoRaMacClassBSetMulticastPeriodicity( &MacCtx.NvmCtx->MulticastChannelList[channel->GroupID] );
    }
// <--- ADDED CODE
    // Reset multicast channel downlink counter to initial value.
    *MacCtx.NvmCtx->MulticastChannelList[channel->GroupID].DownLinkCounter = FCNT_DOWN_INITAL_VALUE;
// <--- END ADDED CODE
    EventMacNvmCtxChanged( );
    EventRegionNvmCtxChanged( );
    return LORAMAC_STATUS_OK;
}
```

**Comment by mluis1** [comment]
@KaDw, Could you please confirm if the proposed solution is OK for you?

**Comment by KaDw** [comment]
@mluis1 Yes, It solved the problem

**Comment by mluis1** [comment]
Thanks, for the feedback.
