### ISSUE TITLE
ack missing in uplink after downlink with ack request

### ISSUE THREAD

**Issue by steph44fr** [Lora-net/LoRaMac-node#816]
ack missing in uplink after downlink with ack request

after receiving downlink with ack request I send uplink for ack
in SendFrame( void ) call of LoRaMacMcpsRequest return LORA_MAC_STATUS_DUTYCYCLE_RESTRICTED due to Duty cycle

so periodicaly I call SendFrame() until uplink is send, but this uplink doesn't contain the ack

**Comment by steph44fr** [comment]
stack is version 4.4.1

**Comment by steph44fr** [comment]
// SEND, IsTxConfirmed = TRUE
```
static b SendFrame( void )
{
	McpsReq_t mcpsReq;
	LoRaMacTxInfo_t txInfo;
	if( LoRaMacQueryTxPossible( AppDataSize, &txInfo ) != LORAMAC_STATUS_OK ) {
		// Send empty frame in order to flush MAC commands
		mcpsReq.Type = MCPS_UNCONFIRMED;
		mcpsReq.Req.Unconfirmed.fBuffer = NULL;
		mcpsReq.Req.Unconfirmed.fBufferSize = 0;
		mcpsReq.Req.Unconfirmed.Datarate = lora_parameters.default_DR;
	} else {
		if( IsTxConfirmed == false) {
			mcpsReq.Type = MCPS_UNCONFIRMED;
			mcpsReq.Req.Unconfirmed.fPort = AppPort;
			mcpsReq.Req.Unconfirmed.fBuffer = AppData;
			mcpsReq.Req.Unconfirmed.fBufferSize = AppDataSize;
			mcpsReq.Req.Unconfirmed.Datarate = LORAWAN_DEFAULT_DATARATE;
		} else {
			mcpsReq.Type = MCPS_CONFIRMED;
			mcpsReq.Req.Confirmed.fPort = AppPort;
			mcpsReq.Req.Confirmed.fBuffer = AppData;
			mcpsReq.Req.Confirmed.fBufferSize = AppDataSize;
			mcpsReq.Req.Confirmed.NbTrials = 8;
			mcpsReq.Req.Confirmed.Datarate = LORAWAN_DEFAULT_DATARATE;
		}
	}
	LoRaMacStatus_t status = LoRaMacMcpsRequest( &mcpsReq );
	if(status == LORAMAC_STATUS_OK )
	{
		return false;
	}
	return TRUE;
}
```

// TASK LoRa
```
case DEVICE_STATE_SEND:
	if( NextTx == true )
	{
		NextTx = SendFrame( );
		if(NextTx == TRUE)
		{
			if( xTimerStart( Send_Wait_DC, 0 ) != pdPASS )
			{
			}
			else
			{
			}
		}
	}
break;
```

// TIMER CALLBACK'void vTimerSendWaitDCCallback(void)
```
{
	xTaskNotify(lora_task_handle, DEVICE_STATE_SEND, eSetValueWithOverwrite);
	xTimerStop( Send_Wait_DC, 0 );
}
```

**Comment by steph44fr** [comment]
before calling SendFrame for the first time, I call LoRaMacGetLoRaMacState wich return LORAMAC_IDLE,
the next call to SendFrame (vTimerSendWaitDCCallback) are without call LoRaMacGetLoRaMacState

**Comment by steph44fr** [comment]
no need to implement periodicaly call to SendFrame()

in LoRaMacStatus_t Send( LoRaMacHeader_t *macHdr, uint8_t fPort, void *fBuffer, uint16_t fBufferSize )
replace 
status = ScheduleTx( false);
with
status = ScheduleTx( true );

it's seems OK

**Comment by djaeckle** [comment]
Hi steph44fr,

thanks for the report. We have verified the operation with integration tests and we cannot reproduce the issue. In addition, the reset of the acknowledgement status in the code will be only reset, if the transmission was successful. 

> status = ScheduleTx( true );

I recommend to not change this for a fix, as this has a different purpose.
