### ISSUE TITLE
How to change device eui in firmware execution?

### ISSUE THREAD

**Issue by VitorLima** [Lora-net/LoRaMac-node#833]
Hi all. 
I want to use STM32 device unique ID combination as Device_EUI and Device_Address.
I have a function to get the 3 words of unique ID and create one vector of 8 bytes for Device_EUI and one 32bit variable for Device_Address.
So I run this function at beginning of the program (after basics initialization) but I don't know how to properly change those parameters.
Till now I've been just manually input values in Commissioning.h file.
Does anyone knows best way to do it?
Thanks a lot.

**Comment by mluis1** [comment]
The provided examples show you how to perform this.

Example:
NucleoL073 classA example main.c file at lines [1030](https://github.com/Lora-net/LoRaMac-node/blob/29c4d42c5489ccff6dbca1f7e718ca8dcb053fd9/src/apps/LoRaMac/classA/NucleoL073/main.c#L1030) and [1048](https://github.com/Lora-net/LoRaMac-node/blob/29c4d42c5489ccff6dbca1f7e718ca8dcb053fd9/src/apps/LoRaMac/classA/NucleoL073/main.c#L1048)

```c
...
                    // Initialize LoRaMac device unique ID if not already defined in Commissioning.h
                    if( ( devEui[0] == 0 ) && ( devEui[1] == 0 ) &&
                        ( devEui[2] == 0 ) && ( devEui[3] == 0 ) &&
                        ( devEui[4] == 0 ) && ( devEui[5] == 0 ) &&
                        ( devEui[6] == 0 ) && ( devEui[7] == 0 ) )
                    {
                        BoardGetUniqueId( devEui );
                    }
...

                    // Choose a random device address if not already defined in Commissioning.h
                    if( DevAddr == 0 )
                    {
                        // Random seed initialization
                        srand1( BoardGetRandomSeed( ) );

                        // Choose a random device address
                        DevAddr = randr( 0, 0x01FFFFFF );
                    }
...
```
