### ISSUE TITLE
GetElement( ) function in LoRaMacConfirmQueue.c

### ISSUE THREAD

**Issue by Dollar-Yao** [Lora-net/LoRaMac-node#837]
[https://github.com/Lora-net/LoRaMac-node/blob/87f19e84ae2fc4af72af9567fe722386de6ce9f4/src/mac/LoRaMacConfirmQueue.c#L115](url)
If the request which we wanted is bufferEnd, as element is set to bufferStart, when we do the judgement of while( element != bufferEnd ), the code will execute "else" until element is equal with bufferEnd. When element is equal with bufferEnd, actually we have found the request, but then do the judgement of while( element != bufferEnd ) will fail, then return NULL. The issue is that there is no condition to judge 'request' is equal with 'element' when 'request' is bufferEnd. I think we should add code like: if( element == bufferEnd )..., after executing while.

**Comment by mluis1** [comment]
Thanks for the finding. Will be corrected for next  milestone.
