### ISSUE TITLE
How to generate encrypted multicast key (McKeyE) for multicast channel setup

### ISSUE THREAD

**Issue by rifatsahiner** [Lora-net/LoRaMac-node#840]
I wanted to update stack to  a newer version but multicast channel setup is now changed. New procedure needs an "encrypted multicast key" but it's unclear how to generate this key on both stack and lorawan specification. Explanation about McKEKey on specification;
> Derived from a new root key (GenAppKey) provisioned in the end-device at any time before the deployment of the end-device in the field. LoRaWAN 1.0.x end-devices SHALL use this scheme.
> * McRootKey = aes128_encrypt(GenAppKey, 0x00 | pad16)
> * McKEKey = aes128_encrypt(McRootKey, 0x00 | pad16)

We are using stack and network server configured for a private v1.0.3 network. Is there any way to bypass this key (use one of the other multicast keys instead)? If not can someone further explain how to generate this key?
Thanks.

**Comment by djaeckle** [comment]
Hi @rifatsahiner ,

thanks for the report. Actually, this is already on the roadmap for 4.5.0. We will provide a sample implementation for a "static" multicast setup - as soon as its ready we will provide a brief overview here.
