### ISSUE TITLE
Bug in LoRaMacCommandsGetCmdSize() for case SRV_MAC_RX_PARAM_SETUP_REQ ?

### ISSUE THREAD

**Issue by FranciscoRV** [Lora-net/LoRaMac-node#848]
https://github.com/Lora-net/LoRaMac-node/blob/811e46c09fa40c309ad8e3116f2029edb85076a0/src/mac/LoRaMacCommands.c#L578

**It's should be :**

```
      cidSize = 5;  // cid(1B) + DLsettings(1B) + Frequency (3B) = 5B
```

**Comment by mluis1** [comment]
Thanks for the finding. Will be corrected for next milestone.
