### ISSUE TITLE
I2C without clock signal on B-L072Z-LRWAN1

### ISSUE THREAD

**Issue by AlexandroSantos** [Lora-net/LoRaMac-node#853]
Hello my dear, 

I'm using:
Ubuntu 18.04 (Cmake, gcc-arm-none-eabi);
B-L072Z-LRWAN1;
DS18B20, for example;

Declarations in main.c:
#include "i2c.h"
I2c_t DS;
uint8_t databuffer;

main ()
I2cInit (& DS, ID_DS, PB_8, PB_9);
I2cReadBuffer (& DS, 0x57, 0xBC, & databuffer, 1); // fictional address and register, example only.

Compiling, there are no errors. But, monitoring the clock signal on pin PB_8 (data in PB_9, sda) with the oscilloscope, I didn't find it.

In an attempt to observe the signal I did:
do{
I2cReadBuffer (& DS, 0x57, 0xBC, & databuffer, 1); // fictional address and register, example only.
} while (true); // It's crazy but, it was for testing.
   
And no clock signal.

Another problem, in the serial terminal (Cutecom) displays just this:
<0xed><0xdf><0xfd><0xdb><0xdb><0xdb><0xdb><0xdb><0xff><0xdb><0xff><0xdf><0xdb><0xdb> <0xdf> I <0xdb> < 0xfb> <0xff> <0xdf> <0xdb> I <0xdb> [<0xdf> <0xdb> <0xfb> <0xdb> <0xdb> <0xdb> <0xfb> <0xdb> <0xdb> <0xdf> 0xff> <0xdf> <0xdb> <0xdb> <0xdb> <0xdb> <0xfb> <0xff> [<0xdb> <0xdb> <0xdb> <0xdb> <0xff> <0xdb> [<0xdf> <0xdb> <0xdb> 0xdb> <0xfb> <0xff> <0xdf> <0xdb> <0xdb> <0xdb> <0xdb> <0xdb> <0xdb> <0xdb> <0xc9> <0xff> <0xdb> <0xdf> <0xff> <0xd> <0xdb><0xdb><0xdb><0xff><0xdb><0xdb><0xdf><0xdb><0xdb><0xfd><0xdf><0xdb><0xdf><0xff><0xdf> <0xdb> I < 0xdf> <0xdb> [<0xdf> <0xdb> <0xfb> ...

I thank everyone who can help me.

**Comment by mluis1** [comment]
Can we close this issue?
