### ISSUE TITLE
Support for LLCC68

### ISSUE THREAD

**Issue by Pirakutu** [Lora-net/LoRaMac-node#860]
Hi guys,

just wanted to ask if you guys will also integrate the new LoRa chip LLCC68. If yes, when are you planning to do so?

Cheers & thanks!

**Comment by mluis1** [comment]
The LLCC68 doesn't support all required LoRaWAN specification data rates.

Although, one can use the already supported SX126x radio driver and limiting the MAC layer to the supported data rates.

Please note that you will not be able to get the LoRa-Alliance certification using this radio chip.
