### ISSUE TITLE
TCXO Contol on B-L072Z-LRWAN1 Discovery

### ISSUE THREAD

**Issue by gilbertoe** [Lora-net/LoRaMac-node#863]
Hi

Could anyone tell if the TCXO control on the B-L072Z-LRWAN1 Discovery board by PA12 is implemented? If so, am I free to use any GPIO for this function?

BR
Gilberto

**Comment by MedadRufus** [comment]
The GPIO pin for turning on and off the TCXO appears to be defined in ``src/boards/B-L072Z-LRWAN1/board-config.h``. In the variable ``#define RADIO_TCXO_POWER                            PA_12``. I think you should be able to change that pin to any GPIO pin. 

Looking at the code, it appears that TCXO control is implemented.

In ``src/boards/B-L072Z-LRWAN1/sx1276-board.c`` they have implemented a function to turn off and on the TCXO:

```c
void SX1276SetBoardTcxo( uint8_t state )
{
    if( state == true )
    {
        if( GpioRead( &TcxoPower ) == 0 )
        { // TCXO OFF power it up.
            // Power ON the TCXO
            GpioWrite( &TcxoPower, 1 );
            DelayMs( BOARD_TCXO_WAKEUP_TIME );
        }
    }
    else
    {
        // Power OFF the TCXO
        GpioWrite( &TcxoPower, 0 );
    }
}
```


This function is getting called to turn off the TCXO during sleep mode.
