### ISSUE TITLE
sx1278 support?

### ISSUE THREAD

**Issue by xenpac** [Lora-net/LoRaMac-node#868]
im using the sx1278 in the 400mhz range.
any chance of adding it?

**Comment by mluis1** [comment]
The SX1278 is almost an exact copy of the SX1276 radio.

The difference is that the SX1278 only covers the lower UHF bands.

In your case you have to choose one of the platforms supporting the SX1276 radio and select one of the regions that work on lower UHF bands. These regions are CN470 and EU433.
