### ISSUE TITLE
Question: How to add a new board support

### ISSUE THREAD

**Issue by Vinimuller** [Lora-net/LoRaMac-node#876]
Hello! I have a project that I use the SX1276 radio with STM32F334 uC. I like the way the drivers here are written and I would like to use the SX1276 driver available on this repo, so I don't need to write everything again. Is there any tutorial indicating how the driver structure works and what I need to do to make it work with another processor?

**Comment by EduardoPfeifer** [comment]
http://stackforce.github.io/LoRaMac-doc/_p_o_r_t_i_n_g__g_u_i_d_e.html
