### ISSUE TITLE
Nvm ctx restore may have issue for pointer

### ISSUE THREAD

**Issue by wwx0715** [Lora-net/LoRaMac-node#877]
1.LoRaMacCommandsRestoreNvmCtx():NvmCtx.MacCommandList is using pointer, if memory usage is changed, these pointer will be changed after reboot
2.RestoreCtxs() at LoRaMac.c:need call LoRaMacCryptoSetMulticastReference() also, reson like above

**Comment by mluis1** [comment]
We have reworked the NVM context management could you please verify that this issue has been solved?

If it is the case could you please close this issue?
