### ISSUE TITLE
LmhpFragmentation issues

### ISSUE THREAD

**Issue by wwx0715** [Lora-net/LoRaMac-node#878]
1.the response FRAGMENTATION_FRAG_STATUS_ANS message format may be wrong:
should be:
                    LmhpFragmentationState.DataBuffer[dataBufferIndex++] = FragSessionData[fragIndex].FragDecoderStatus.FragNbRx & 0xFF;
                    LmhpFragmentationState.DataBuffer[dataBufferIndex++] = ( fragIndex << 6 ) |
                                                                           ( ( FragSessionData[fragIndex].FragDecoderStatus.FragNbRx >> 8 ) & 0x3F );

not be:
                    LmhpFragmentationState.DataBuffer[dataBufferIndex++] = ( fragIndex << 14 ) |
                                                                           ( ( FragSessionData[fragIndex].FragDecoderStatus.FragNbRx >> 8 ) & 0x3F );
                    LmhpFragmentationState.DataBuffer[dataBufferIndex++] = FragSessionData[fragIndex].FragDecoderStatus.FragNbRx & 0xFF;

2.when handle FRAGMENTATION_FRAG_SESSION_SETUP_REQ, may be need to check FragNb and FragSize also, not just total size. I test fuota and FragNb is beyond FRAG_MAX_NB, cause decoder memory overflow

**Comment by mluis1** [comment]
Thanks for the finding.

I have pushed the fixes for the 2 propositions.
Could you please check the propositions and then close the issue?
