### ISSUE TITLE
First message after reset not sent

### ISSUE THREAD

**Issue by branek** [Lora-net/LoRaMac-node#879]
Sending first message after reset of the device is broken by this commit: 92547484285b9114695262fcdd981a8536f0cb75

It looks like that after JOIN accept, MacCtx.ChannelsNbTransCounter is not reset, and first message sending ends up in function `static LoRaMacStatus_t SecureFrame( uint8_t txDr, uint8_t txCh )` on this:
```
            ...
            if( MacCtx.ChannelsNbTransCounter >= 1 )
            {
                fCntUp -= 1;
            }
            ...
```
Steps to reproduce (feature/5.0.0 branch):

- Join on EU868 network
- Send message
- Observe message not sent
Any subsequent messages are sent as expected.

**Comment by mluis1** [comment]
Thanks for the report.

We had already fixed the issue in our internal repository.
