### ISSUE TITLE
Downlink packets are not being received - AU915

### ISSUE THREAD

**Issue by lucaspeixotot** [Lora-net/LoRaMac-node#886]
I'm working on a porting process to use LoRaMac. I think that I finished it, except for the fact that I'm not getting downlink packets. I suspect that it can be or a porting issue or a configuration wrong. I'm using the end-device in class C and with ABP activation. My network server is on Everynet and I had this config to this end-device:
- AU915
- Uplink: 8 initial channels beginning in 915.2MHz, with 200KHz increments
- Downlink: 8 last channels beginning in 923.3MHz with 500KHz increments
- Rx1 = 5s e Rx2 = 6s
- ADR on
- Rx window auto
- Class C

Besides that, I configured the end-device through LoRaMacMibSetRequestConfirm with these values:
- MIB_RECEIVE_DELAY_1
    - 5000
- MIB_RECEIVE_DELAY_2
    - 6000
- MIB_ABP_LORAWAN_VERSION
    - 0x01000300
- MIB_SYSTEM_MAX_RX_ERROR
    - 20
- MIB_MIN_RX_SYMBOLS
    - 8
- MIB_NETWORK_ACTIVATION
    - ACTIVATION_TYPE_ABP
- MIB_CHANNELS_DEFAULT_MASK and MIB_CHANNELS_MASK
    - 00FF 0000 0000 0000 FFFF

All my uplink packets arrive on the network server. This is my log output (I printed rx2 channel config because I read in the regional specification that rx2 should have 923.3MHz and DR8, so I printed to see if it was true).

```
MIB_RX2_CHANNEL	: 
Frequency	: 923300000
Datarate	: 8
MIB_RX2_DEFAULT_CHANNEL	: 
Frequency	: 923300000
Datarate	: 8
MIB_RECEIVE_DELAY_1	: 
Delay 1	: 5000
MIB_RECEIVE_DELAY_2	: 
Delay 2	: 6000

###### ===== MCPS-Request ==== ######
PORT		: 2
Buffer		: 
F1 
Buffer size	: 1
Confirmed	: n
Datarate	: 2
STATUS		: OK
Next tx frame 9178

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MCPS-Confirm ==== ######
STATUS      : OK
MCPS UNCONFIRMED

###### ===== UPLINK FRAME 1 ==== ######

CLASS       : C

TX PORT     : 2
TX DATA     : UNCONFIRMED
F1 

DATA RATE   : DR_2
U/L FREQ    : 915800000
TX POWER    : 0
CHANNEL MASK: 00FF 0000 0000 0000 FFFF 


###### ===== MCPS-Request ==== ######
PORT		: 2
Buffer		: 
F1 
Buffer size	: 1
Confirmed	: n
Datarate	: 2
STATUS		: OK
Next tx frame 10649

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MCPS-Confirm ==== ######
STATUS      : OK
MCPS UNCONFIRMED

###### ===== UPLINK FRAME 2 ==== ######

CLASS       : C

TX PORT     : 2
TX DATA     : UNCONFIRMED
F1 

DATA RATE   : DR_2
U/L FREQ    : 916200000
TX POWER    : 0
CHANNEL MASK: 00FF 0000 0000 0000 FFFF 
```

I checked through the gdb if the code is receiving IrqStatus from radio if the SX126xWriteCommand and SX126xReadCommand are working and I think that they are. Have anyone some suggestions about what can be the problem? Is it missing some configuration on the end-device side?

**Comment by EduardoPfeifer** [comment]
@lucaspeixotot 

Is your configuration the same as in this image?

![ClassC](https://user-images.githubusercontent.com/16170543/83288198-57116180-a1b9-11ea-8e6b-2a78d1a9df68.png)

**Comment by lucaspeixotot** [comment]
@EduardoPfeifer 

Exactly the same.

**Comment by lucaspeixotot** [comment]
> @lucaspeixotot
> 
> Is your configuration the same as in this image?
> 
> ![ClassC](https://user-images.githubusercontent.com/16170543/83288198-57116180-a1b9-11ea-8e6b-2a78d1a9df68.png)

Look that when the network server receives an uplink packet it is sending a downlink response, the mcps_indication is just not getting the packet.

![2020-05-29-14:44:45_133x219_screenshot](https://user-images.githubusercontent.com/11475476/83289362-54b00700-a1bb-11ea-878c-10f7338a80da.png)

**Comment by EduardoPfeifer** [comment]
Did you check the configuration of all GPIOs on the radio? I am using the SX1276, it may be a SX126X driver problem as you mentioned.

**Comment by lucaspeixotot** [comment]
> Did you check the configuration of all GPIOs on the radio? I am using the SX1276, it may be a SX126X driver problem as you mentioned.

Yes but I will make a double check now, I'm going to verify it. About my end-device configuration and the network config, do you think that is okay?

**Comment by EduardoPfeifer** [comment]
> > Did you check the configuration of all GPIOs on the radio? I am using the SX1276, it may be a SX126X driver problem as you mentioned.
> 
> Yes but I will make a double check now, I'm going to verify it. About my end-device configuration and the network config, do you think that is okay?

Yes, I think that is okay!

**Comment by lucaspeixotot** [comment]
> 
> 
> Did you check the configuration of all GPIOs on the radio? I am using the SX1276, it may be a SX126X driver problem as you mentioned.

I already checked and the pins are configured right. Actually I'm using the SX1262MB2xAS mbed shield. And I copied the sx1262mbxcas-board.c from an example to be the shield driver. Is there some problem on it?

**Comment by lucaspeixotot** [comment]
I realized that my rtc-board.c implementation was with counter late. After fixing it I received downlink packets but only for class C. In class A I can't receive packets yet.

**Comment by lucaspeixotot** [comment]
> I realized that my rtc-board.c implementation was with counter late. After fixing it I received downlink packets but only for class C. In class A I can't receive packets yet.

I found a new error this time on delay-board.c, I fixed it and everything is working now. Thanks.

**Comment by khariya** [comment]
@lucaspeixotot Could you please describe the issue rtc-board.c and delay-board.c implementation and the fix? I'm having a similar issue in US915 region.

**Comment by lucaspeixotot** [comment]
> @lucaspeixotot Could you please describe the issue rtc-board.c and delay-board.c implementation and the fix? I'm having a similar issue in US915 region.

In rtc-board.c my counter was not in 1Hz of frequency. And in delay-board.c the function DelayMsMcu was not implemented correctly(I was using a wrong API from silicon labs code)
