### ISSUE TITLE
B-L072Z-LRWAN1 LOW POWER MODE

### ISSUE THREAD

**Issue by gilbertoe** [Lora-net/LoRaMac-node#891]
Hi

Could someone tell me if the LoraMac-node enters in deep sleep mode during rx1 and rx2 windows? If so, could you show me where this function is in the code? 

I have already checked with an oscilloscope that VDD_TXCO is disabled during r1 and rx2, but I did not find any info on the sleep mode.

BR
Gilberto

**Comment by altishchenko** [comment]
@gilbertoe You can search for the LpmEnterLowPower() in your code, depending on the application you are compiling.

**Comment by gilbertoe** [comment]
Thanks!
