### ISSUE TITLE
Warning[Pa118]: mixing boolean and non-boolean types in a comparison results in the boolean being promoted

### ISSUE THREAD

**Issue by Xeenych** [Lora-net/LoRaMac-node#898]
IAR C++ Compiler produces the following warning

Warning[Pa118]: mixing boolean and non-boolean types in a comparison results in the boolean being promoted D:\Projects\LoRaArtur\amdk_F103\LoraMac\mac\LoRaMac.c 1128 

https://github.com/Lora-net/LoRaMac-node/blob/d3791e2a00598452eb34290c69447727dfb3fe52/src/mac/LoRaMac.c#L1130

There should be 1, not "true"

The same for line #1129

**Comment by EduardoPfeifer** [comment]
> ( macMsgData.FHDR.FCtrl.Bits.Ack == true ) ||

I recomend:

`( macMsgData.FHDR.FCtrl.Bits.Ack != 0 )`

**Comment by mluis1** [comment]
Thanks for the finding.

Would you be willing to propose a pull-request?

@EduardoPfeifer proposition is the right way to go.

**Comment by Xeenych** [comment]
I wonder if I've done ot right
https://github.com/Lora-net/LoRaMac-node/pull/899

**Comment by mluis1** [comment]
Yes, it looks good. Thanks.
