### ISSUE TITLE
failing join when setting the node to private 

### ISSUE THREAD

**Issue by Crossfire60** [Lora-net/LoRaMac-node#90]
I'm using a Kerlink SPN base-station, I'm using a private LoRa network and am trying to connect my SK IM880A.
When the network mode is set to public the connection is successful, but when I set it to private, the node will not join the network. I am using the OTA activation method.

**Comment by pdemil** [comment]
Try to disable the Public Network on your SK IM880A.
Search  SetPublicNetwork

**Comment by Crossfire60** [comment]
Maybe I wasn't clear but that's what I tried which resulted in a failed join. That's why I'm aksing what might have gone wrong.

**Comment by pdemil** [comment]
Can you change the configuration of the Kerlink SPN basestation to private network?

**Comment by mluis1** [comment]
Can we close the issue?
It looks like that this issue is related to the network setup rather than end-device implementation.
