### ISSUE TITLE
missing compile_commands.json

### ISSUE THREAD

**Issue by Xeenych** [Lora-net/LoRaMac-node#904]
I'm trying to build LoRaMac-node with VSCode.
There is a reference to a file which is missing from repository
https://github.com/Lora-net/LoRaMac-node/blob/235b14d7019257b50a8de90c82b5d0f94ed35418/.vscode/c_cpp_properties.json#L5

**Comment by mluis1** [comment]
This file is automatically created when the build succeeds.
This file is used by VSCode to handle the IntelliSense features.
