### ISSUE TITLE
Receiving packet in Network Server, but TxTimeout is being triggered

### ISSUE THREAD

**Issue by lucaspeixotot** [Lora-net/LoRaMac-node#909]
Hello, I'm making a port of LoRaMac and strange behavior is happening. When I'm sending a packet to network server the packet is being received, but for some reason, the IRQ_TX_DONE flag is not being set when the radio is calling SX126xGetIrqStatus. I'm trying to make a port for a board from Silicon Labs; Actually I already did a port for a different board from Silicon Labs and I'm making just some changes on it for this port works in another board.

Below you can see the log from my console. Note that when the RadioIrqProcess is called I'm printing the irq status from SX126xGetIrqStatus and it is always 0.

```
###### ===== MCPS-Request ==== ######
PORT		: 2
Buffer		: 
F1 
Buffer size	: 1
Confirmed	: y
Datarate	: 2
STATUS		: OK
Next tx frame in 4601ms
NCP task
Bluetooth event task started!
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######
irq status: 0000

###### ===== MAC-PROCESS-NOTIFY ==== ######

###### ===== MCPS-Confirm ==== ######
STATUS      : Tx timeout

###### ===== UPLINK FRAME 2 ==== ######

CLASS       : A

TX PORT     : 2
TX DATA     : CONFIRMED - NACK
F1 

DATA RATE   : DR_2
U/L FREQ    : 915800000
TX POWER    : 0
CHANNEL MASK: 00FF 0000 0000 0000 00FF 
```

I already see that this problem happens when the radio chip is dead or when the pin connections are wrong but this is not my case. My radio chip is working well because I already did a port for another board and it is working. And my pin connections were checked a lot of times, so it is ok too.

This can be a problem in my spi-board.c, but I can't see where can be the problem. The stranger thing is that the packet is being received, so apparently the spi-board.c is working in some way.

I can send more information if is needed, so tell me about that.

**Comment by LocatorCJSC** [comment]
Check the RADIO_DIO_0 ... RADIO_DIO_5 pins connections, and check if their corresponding interrupts work.

**Comment by lucaspeixotot** [comment]
> Check the RADIO_DIO_0 ... RADIO_DIO_5 pins connections, and check if their corresponding interrupts work.

I'm using sx1262 and just RADIO_DIO_0 is connected. It is working because the irq is working and the irqFire variable is setting to true, enabling RadioIrqProcess to check the irqRegs with SX126xGetIrqStatus.

**Comment by lucaspeixotot** [comment]
Apparently when the DIO0 interrupt happens is because there is something in irqStatus but I'm getting always zero. I could say that the something in read and write commands are wrong but how if the packet is being received by network server?
