### ISSUE TITLE
ld.exe: unrecognized option '--major-image-version'

### ISSUE THREAD

**Issue by Xeenych** [Lora-net/LoRaMac-node#912]
I've followed development environment setup from here.
https://github.com/Lora-net/LoRaMac-node/blob/master/doc/development-environment.md
I'm using VSCode and trying to build LoaraMac periodic-uplinc-lpp

And I get the following error:
```
[build] [ 88%] Linking C executable LoRaMac-periodic-uplink-lpp.exe
[build] c:/progra~2/gnuarm~1/92020-~1/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: unrecognized option '--major-image-version'
[build] c:/progra~2/gnuarm~1/92020-~1/bin/../lib/gcc/arm-none-eabi/9.3.1/../../../../arm-none-eabi/bin/ld.exe: use the --help option for usage information
[build] collect2.exe: error: ld returned 1 exit status
[build] mingw32-make[2]: *** [src\apps\LoRaMac\CMakeFiles\LoRaMac-periodic-uplink-lpp.dir\build.make:383: src/apps/LoRaMac/LoRaMac-periodic-uplink-lpp.exe] Error 1
[build] mingw32-make[1]: *** [CMakeFiles\Makefile2:383: src/apps/LoRaMac/CMakeFiles/LoRaMac-periodic-uplink-lpp.dir/all] Error 2
[build] mingw32-make: *** [Makefile:86: all] Error 2
```

**Comment by mluis1** [comment]
This looks to be an issue concerning your development environment and we don't really know how we can help you.

Have you followed the instructions provided by [Development environment](doc/development-environment.md) document.
If yes, maybe you have missed a required step provided on that document.

From your error description there is something weird. The final executable has an `.exe` extension while it should have no extension at all. 

The following line
```bash
[build] mingw32-make[2]: *** [src\apps\LoRaMac\CMakeFiles\LoRaMac-periodic-uplink-lpp.dir\build.make:383: src/apps/LoRaMac/LoRaMac-periodic-uplink-lpp.exe] Error 1
```
should look like the below
```bash
[build] mingw32-make[2]: *** [src\apps\LoRaMac\CMakeFiles\LoRaMac-periodic-uplink-lpp.dir\build.make:383: src/apps/LoRaMac/LoRaMac-periodic-uplink-lpp] Error 1
```

It feels like the make files think you are compiling a code for Windows.
