### ISSUE TITLE
Please check and fix some uninitialized structs

### ISSUE THREAD

**Issue by Supowang1989** [Lora-net/LoRaMac-node#919]
if the fuction “RegionCommonParseLinkAdrReq” return 0 ，the while loop will break ，we use uninitialized_structs “linkAdrParams ” after the  while loop，please check it， Thanks！

This case is found by a student in tsinghua university，we have merged this in TencentOS Tiny program  as follows：

https://github.com/Tencent/TencentOS-tiny/commit/953a77cd08aa1722ce3bfa63adee153fa9b25fb6

**Comment by mluis1** [comment]
Thanks for the finding.
