### ISSUE TITLE
Adaptive data rate - how to swich on it?

### ISSUE THREAD

**Issue by Arcanum7** [Lora-net/LoRaMac-node#921]
Hi everyone!
I have stm32L072 chip and sx1272 lorachip.
I had developed a simple end-node device with stm32 lrwan library and endnode example for nucleo board.
Developed by Atollic True Studio.
Versions is: MAC_VERSION= 04.04.02.00 and STM32CubeExpansion_LRWAN_V1.3.1

options that i had used to: 
1) LORAWAN_ADR_ON - true;
2) Global define REGION_EU868;
3) server's prefer DR is 5 (SF7);

Questions:
1) why uplink from device is always SF12? I think that the datarate should change itself or am I wrong?
2) how to make it "true" ADR?

**Comment by mluis1** [comment]
First I would like to inform that this kind of questions are better suited to be asked on a forum.
Please find below an example of forum where such question will get better support.
https://lora-developers.semtech.com/knowledge-base/forum/

The data rate increase by the ADR algorithm depends on how the network server has implemented such algorithm.
Usually it takes several uplinks before the network server is able to decide to increase the data rate.

From LoRaMac point of view you have everything correctly set up.
