### ISSUE TITLE
Only three chanels - how to make more?

### ISSUE THREAD

**Issue by Arcanum7** [Lora-net/LoRaMac-node#922]
Hi everyone!
I have stm32L072 chip and sx1272 lorachip.
I had developed a simple end-node device with stm32 lrwan library and endnode example for nucleo board.
Developed by Atollic True Studio.
Versions is: MAC_VERSION= 04.04.02.00 and STM32CubeExpansion_LRWAN_V1.3.1

options that i had used to:

    1)LORAWAN_ADR_ON - true;
    2)Global define REGION_EU868;
    3)server's chanels list:
3.1) FIXED; (servers chanel default);
3.2) FIXED;
3.3) FIXED;
3.4) 867,1 MHz;
3.5) 867,3 MHz;
3.6) 867,5 MHz;
3.7) 867,7 MHz;
3.8) 867,9 MHz;

Questions:

    My firmware program is always send data by three chanels: 868,1MHz, 868,3MHz, 868,3MHz. How can I add the missing channels?

**Comment by mluis1** [comment]
First I would like to inform that this kind of questions are better suited to be asked on a forum.
Please find below an example of forum where such question will get better support.
https://lora-developers.semtech.com/knowledge-base/forum/

By default the LoRaMac stack (and I believe all other stacks) start operation with default channels only.
These default channels are the only ones that the end-device can be sure to exist at any time.

It is the responsibility of the network server to create the extra channels. The network server is the one that knows how the gateways are setup (on which channels the gateways are listening).

Usually the network servers provide the extra channels by providing for OTAA activated end-devices a CFList on the JoinAccept downlink frame and for ABP activated end-device by using the NewChannelReq/Ans MAC commands.
