### ISSUE TITLE
Semtech Server specific processing

### ISSUE THREAD

**Issue by snelson-senet** [Lora-net/LoRaMac-node#94]
There is a Semtech Server bug fix in the processing of the join accept DLSettings. Shouldn't this code be Vendor neutral? 

#if defined( USE_BAND_915 ) || defined( USE_BAND_915_HYBRID )
                /*
                 * WARNING: To be removed once **Semtech server implementation**
                 *          is corrected.
                 */
                if( LoRaMacParams.Rx2Channel.Datarate == DR_3 )
                {
                    LoRaMacParams.Rx2Channel.Datarate = DR_8;
                }
#endif

**Comment by mluis1** [comment]
Actually the bug fix is neutral as DR3 (SF9BW125) datarate isn't used for downlinks in the US915 band. The downlinks datarates for US915 start at DR8(SF12BW500).

But, anyway you are right we should remove the bug fix in order to avoid confusions.
