### ISSUE TITLE
Import this source to Cube ide

### ISSUE THREAD

**Issue by templier1994** [Lora-net/LoRaMac-node#940]
Hi,

Im working on Linux ubuntu cube ide. Is there à way to importe this loramac node into it ?

I've first used the example projet given by st but it don't really match with what i have to do.

Thanx

**Comment by x893** [comment]
Hi,
i can't say about CudeIde. I use Keil for development but i think the same for Cube
Make build via cmake, save results to log and create project manually.
Need 10-15 minutes.

**Comment by mluis1** [comment]
As said by @x893 this project can be imported to any development environment.
But, this will require extra work and investigation on how to do it on your side.

As we can't provide more help on this we close the issue.
