### ISSUE TITLE
Enable I2C on B-L072Z-LRWAN1

### ISSUE THREAD

**Issue by gilbertoe** [Lora-net/LoRaMac-node#944]
Hi

I am trying to enable I2C communication on the B-L072Z-LRWAN1 board with no success. I have initialized the I2C using the I2CInit function in the BoardInitMcu as shown below:

        BoardUnusedIoInit( );

        I2cInit(&I2c, I2C_1, I2C_SCL, I2C_SDA);

The I2cWriteBuffer function call always return an error code.

Does anyone as already solved this problem? any help is welcome...

BR
Gilberto

**Comment by mklil** [comment]
pls check #945, and report back if working.

**Comment by gilbertoe** [comment]
Yes. It fixed the problem!
Thanks
