### ISSUE TITLE
Support Sleep-on-exit feature

### ISSUE THREAD

**Issue by jamesle-0812** [Lora-net/LoRaMac-node#949]
Hi there, I've worked on customized boards based on B-L072Z-LRWAN1. I also use I-CUBE-LRWAN (v1.1.4), compiled on Keil uVision. Everything works fine. I can get about 2uA in Stop mode.
Recently I'm doing a project requiring power consumption optimized so I enable Sleep-On-Exit feature. Everything is fine until enable Sleep-on-exit. It still wakes up as expected but the current consumption during stop mode is much higher than usual (about 900uA).
I've narrowed down the problem. I have a sleep function. The main block of entering stop mode is described below.
```
void Sleep(time_interval_ms)
{
...
 
DISABLE_IRQ();	// Commented out here
 
LL_LPM_EnableSleepOnExit();
// sleep
LPM_EnterStopMode();
 
//wake up
LPM_ExitStopMode();
 
...
}
 
void LPM_EnterStopMode(void)
{
  uint32_t tmpreg = 0U;
 
  BACKUP_PRIMASK();
 
  DISABLE_IRQ();
 
  HW_IoDeInit();
 
  /*clear wake up flag*/
  LL_PWR_ClearFlag_WU();
 
  RESTORE_PRIMASK();
 
  /* Enter Stop Mode - is a LL implementatin of HAL_PWR_EnterSTOPMode(PWR_LOWPOWERREGULATOR_ON, PWR_STOPENTRY_WFI) */
  /* Select the regulator state in Stop mode ---------------------------------*/
  tmpreg = PWR->CR;
 
  /* Clear PDDS and LPDS bits */
  CLEAR_BIT(tmpreg, (PWR_CR_PDDS | PWR_CR_LPSDSR));
 
  /* Set LPSDSR bit according to PWR_Regulator value */
  SET_BIT(tmpreg, LL_PWR_REGU_LPMODES_LOW_POWER);
 
  /* Store the new value */
  PWR->CR = tmpreg;
 
  /* Set SLEEPDEEP bit of Cortex System Control Register */
  LL_LPM_EnableDeepSleep();
 
  /* Select Stop mode entry --------------------------------------------------*/
  __WFI();
 
  /* Reset SLEEPDEEP bit of Cortex System Control Register */
  LL_LPM_EnableSleep();
}
```
If I comment out the DISABLE_IRQ();, the code should work fine. However, the sequence of __disable_irq and then call the sleep function is pretty similar in both LoRaMac and I-CUBE-LRWAN versions. My question is
- Why it's there because inside sleep function IRQ will be disabled again in critical section.
- If I comment out it, will it affect to any thing? Otherwise any way to work around is much appreciate.
Thanks in advance!

**Comment by mluis1** [comment]
This question is related on how the STM32 low power modes are handled.

We never investigated on how to use other STM32 low power modes as 2 uA was our target power consumption for the example projects.
The Stop sleep mode was the chosen one because it was the lowest power mode were the RAM memories were kept which simplifies the low power modes handling.

I would recommend that you ask this question directly to ST support.
