### ISSUE TITLE
Wrong FCnt in gateway

### ISSUE THREAD

**Issue by ImanIDG** [Lora-net/LoRaMac-node#951]
Hi there. I'm using LoRaMac on ST32L073RZ and SX1276 (EU868 Region). I tried to modify this code for my purpose but now i face an interesting problem. At transmission, I cant see my node on Server. when i checked, the problem was wrong fcnt and devaddr reading in gateway. 
you can see the mac frame sent to sx1276. I set 0x11111111 as devaddr but i get 1111400D in gateway. also instead of fcnt = 1, i get 32785 (0x8011) in gateway. it seems the tx frame got shifted for two bytes when sx1276 tries to send it but i cant find the source of this issue. I have checked preamble length but it's ok.

![image](https://user-images.githubusercontent.com/44342542/90311141-4ac1b880-df0d-11ea-8d23-6a77a7fc0947.png)

**Comment by mklil** [comment]
in case you did modify the spi init  code in (spi-board.c), check if you have the right clk phase and polarity settings.

**Comment by mluis1** [comment]
We close the issue then.
