### ISSUE TITLE
Joint Faliure with B-L072Z-LRWAN1 and Everynet

### ISSUE THREAD

**Issue by gilbertoe** [Lora-net/LoRaMac-node#953]
Hi

I am using a B-L072Z-LRWAN1 and the LoRaMac-Node stack. I have modified the band according the so called LA915 region. Everything works fine. However, I noticed that sometimes, alter a  software update (with the previous working firmware), the end-node is not able to Joint the network. In this situation the only way to Join again is to way several hours. The Lorawan network operator in Brazil is Everynet. The Rx1 and Rx2 delays are 5 and 6 seconds respectively.

The software stack reports a RX2 window time out.

Does some have already experienced a problem like this one? I am wondering if the network has any kind of protection to detected tha a device has chanced.

BR
Gilberto

**Comment by FoujanetG** [comment]
Check the _DevNonce_ value of the join request.
If you enable the Secure Element software, the _DevNonce_, for a new join request, starts from 0 and is incremeted at each join request message.    
The LoRaMAC specification says that LoRaWAN servers keep tracks of a certain number of _DevNonce_ value used by the device. and ignore join request with any of these _DevNonce_.( Security mechanism)

with `SECURE_ELEMENT":"SOFT_SE` of the _setting.json_ file,
you must wait to increment a new _devnonce_ if the server check _DevNonce_ value.

A workaround is to change the increment of the _devnonce_ value with a random value, as:
in _LoRaMAcCrypto.c_ file:
```
#if ( USE_RANDOM_DEV_NONCE == 1 )
    uint32_t devNonce = 0;
    SecureElementRandomNumber( &devNonce );
    CryptoCtx.NvmCtx->DevNonce = devNonce;
#else
    //CryptoCtx.NvmCtx->DevNonce++;
    CryptoCtx.NvmCtx->DevNonce=randr(1,255);
#endif
```

or to be cleaner, you can create an interface _soft-se_  to use the function _SecureElementRandomNumber()_ to generate a random _devnonce_.

guillaume

**Comment by gilbertoe** [comment]
Hi

The USE_RANDOM_DEV_NONCE is set. So, DevNonce is already generated by random. What do you meant "by enable the Secure Element software"? Is there a way do disable it?

BR
Gilberto
