### ISSUE TITLE
SECURE_ELEMENT_PIN

### ISSUE THREAD

**Issue by gilbertoe** [Lora-net/LoRaMac-node#957]
Hi

We am trying upgrade a device from a previous release to V.4.4.4. The SECURE_ELEMENT_PIN is a new parameter. What it's purpose?

BR
Gilberto

**Comment by mluis1** [comment]
The `SECURE_ELEMENT_PIN` parameter is only required when using Semtech Join Server cloud service. This parameters is used to claim an end-device ownership.
You may find more information at https://www.loracloud.com/documentation/join_service?url=index.html

Currently, it is manly used when using LR1110 radios which are pre-provisioned at factory.

In all other cases this parameter is currently not used.
