### ISSUE TITLE
Problem with FSK50 maximum payload test

### ISSUE THREAD

**Issue by Pirakutu** [Lora-net/LoRaMac-node#965]
Hi guys,

I am having problems passing the FSK50 maximum payload test on the new EU868 specs with the stack v4.4.4, is this problem known to any of you? Thanks!

Cheers,

Andres

**Comment by Pirakutu** [comment]
Another question, shall i go with the master or with the release version? ive seen there have been some fixes made on the master branch, how far checked are these fixes?

**Comment by mluis1** [comment]
Could you please check if commit f8d1950619d0d1f2c835d5df3eb719cbcb85a3e9 solves your issue?

We noticed that using FifoEmpty IRQ was too much constraint when the MCU was using low power modes.
In order to solve that we changed the IRQ to FifoLevel instead.

**Comment by mluis1** [comment]
Master branch is most of the time stable. Prior to push to GitHub we usually perform some internal tests.

In may happen time to time that it gets not stable. Most of the time it happens when we accept pull-requests on GitHub.

**Comment by Pirakutu** [comment]
Thanks, will test this and come back to you (it will probably be next year as we went ahead and certified the device without this option, it would still be interessting to have it working though)

**Comment by mluis1** [comment]
Had you some time to perform your checks?
Can we close this issue?

**Comment by mluis1** [comment]
No feedback, we close the issue.
