### ISSUE TITLE
CLASS_B examples

### ISSUE THREAD

**Issue by x893** [Lora-net/LoRaMac-node#97]
Hi,
can't find any CLASS_B example. In folder ClassB main.c use CLASS_A settings.
Can you explain how to CLASS_B check ?
Simple change CLASS_A to CLASS_A ?

Thanks

**Comment by nestorayuso** [comment]
Did you see the branch feature/class_b ?
https://github.com/Lora-net/LoRaMac-node/tree/feature/class_b

**Comment by x893** [comment]
Ops, need increase telepatic feature. Now i see in details.

Thanks !!!
