### ISSUE TITLE
Can't activate on RU864 region

### ISSUE THREAD

**Issue by Xeenych** [Lora-net/LoRaMac-node#979]
I have wap LoRa8 Kit gateway.
I'm using a custom board similar to Skim880b.

When region is set to EU868 (on node and on gateway) OTAA activation completes succesfully.

When region is set to RU864, board can't activate.

On the gateway I see join request, and then join accept. RSSI is -60dB, SNR is 10dB.
Board sometimes shows Rx2 Timeout and sometimes Rx2 Error, which is caused by CRC error internally from Sx1272 chip interrupt.

Using 4.4.5 release

**Comment by altishchenko** [comment]
Does your gateway/network server configuration match the RU864 configuration of the library? There are two RU864 config variants I know of. Make sure that your network server/gateway uses 869.1 MHz as an RX2 frequency with full DR range,

**Comment by Xeenych** [comment]
I don't know.
There is mikrotik router OS v6.46.1 and only single RU864 option

**Comment by altishchenko** [comment]
And what is the network server in use? (you can drop me a message at atishch @ gmail.com as this issue looks more of a network config problem then library issue).

**Comment by Xeenych** [comment]
i'm using router.eu.thethings.network
I've sent you a email message

**Comment by Xeenych** [comment]
It is strange but
switching to digitalcatapult-uk-router (ttn.thethingsconnected.net) solved the problem
