### ISSUE TITLE
LoRaMac ClassA - DEVICE STATE SEND LOGIC

### ISSUE THREAD

**Issue by gilbertoe** [Lora-net/LoRaMac-node#988]
Hi
Could you please someone give some information on the logic behind the NextTx variable that is used to control the call to SendFrame() in the DEVICE_STATE_SEND state? The application is classA. It is set in OnTxNextPacketTimerEvent.
Best Regards
Gilberto

**Comment by mluis1** [comment]
I provided an explanation on how the transmissions are handled on issue https://github.com/Lora-net/LoRaMac-node/issues/993
