### ISSUE TITLE
Join AlternateDatarate() conditions

### ISSUE THREAD

**Issue by Mobiak** [Lora-net/LoRaMac-node#99]
Function AlternateDatarate() is a good idea to get the best gateway of the network. But there is a mistake in if/else, the device will try 
DR_5 seven times, DR_4 one time, 
DR_5 seven times, DR_3 one time, 
DR_5 seven times, DR_2 one time, 
DR_5 seven times, DR_1 one time, 
DR_5 seven times, DR_4 one time, 
DR_5 seven times, DR_0 one time, 
and repeat this cycle.

Ifs and elses should be using >= instead of %. 

```
    if( nbTrials >= 48 )
    {
        datarate = DR_0;
    }
    else if( nbTrials >= 32 )
    {
        datarate = DR_1;
    }
    else if( nbTrials >= 24 )
    {
        datarate = DR_2;
    }
    else if( nbTrials >= 16 )
    {
        datarate = DR_3;
    }
    else if( nbTrials >= 8 )
    {
        datarate = DR_4;
    }
    else
    {
        datarate = DR_5;
    }
```

**Comment by djaeckle** [comment]
Hi Mobiak,

thanks for your report. The implementation as is was implemented according to feedback of the LoRa Alliance. The idea behind the implementation is, that it respects the EU868 ETSI duty cycle restrictions.
