### ISSUE TITLE
Fix STM platforms IRQ handlers when using a C++ compiler

### ISSUE THREAD

**Issue by mluis1** [Lora-net/LoRaMac-node#996]
Followup issue for pull-requests https://github.com/Lora-net/LoRaMac-node/pull/974 and https://github.com/Lora-net/LoRaMac-node/pull/975

The attached patch should fix the observed problem.
[cpp-irq-extern-c-wrapper.patch.txt](https://github.com/Lora-net/LoRaMac-node/files/5602244/cpp-irq-extern-c-wrapper.patch.txt)

@Xeenych Could you please verify this proposition?

**Comment by Xeenych** [comment]
Sorry, I don't know how to read or use this patch.

**Comment by mluis1** [comment]
On a terminal window go to the repository directory. Copy the patch file to that directory.
Then execute below commands in order to apply the patch. 1st we set the repository to master branch, 2nd we update the repository with latest changes on GitHub and then 3rd we apply the patch.

```bash
$ cd <path to your repository directory>/loramac-node
$ git checkout master
$ git pull -v
$ git apply cpp-irq-extern-c-wrapper.patch.txt
```

Once done you can compile your project. 
If using an IDE don't forget to move `sysIrqHandler.c` file to the right place in your project.

**Comment by mluis1** [comment]
In case it is easier I have created pull request #998.

Could you please try it?

**Comment by Xeenych** [comment]
Thanks. This works.
The new header sysIrqHandlers.h solves the issue.

**Comment by mluis1** [comment]
Nice, thanks for the feedback.
